- src/content/docs/pt-br/pages/produtos/edge-firewall/network-layer-protection/index.mdx
Related issue: [EDU-832](https://aziontech.atlassian.net/browse/EDU-832)
Changes:
* Localization from English version: content, structure, and some fixes. 
[EDU-832]: https://aziontech.atlassian.net/browse/EDU-832?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> EDU-832-PT-Network-Layer-Protection

- src/content/docs/en/pages/guides/marketplace/templates/astro-boilerplate/astro-boilerplate.mdx
- src/content/docs/pt-br/pages/guias/marketplace/templates/astro-boilerplate/astro-boilerplate.mdx
Adding new Astro boilerplate guide.
-
[EDU-2600]: https://aziontech.atlassian.net/browse/EDU-2600?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> edu-2600-astro-boilerplate-guide

- src/content/docs/en/pages/guides/marketplace/bot-protection/index.mdx
- src/content/docs/pt-br/pages/guias/marketplace/bot-protection/index.mdx
[EDU-2615]
Adding Preview badge to inform release stage.
N/A
[EDU-2615]: https://aziontech.atlassian.net/browse/EDU-2615?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> EDU-2615-adding-badge-in-bot-protection-guide

- src/content/docs/en/pages/guides/index.mdx
- src/content/docs/pt-br/pages/guias/guides.mdx
[EDU-2366]
Adding new section to Guides page: Azion Templates, including links to dedicated guides.
N/A
[EDU-2366]: https://aziontech.atlassian.net/browse/EDU-2366?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> edu-2366-templates-guides-page

- src/content/docs/en/pages/guides/marketplace/templates/nextjs-static-boilerplate/nextjs-static-boilerplate.mdx
- src/content/docs/en/pages/guides/marketplace/templates/react-boilerplate/react-boilerplate.mdx
- src/content/docs/pt-br/pages/guias/marketplace/templates/next-static-boilerplate/next-static-boilerplate.mdx
[EDU-2217]
Adding new Nextjs Static boilerplate.
N/A
[EDU-2217]: https://aziontech.atlassian.net/browse/EDU-2217?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> edu-2217-guide-next-boilerplate

- src/content/docs/en/pages/azion-edge-runtime/api-reference/network-list/network-list.mdx
- src/content/docs/pt-br/pages/azion-edge-runtime/api-reference/network-list/index.mdx
[EDU-2619](https://aziontech.atlassian.net/browse/EDU-2619)
[EDU-2619]: https://aziontech.atlassian.net/browse/EDU-2619?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Adjust network list interface

- src/content/docs/en/pages/products/edge-application/l2-caching.mdx
- src/content/docs/pt-br/pages/produtos/edge-application/l2-caching/index.mdx
- Modified default region info
- Added early access note
[EDU-2571]: https://aziontech.atlassian.net/browse/EDU-2571?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-2571] Add L2 region info

- README.md
> adjust-mit-links

- src/content/docs/en/pages/api-graphql/limits/limits.mdx
- src/content/docs/en/pages/api-graphql/queries/queries.mdx
- src/content/docs/pt-br/pages/api-graphql/limites/index.mdx
- src/content/docs/pt-br/pages/api-graphql/queries/index.mdx
[ENG-27351]
* Added the new limit for Real-Time Events GQL query fields in EN and PT.
* Added note for users to check the Limits doc in EN and PT.
[ENG-27351]: https://aziontech.atlassian.net/browse/ENG-27351?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-27351] new fields limit

- src/content/docs/pt-br/pages/produtos/edge-firewall/ddos-protection/index.mdx
Tarefa relacionada: [EDU-2316]()
Alterações:
* Documentação de referência adaptada para o novo DDoS Protection Unmetered.
[EDU-2316]: https://aziontech.atlassian.net/browse/EDU-2316?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> EDU-2316-PT-New-DDoS-Unmetered-documentation

- src/content/docs/en/pages/products/edge-application/image-processor.mdx
- src/content/docs/pt-br/pages/produtos/edge-application/image-processor/index.mdx
- Added new supported parameters
- Added example with Azion logo
[EDU-2136]: https://aziontech.atlassian.net/browse/EDU-2136?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-2136] Add watermark parameters and example

- src/content/docs/en/pages/products/edge-firewall/ddos-protection/ddos-protection.mdx
- src/content/docs/pt-br/pages/produtos/edge-firewall/ddos-protection/index.mdx
Related issue: [EDU-2316](https://aziontech.atlassian.net/browse/EDU-2316)
Changes:
* Link fix on EN and PT.
[EDU-2316]: https://aziontech.atlassian.net/browse/EDU-2316?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> EDU-2316-EN-DDoS-fix-link

- src/content/docs/en/pages/guides/blacklists-ip-addresses-edge/index.mdx
- src/content/docs/en/pages/guides/index.mdx
- src/content/docs/pt-br/pages/guias/blacklists-ip-addresses-edge/index.mdx
- src/content/docs/pt-br/pages/guias/guides.mdx
Tarefa relacionada: [EDU-832](https://aziontech.atlassian.net/browse/EDU-832)
Alterações:
* Introdução da versão em PT-BR do guia de Network Lists.
* Introdução do link para este guia e para a versão em inglês, nas devidas páginas de guias EN e PT-BR.
[EDU-832]: https://aziontech.atlassian.net/browse/EDU-832?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> EDU-832-PT-guia-Network-Lists

- src/content/docs/en/pages/api-graphql/limits/limits.mdx
- src/content/docs/pt-br/pages/api-graphql/limites/index.mdx
* Added new limit for Real-Time Metrics GQL in EN and PT.
[EDU-2663]: https://aziontech.atlassian.net/browse/EDU-2663?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-2663] limits-metrics-gql

- src/content/docs/en/pages/api-graphql/error-responses/error-responses.mdx
- src/content/docs/pt-br/pages/api-graphql/mensagens-de-erro/index.mdx
[EDU-2664]
* Updated time range error message according to the new one being exhibited to users.
[EDU-2664]: https://aziontech.atlassian.net/browse/EDU-2664?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-2664] time-range-message-gql

- src/content/docs/en/pages/api-graphql/features/events-fields/events-fields.mdx
* Updated description of 2 variables after talking to TM in EN ✌️ 
[EDU-2591]: https://aziontech.atlassian.net/browse/EDU-2591?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-2591] update-variables-gql-l2

- src/content/docs/en/pages/api-graphql/features/events-fields/events-fields.mdx
- src/content/docs/en/pages/api-graphql/features/features.mdx
- src/content/docs/pt-br/pages/api-graphql/recursos/events-campos/events-campos.mdx
- src/content/docs/pt-br/pages/api-graphql/recursos/index.mdx
[EDU-2567] [EDU-2568]
* Added activityHistoryEvents dataset in PT.
* Changed the dataset to alphabetical order in EN.
* Added a button taking to the Events GQL fields doc.
* Updated the name of the Metrics GQL fields doc on a button.
[EDU-2567]: https://aziontech.atlassian.net/browse/EDU-2567?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[EDU-2568]: https://aziontech.atlassian.net/browse/EDU-2568?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-2567] [EDU-2568] activity-history-dataset-alphabetical-order

- src/content/docs/pt-br/pages/api-graphql/recursos/events-campos/events-campos.mdx
* Updated 2 variables descriptions in PT after talking to TM :D 
[EDU-2591]: https://aziontech.atlassian.net/browse/EDU-2591?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-2591] update-variables-gql-l2-pt

- src/content/docs/en/pages/products/edge-application/rules-engine.mdx
- src/content/docs/pt-br/pages/produtos/edge-application/rules-engine/index.mdx
- Removed unnecessary description of Forward Cookies behavior
- Fixed regex for Rewrite Request behavior
> [HOTFIX] Fix Forward Cookies desc and Rewrite Req regex

- src/content/docs/en/pages/main-menu/before-begin/core-concepts.mdx
- src/content/docs/en/pages/main-menu/before-begin/get-help.mdx
- src/content/docs/en/pages/main-menu/get-started/go-live-with-azion.mdx
- src/content/docs/pt-br/pages/menu-principal/antes-de-comecar/conceitos-basicos.mdx
- src/content/docs/pt-br/pages/menu-principal/ponto-de-partida/ponto-de-partida.mdx
- src/content/docs/pt-br/pages/menu-principal/ponto-de-partida/rodar-na-azion.mdx
Fixes in new menu: graphic, links, and a broken component.
> fixes-new-menu

- src/content/docs/en/pages/main-menu/before-begin/core-concepts.mdx
- src/content/docs/en/pages/main-menu/get-started/get-started.mdx
- src/content/docs/pt-br/pages/menu-principal/antes-de-comecar/conceitos-basicos.mdx
- src/content/docs/pt-br/pages/menu-principal/ponto-de-partida/ponto-de-partida.mdx
Deleting learning section links.
N/A.
> fix-core-concepts

- src/content/docs/en/pages/main-menu/reference/build/edge-application/rules-engine.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/build/edge-application/rules-engine-edge-app.mdx
- Updated behavior list in EN
- Modified debug link text
> [HOTFIX] rules engine

- src/content/docs/en/pages/guides/index.mdx
- src/content/docs/pt-br/pages/guias/guides.mdx
N/A.
Adjusting guides page to delete next.js link to guide and reduce visibility.
The template is been refined and will be launch later. 
N/A.
> adjust-templates-guides

- src/content/docs/pt-br/pages/menu-principal/recursos-adicionais/developer-tools/primeiros-passos-api.mdx
Tarefa relacionada: [EDU-2367](https://aziontech.atlassian.net/browse/EDU-2367)
Alterações:
* Introdução da documentação `Primeiros passos com a API da Azion`.
[EDU-2367]: https://aziontech.atlassian.net/browse/EDU-2367?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> EDU-2367-PT-Create-API-overview

- src/content/docs/en/pages/main-menu/additional-resources/developer-tools/getting-started-api.mdx
* Updated namespace to match PT version
* Updated URL path to avoid redirect
> [HOTFIX] fix namespace and url API overview

- src/content/docs/en/pages/main-menu/work-with-domains/configure-domains.mdx
- src/content/docs/en/pages/main-menu/work-with-domains/create-certificate.mdx
- src/content/docs/en/pages/main-menu/work-with-domains/migrate-ns.mdx
- src/content/docs/en/pages/main-menu/work-with-domains/point-domain.mdx
- src/content/docs/pt-br/pages/build-jornada/configuracoes-avancadas/multiple-origins.mdx
- src/content/docs/pt-br/pages/build-jornada/configuracoes-avancadas/processar-imagens.mdx
- src/content/docs/pt-br/pages/build-jornada/edite-edge-app/functions-instances.mdx
- src/content/docs/pt-br/pages/build-jornada/edite-edge-app/origins.mdx
- src/content/docs/pt-br/pages/build-jornada/edite-edge-app/rules-engine.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/build/edge-application/application-acceleration.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/build/edge-application/cache-settings.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/build/edge-application/device-groups.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/build/edge-application/error-responses.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/build/edge-application/image-processor.mdx
- src/content/docs/pt-br/pages/menu-principal/trabalhe-com-dominios/apontar-dominio.mdx
- src/content/docs/pt-br/pages/menu-principal/trabalhe-com-dominios/configurar-dominio.mdx
- src/content/docs/pt-br/pages/menu-principal/trabalhe-com-dominios/criar-certificado.mdx
- src/content/docs/pt-br/pages/menu-principal/trabalhe-com-dominios/migrar-ns.mdx
- Improved wording and structure in domain journey
- Fixed a translation inconsistency in build documentation
[EDU-2721]: https://aziontech.atlassian.net/browse/EDU-2721?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-2721] Adjust WWD journey content

- src/content/docs/en/pages/main-menu/manage-accounts/create-accountd.mdx
- src/content/docs/en/pages/main-menu/manage-accounts/manage-account/activity-history.mdx
- src/content/docs/en/pages/main-menu/manage-accounts/manage-account/billing-and-subscriptions.mdx
- src/content/docs/en/pages/main-menu/manage-accounts/manage-account/credentials.mdx
- src/content/docs/en/pages/main-menu/manage-accounts/manage-account/mfa.mdx
- src/content/docs/en/pages/main-menu/manage-accounts/manage-account/sso.mdx
- src/content/docs/en/pages/main-menu/manage-accounts/manage-account/teams-permissions.mdx
- src/content/docs/en/pages/main-menu/manage-accounts/manage-account/users.mdx
- src/content/docs/en/pages/main-menu/manage-accounts/manage-profile/delete-account.mdx
- src/content/docs/en/pages/main-menu/manage-accounts/manage-profile/personal-token.mdx
- src/content/docs/en/pages/main-menu/manage-accounts/manage-profile/settings.mdx
- src/content/docs/en/pages/main-menu/reference/accounts/users-management.mdx
- src/content/docs/pt-br/pages/menu-principal/gerencie-contas/gerenciar-contas/activity-history.mdx
- src/content/docs/pt-br/pages/menu-principal/gerencie-contas/gerenciar-contas/faturamento-e-assinaturas.mdx
- src/content/docs/pt-br/pages/menu-principal/gerencie-contas/gerenciar-contas/mfa.mdx
- src/content/docs/pt-br/pages/menu-principal/gerencie-contas/gerenciar-contas/sso.mdx
- src/content/docs/pt-br/pages/menu-principal/gerencie-contas/gerenciar-contas/times-permissoes.mdx
- src/content/docs/pt-br/pages/menu-principal/gerencie-contas/gerenciar-contas/usuários.mdx
- src/content/docs/pt-br/pages/menu-principal/gerencie-contas/gerenciar-perfis/personal-token.mdx
- Keep PT and EN consistent
- Added small descriptions to some pages
[EDU-2722]: https://aziontech.atlassian.net/browse/EDU-2722?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-2722] Adjust Accounts content

- .github/CONTRIBUTING.md
* Added links to code owners profiles.
> code owners profile links

- src/content/docs/pt-br/pages/menu-principal/referencia/secure/edge-firewall/ddos-protection.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/secure/edge-firewall/edge-firewall.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/secure/edge-firewall/edge-functions-firewall.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/secure/edge-firewall/edge-functions-instances-para-edge-firewall.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/secure/edge-firewall/network-layer-protection.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/secure/edge-firewall/network-lists.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/secure/edge-firewall/rules-engine-edge-firewall.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/secure/edge-firewall/waf-custom-allowed-rules.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/secure/edge-firewall/waf-rule-sets.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/secure/edge-firewall/web-application-firewall.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/secure/intelligent-dns/dnssec.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/secure/intelligent-dns/intelligent-dns.mdx
* Changed `>` to Astro componentes in Secure docs in PT.
[EDU-2191]: https://aziontech.atlassian.net/browse/EDU-2191?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> componentes

- src/content/docs/pt-br/pages/menu-principal/referencia/secure/edge-firewall/waf-custom-allowed-rules.mdx
* Fixed namespace in PT to match EN doc.
[EDU-2781]: https://aziontech.atlassian.net/browse/EDU-2781?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [HOTFIX] namespace waf custom allowed rules pt

- src/content/docs/en/pages/main-menu/reference/build/edge-application/main-settings.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/build/edge-application/main-settings.mdx
- Added experimental badge to HTTP/3
> [HOTFIX] Add experimental badge to HTTP3 doc

- src/content/docs/en/pages/guides/access-rtm/access-rtm.mdx
- src/content/docs/pt-br/pages/guias/acessar-rtm/acessar-rtm.mdx
[EDU-2660]
Add PT and EN version of the guide on how to access rtm.
n/a.
[EDU-2660]: https://aziontech.atlassian.net/browse/EDU-2660?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> EDU-2660-access-rtm

- src/content/docs/en/pages/guides/run-the-dig-command/index.mdx
> Alteração da url do youtube

- src/content/docs/pt-br/pages/devtools/api-graphql/recursos/events-campos/events-campos.mdx
* Arrumei um typo em um campo.
* Adicionei exemplos nos campos que estavam faltando.
[EDU-2841]: https://aziontech.atlassian.net/browse/EDU-2841?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[EDU-2864]: https://aziontech.atlassian.net/browse/EDU-2864?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> exemplos GQL events

- src/content/docs/en/pages/marketplace/templates-and-integrations/install-an-integration.mdx
- src/content/docs/en/pages/marketplace/templates-and-integrations/overview.mdx
- src/content/docs/en/pages/marketplace/templates-and-integrations/understand-azion-integrations.mdx
- src/content/docs/en/pages/marketplace/templates-and-integrations/understand-azion-templates.mdx
- src/content/docs/en/pages/marketplace/templates-and-integrations/update-an-integration.mdx
[EDU-2225]
Add new content related to **Templates and Integrations** section, including:
- Overview
- Undestand templates
- Undertand integrations
- Install an integration
- Update an integration
Use a template guide was already created with Get Started section.
N/A
[EDU-2225]: https://aziontech.atlassian.net/browse/EDU-2225?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> EDU-2225-templates-and-integrations-content

- src/content/docs/en/pages/marketplace/templates-and-integrations/overview.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/marketplace/marketplace.mdx
- src/content/docs/pt-br/pages/menu-principal/templates-e-integracoes/overview.mdx
[EDU-2523]
- Fixed broken link
- Style adjustment
n/a.
[EDU-2523]: https://aziontech.atlassian.net/browse/EDU-2523?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> edu-2523-fixes-link-marketplace

- src/content/docs/en/pages/main-menu/reference/observe/data-streaming/data-streaming.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/observe/data-streaming/data-streaming.mdx
> [HOTFIX] Remove double declaration DTS

- src/content/docs/en/pages/main-menu/reference/observe/real-time-events/real-time-events.mdx
* Added or fixed examples for fields that didn't have them.
[EDU-2445]: https://aziontech.atlassian.net/browse/EDU-2445?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-2445] add examples rte

- src/content/docs/pt-br/pages/menu-principal/referencia/secure/edge-firewall/network-lists.mdx
* Added info for comment and due date feature on network lists.
* Added examples.
[EDU-2863]: https://aziontech.atlassian.net/browse/EDU-2863?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-2863] add comentario e data feature network list

- .github/CONTRIBUTING.md
> fix: uxe team

- src/content/docs/en/pages/main-menu/reference/build/edge-application/edge-application.mdx
- src/content/docs/en/pages/main-menu/reference/build/edge-application/first-steps.mdx
- src/content/docs/en/pages/main-menu/reference/build/edge-application/websocket.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/build/edge-application/edge-app-primeiros-passos.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/build/edge-application/edge-application.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/build/edge-application/websocket.mdx
- Added websocket links and PT docs back
> [HOTFIX] docs: return websocket

- src/content/docs/pt-br/pages/devtools/api-graphql/recursos/events-campos/events-campos.mdx
* Adicionei novos campos, suas descrições e seus exemplos.
[EDU-2840]: https://aziontech.atlassian.net/browse/EDU-2840?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-2840] add campos activity history graphQL

- src/content/docs/en/pages/main-menu/reference/build/edge-application/digital-certificates.mdx
- src/content/docs/en/pages/main-menu/reference/build/edge-application/rules-engine.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/build/edge-application/digital-certificates.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/build/edge-application/rules-engine-edge-app.mdx
- Improved explanation of variables as arguments
- Clarified "function" variables
- Fixed Digital Certificates heading hierarchy and section title
[EDU-2771]: https://aziontech.atlassian.net/browse/EDU-2771?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-2771] docs: improve old functions section in Rules Engine

- src/content/docs/pt-br/pages/guias/marketplace/ab-testing-marketplace/index.mdx
[EDU-2289] 
- Fixing contributors' import to avoid errors while merging.
n/a
[EDU-2289]: https://aziontech.atlassian.net/browse/EDU-2289?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: contributors import

- src/content/docs/en/pages/devtools/cli/azion-cli-alpha/azion-overview/azion-overview.mdx
- src/content/docs/pt-br/pages/devtools/cli/azion-cli-alpha/azion-overview/azion-overview.mdx
https://aziontech.atlassian.net/browse/EDU-3230
> [EDU-3230] add debian install to cli overview

- src/content/docs/en/pages/main-menu/reference/build/edge-application/load-balancer.mdx
- src/content/docs/en/pages/main-menu/reference/build/edge-application/origins.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/build/edge-application/load-balancer.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/build/edge-application/origins.mdx
- Added note to timeout to contact support
- Added behavior to balancing method
https://aziontech.slack.com/archives/C05DRB16170/p1695644703084199
> [HOTFIX] fix: add note about lb error behavior and timeout config

- src/content/docs/en/pages/devtools/api-graphql/features/features.mdx
* Added Resample feature to Real-Time Metrics GraphQL API.
[EDU-2497]: https://aziontech.atlassian.net/browse/EDU-2497?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-2497] feat: graphql resample

- src/content/docs/pt-br/pages/devtools/api-graphql/recursos/index.mdx
* Adicionei seção sobre o recurso Reamostrar.
[EDU-2497]: https://aziontech.atlassian.net/browse/EDU-2497?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-2497] feat: add reamostrar

- src/content/docs/en/pages/devtools/cli/azion-cli-alpha/domains/domains.mdx
- src/content/docs/en/pages/devtools/cli/azion-cli-alpha/edge-application/edge-application.mdx
- src/content/docs/en/pages/devtools/cli/azion-cli-alpha/personal-tokens/personal-tokens.mdx
- src/content/docs/en/pages/devtools/cli/azion-cli-alpha/rules-engine/rules-engine.mdx
- src/content/docs/pt-br/pages/devtools/cli/azion-cli-alpha/domains/domains.mdx
- src/content/docs/pt-br/pages/devtools/cli/azion-cli-alpha/edge-application/edge-application.mdx
- src/content/docs/pt-br/pages/devtools/cli/azion-cli-alpha/personal-tokens/personal-tokens.mdx
- src/content/docs/pt-br/pages/devtools/cli/azion-cli-alpha/rules-engine/rules-engine.mdx
https://aziontech.atlassian.net/browse/EDU-3253
> [EDU-3235] refactor: change in to file cli flags

- src/content/docs/en/pages/devtools/cli/azion-cli-alpha/edge-functions/edge-functions.mdx
https://aziontech.atlassian.net/browse/EDU-3250
> [EDU-3250] feat: add edge functions command ref

- src/content/docs/en/pages/devtools/cli/azion-cli-alpha/origins/origins.mdx
https://aziontech.atlassian.net/browse/EDU-3247
> [EDU-3247] feat: origin CRUD cli

- src/content/docs/en/pages/main-menu/reference/services/support/business-events-support.mdx
- src/content/docs/en/pages/main-menu/reference/services/support/technical-support.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/servicos/business-support-events.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/servicos/technical-support.mdx
- Changed wording in BES
- Added ticket types
- Added definition on ticket type severities
[EDU-3009]: https://aziontech.atlassian.net/browse/EDU-3009?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-3009] refactor: modified support tickets and BES

- src/content/docs/pt-br/pages/devtools/cli/azion-cli-alpha/cache-settings/cache-settings.mdx
https://aziontech.atlassian.net/browse/EDU-3244
> EDU-3244-cache-settings-cli-pt

- src/content/docs/en/pages/devtools/cli/azion-cli-alpha/origins/origins.mdx
- src/content/docs/pt-br/pages/devtools/cli/azion-cli-alpha/origins/origins.mdx
https://aziontech.atlassian.net/browse/EDU-3247
> EDU-3247-origins-cli-pt

- src/content/docs/en/pages/devtools/cli/azion-cli-alpha/edge-functions/edge-functions.mdx
- src/content/docs/pt-br/pages/devtools/cli/azion-cli-alpha/edge-functions/edge-functions.mdx
https://aziontech.atlassian.net/browse/EDU-3250
> [EDU-3250] edge-function cli pt

- src/content/docs/en/pages/main-menu/reference/secure/edge-firewall/edge-firewall.mdx
* Added an H3 and moved a button for better content flow.
[EDU-2414]: https://aziontech.atlassian.net/browse/EDU-2414?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-2414] feat: add rules engine H3

- src/content/docs/pt-br/pages/menu-principal/antes-de-comecar/conceitos-basicos.mdx
This PR modifies the translation of "Estándares abertos" to "Padrões abertos".
> Adjust translation from "Estándares abertos" to "Padrões abertos"

- src/content/docs/pt-br/pages/guias/debug-regras/index.mdx
- Remove early access note from PT version
> [HOTFIX] fix: remove early access note

- src/content/docs/pt-br/pages/menu-principal/referencia/secure/edge-firewall/edge-firewall.mdx
* Added an H3 for Rules Engine and moved a button for better content flow.
[EDU-2414]: https://aziontech.atlassian.net/browse/EDU-2414?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-2414] feat: add rules engine H3 pt

- src/content/docs/en/pages/devtools/azion-edge-runtime/overview/overview.mdx
- src/content/docs/pt-br/pages/devtools/azion-edge-runtime/visao-geral/visao-geral-runtime.mdx
https://aziontech.atlassian.net/browse/EDU-3344
> [EDU-3344] add frameworks runtime overview

- src/content/docs/en/pages/devtools/api-graphql/first-steps/first-steps.mdx
- src/content/docs/en/pages/guides/intelligent-dns/run-the-dig-command/index.mdx
Update dos links dos vídeos do Youtube Dig Command e GraphQL nas respectivas doc's
[EDU-3227]: https://aziontech.atlassian.net/browse/EDU-3227?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-3227] - fix: update links videos

- src/content/docs/en/pages/guides/marketplace/templates/angular-boilerplate/angular-boilerplate.mdx
- src/content/docs/en/pages/guides/marketplace/templates/astro-boilerplate/astro-boilerplate.mdx
- src/content/docs/en/pages/guides/marketplace/templates/chatgpt-plugin/chatgpt-plugin.mdx
- src/content/docs/en/pages/guides/marketplace/templates/qstash-scheduler/qstash-scheduler.mdx
- src/content/docs/en/pages/guides/marketplace/templates/react-boilerplate/react-boilerplate.mdx
- src/content/docs/en/pages/guides/marketplace/templates/upstash-geolocation/upstash-geolocation.mdx
- src/content/docs/en/pages/guides/marketplace/templates/upstash-rate-limiting/upstash-rate-limiting.mdx
- src/content/docs/en/pages/guides/marketplace/templates/vue-boilerplate/vue-boilerplate.mdx
- src/content/docs/en/pages/guides/marketplace/templates/wordpress-edgeaccelerator/wordpress-edgeaccelerator.mdx
- src/content/docs/en/pages/guides/marketplace/templates/wordpress-instacreator/wordpress-instacreator.mdx
- src/content/docs/pt-br/pages/guias/marketplace/angular-boilerplate/angular-boilerplate.mdx
- src/content/docs/pt-br/pages/guias/marketplace/chatgpt-plugin/chatgpt-plugin.mdx
- src/content/docs/pt-br/pages/guias/marketplace/qstash-scheduler/qstash-scheduler.mdx
- src/content/docs/pt-br/pages/guias/marketplace/templates/astro-boilerplate/astro-boilerplate.mdx
- src/content/docs/pt-br/pages/guias/marketplace/templates/react-boilerplate/react-boilerplate.mdx
- src/content/docs/pt-br/pages/guias/marketplace/templates/vue-boilerplate/vue-boilerplate.mdx
- src/content/docs/pt-br/pages/guias/marketplace/upstash-geolocation/upstash-geolocation.mdx
- src/content/docs/pt-br/pages/guias/marketplace/upstash-rate-limiting/upstash-rate-limiting.mdx
- src/content/docs/pt-br/pages/guias/marketplace/wordpress-instacreator/wordpress-instacreator.mdx
Templates guides:
- Deleting non-relevant links.
- Updating links to more specific docs.
n/a.
> [EDU-3204] fix: deleting non-relevant links - Templates guides

- src/content/docs/en/pages/secure-journey/transport-layer-security/ciphers.mdx
- src/content/docs/pt-br/pages/menu-principal/secure-jornada/transport-layer-security/ciphers.mdx
- Added ciphers page
[EDU-3148]: https://aziontech.atlassian.net/browse/EDU-3148?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-3148] feat: secure menu > ciphers

- src/content/docs/pt-br/pages/menu-principal/referencia/build/edge-application/edge-caching.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/build/edge-application/real-time-purge.mdx
- Removed cache key format information from RTP
- Added cache key section to edge caching page
[EDU-2448]: https://aziontech.atlassian.net/browse/EDU-2448?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-2448] refactor: PT - cache keys into edge caching

- src/content/docs/en/pages/secure-journey/advanced-configurations/activate-ddos.mdx
* Added new page for Activate DDoS for Secure menu.
[EDU-3136]: https://aziontech.atlassian.net/browse/EDU-3136?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-3136] feat: add activate ddos

- src/content/docs/en/pages/secure-journey/advanced-configurations/tune-waf.mdx
* Added new guide on How to tune WAF.
[EDU-3142]: https://aziontech.atlassian.net/browse/EDU-3142?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-3142] feat: ad tune waf guide

- src/content/docs/en/pages/secure-journey/secure-infrastructure.mdx
* Added new page on Secure an infrastructure.
Note: Some links aren't working yet.
[EDU-3118]: https://aziontech.atlassian.net/browse/EDU-3118?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-3118] feat: add secure infrastructure

- src/content/docs/en/pages/secure-journey/secure-dns.mdx
* Added new page on Secure DNS.
Note: some links aren't working yet.
[EDU-3121]: https://aziontech.atlassian.net/browse/EDU-3121?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-3121] feat: add secure DNS

- src/content/docs/en/pages/secure-journey/edit-edge-firewall/edit-main-settings.mdx
* Added new Edit main Settings page for Secure Menu.
[EDU-3124]: https://aziontech.atlassian.net/browse/EDU-3124?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-3124] feat: add configure main settings

- src/content/docs/en/pages/secure-journey/secure-application.mdx
* Added new page with Secure an application content.
Note: Some links aren't working yet.
[EDU-3115]: https://aziontech.atlassian.net/browse/EDU-3115?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-3115] feat: add secure application

- src/content/docs/en/pages/secure-journey/transport-layer-security/digital-certificates.mdx
- src/content/docs/pt-br/pages/secure-jornada/advanced-configurations/ative-ddos.mdx
- src/content/docs/pt-br/pages/secure-jornada/transport-layer-security/digital-certificates.mdx
* Added new page for Ative DDoS.
* Fix a componente and temporarily removed another one.
[EDU-3136]: https://aziontech.atlassian.net/browse/EDU-3136?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-3136] feat: add ative ddos

- src/content/docs/pt-br/pages/secure-jornada/editar-edge-firewall/configuracoes-principais.mdx
* Added new page for Definir configurações principais de um edge firewall
[EDU-3124]: https://aziontech.atlassian.net/browse/EDU-3124?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-3124] feat: definir configs principais

- src/content/docs/en/pages/secure-journey/transport-layer-security/digital-certificates.mdx
- src/content/docs/pt-br/pages/secure-jornada/advanced-configurations/tune-waf.mdx
- src/content/docs/pt-br/pages/secure-jornada/transport-layer-security/digital-certificates.mdx
* Added new page for Tune WAF in PT.
* Removed component.
[EDU-3142]: https://aziontech.atlassian.net/browse/EDU-3142?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-3142] feat: add tune WAF PT

- src/content/docs/pt-br/pages/secure-jornada/proteja-aplicacao.mdx
* Added page for Proteja uma aplicação.
[EDU-3115]: https://aziontech.atlassian.net/browse/EDU-3115?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-3115] feat: add proteja aplicacao

- src/content/docs/pt-br/pages/secure-jornada/proteja-infraestrutura.mdx
* Added page for Proteja uma infraestrutura.
[EDU-3118]: https://aziontech.atlassian.net/browse/EDU-3118?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-3118] proteja infraestrutura

- src/content/docs/pt-br/pages/secure-jornada/automate/sdk.mdx
- [EDU-3163](https://github.com/aziontech/docs/pull/482)
Changes
- Traduz docs de automate secure - edge functions e APIs
[EDU-3163]: https://aziontech.atlassian.net/browse/EDU-3163?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-3163] feat: automate secure sdk pt

- src/content/docs/pt-br/pages/secure-jornada/automate/edge-functions-apis.mdx
Related issue
- [EDU-3160](https://aziontech.atlassian.net/browse/EDU-3160 )
Changes
- Traduz docs de automate secure - edge functions e APIs
[EDU-3160]: https://aziontech.atlassian.net/browse/EDU-3160?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-3160] feat: automate sec - edge functions and apis

- src/content/docs/en/pages/secure-journey/transport-layer-security/mtls.mdx
- src/content/docs/pt-br/pages/menu-principal/secure-jornada/transport-layer-security/mtls.mdx
- Added new mTLS guide
- Should replace old mTLS guide
[EDU-3149]: https://aziontech.atlassian.net/browse/EDU-3149?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-3149] feat: secure menu > mtls

- src/content/docs/en/pages/guides/grafana/grafana-cloud/index.mdx
* Added a disclaimer regarding management of the proposed Grafana Cloud plugin.
[EDU-3284]: https://aziontech.atlassian.net/browse/EDU-3284?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-3284] refactor: add disclaimer grafana cloud

- src/content/docs/en/pages/build-journey/develop-with-azion/frameworks/framework-overview.mdx
- src/content/docs/pt-br/pages/build-jornada/desenvolva-com-azion/guias-frameworks/framework-overview.mdx
[EDU-3552] https://aziontech.atlassian.net/browse/EDU-3552)
Changes
For example:
- add new buttons to compatibility docs
- remove a paragraph 
[EDU-3552]: https://aziontech.atlassian.net/browse/EDU-3552?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-3552] feat: add new buttons to compatibility docs

- src/content/docs/en/pages/secure-journey/activate-dnssec.mdx
* Added new page on how to activate DNSSEC via API.
[EDU-3193]: https://aziontech.atlassian.net/browse/EDU-3193?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-3193] feat: add activate dnssec

- src/content/docs/en/pages/secure-journey/edit-edge-firewall/work-with-rules-engine.mdx
- src/content/docs/pt-br/pages/secure-jornada/editar-edge-firewall/rules-engine.mdx
* Added new page for Work with Rules Engine in Edge Firewall.
[EDU-3130]: https://aziontech.atlassian.net/browse/EDU-3130?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-3130] feat: add work rules engine pt

- src/content/docs/en/pages/devtools/cli/azion-cli-alpha/login/login.mdx
Related issue
[EDU-3571](https://aziontech.atlassian.net/browse/EDU-3571)
Changes
- Add login command reference
[EDU-3571]: https://aziontech.atlassian.net/browse/EDU-3571?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-3571] feat: add azion login command ref

- src/content/docs/en/pages/devtools/cli/azion-cli-alpha/logout/logout.mdx
Related issue
[EDU-3574](https://aziontech.atlassian.net/browse/EDU-3574)
Changes
- Add logout command reference
[EDU-3574]: https://aziontech.atlassian.net/browse/EDU-3574?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-3574] feat: add logout command ref cli

- src/content/docs/pt-br/pages/secure-jornada/visao-geral/visao-geral.mdx
* Added new page for Secure visão geral.
[EDU-3086]: https://aziontech.atlassian.net/browse/EDU-3086?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-3086] feat: add visão geral secure

- src/content/docs/pt-br/pages/guias/grafana/grafana-cloud/index.mdx
* Adicionei um disclaimer em um guia do Grafana Cloud.
[EDU-3284]: https://aziontech.atlassian.net/browse/EDU-3284?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-3284] feat: add disclaimer grafana cloud pt

- src/content/docs/en/pages/secure-journey/troubleshoot/intelligent-dns-understand-metrics.mdx
- Added new page on Understand metrics for Intelligent DNS.
[EDU-3196]: https://aziontech.atlassian.net/browse/EDU-3196?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-3196] feat: add understand metrics idns

- src/content/docs/en/pages/secure-journey/advanced-configurations/automate-origin-shield.mdx
- src/content/docs/en/pages/secure-journey/secure-infrastructure.mdx
* Added new guide on How to automate Origin Shield.
[EDU-3172]: https://aziontech.atlassian.net/browse/EDU-3172?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-3172] feat: add automate origin shield

- src/content/docs/en/pages/devtools/cli/azion-cli-alpha/login/login.mdx
- src/content/docs/en/pages/devtools/cli/azion-cli-alpha/logout/logout.mdx
- src/content/docs/pt-br/pages/devtools/cli/azion-cli-alpha/logout/logout.mdx
Related issue
[EDU-3574](https://aziontech.atlassian.net/browse/EDU-3574)
Changes
- Add logout command reference
[EDU-3574]: https://aziontech.atlassian.net/browse/EDU-3574?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-3574] feat: add logout command ref pt

- src/content/docs/pt-br/pages/devtools/cli/azion-cli-alpha/login/login.mdx
Related issue
[EDU-3571](https://aziontech.atlassian.net/browse/EDU-3571)
Changes
- Add login command reference
[EDU-3571]: https://aziontech.atlassian.net/browse/EDU-3571?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-3571] feat: add login command reference in pt

- src/content/docs/en/pages/main-menu/reference/secure/edge-firewall/ddos-protection/ddos-mitigation.mdx
- src/content/docs/en/pages/main-menu/reference/secure/edge-firewall/ddos-protection/ddos-protection.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/secure/edge-firewall/ddos-mitigation.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/secure/edge-firewall/ddos-protection.mdx
* Removed mentions that don't match the actual behavior.
[EDU-3584]: https://aziontech.atlassian.net/browse/EDU-3584?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-3584] refactor: remove lyr 7 mentions

- src/content/docs/en/pages/guides/marketplace/templates/nextjs-static-boilerplate/nextjs-static-boilerplate.mdx
- src/content/docs/pt-br/pages/guias/marketplace/templates/next-static-boilerplate/next-static-boilerplate.mdx
[EDU-2735]
Update Next.js Static Boilerplate guide, adding static exports section.
n/a.
[EDU-2735]: https://aziontech.atlassian.net/browse/EDU-2735?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-2735] refactor: Update Next.js Static Boilerplate guide

- src/content/docs/en/pages/changelog/changelog.mdx
- src/content/docs/en/pages/main-menu/release-notes/release-notes.mdx
- src/content/docs/pt-br/pages/changelog/changelog.mdx
- src/content/docs/pt-br/pages/menu-principal/release-notes/release-notes.mdx
- Added release notes file
[EDU-3470]: https://aziontech.atlassian.net/browse/EDU-3470?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: release notes dec-01

- src/content/docs/en/pages/secure-journey/advanced-configurations/integrate-siems.mdx
* Added new page on How to integrate WAF with SIEMs.
[EDU-3175]: https://aziontech.atlassian.net/browse/EDU-3175?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-3175] feat: add integrate siems

- src/content/docs/en/pages/secure-journey/add-records.mdx
* Added new page on How to add records.
[EDU-3181]: https://aziontech.atlassian.net/browse/EDU-3181?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-3181] feat: add add records

- .github/CONTRIBUTING.md
- .github/PULL_REQUEST_TEMPLATE.md
- Modifies some parts of the contributing guide to include cc
- Modifies PR template to include cc rules
[EDU-3337]: https://aziontech.atlassian.net/browse/EDU-3337?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-3337] refactor: add conventional commits to contributing and template

- src/content/docs/en/pages/build-journey/edit-edge-app/edit-main-settings/main-settings.mdx
- src/content/docs/pt-br/pages/build-jornada/configuracoes-avancadas/multiple-origins.mdx
- src/content/docs/pt-br/pages/build-jornada/desenvolva-com-azion/guias-frameworks/framework-angular.mdx
- src/content/docs/pt-br/pages/build-jornada/edite-edge-app/main-settings.mdx
- src/content/docs/pt-br/pages/devtools/api-graphql/recursos/events-campos/events-campos.mdx
- src/content/docs/pt-br/pages/guias/edge-application/ea-request-lets-encrypt-certificates/index.mdx
- src/content/docs/pt-br/pages/guias/edge-application/ea-test-locally/index.mdx
- src/content/docs/pt-br/pages/guias/marketplace/qstash-scheduler/qstash-scheduler.mdx
- src/content/docs/pt-br/pages/menu-principal/recursos-adicionais/templates-e-integracoes/atualizar-uma-integracao.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/build/edge-application/digital-certificates.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/build/edge-application/domains/domains.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/build/edge-application/rules-engine-edge-app.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/glossario/glossario.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/marketplace/marketplace-seller-guide.mdx
- src/content/docs/pt-br/pages/menu-principal/trabalhe-com-dominios/configurar-dominio.mdx
- Fixed anchor links with special characters
- Modified main settings heading to fit standard
[EDU-3637]: https://aziontech.atlassian.net/browse/EDU-3637?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-3637] fix: removed special characters from anchors

- src/content/docs/pt-br/pages/menu-principal/recursos-adicionais/migrar-para-a-azion/migrar-para-a-azion.mdx
- Translated Migrate to Azion 
[EDU-2401]: https://aziontech.atlassian.net/browse/EDU-2401?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-2401] feat: add migrate to azion PT

- src/content/docs/en/pages/main-menu/additional-resources/migrate-to-azion/migrate-to-azion.mdx
- src/content/docs/en/pages/main-menu/reference/build/edge-application/edge-caching.mdx
- src/content/docs/pt-br/pages/menu-principal/recursos-adicionais/migrar-para-a-azion/migrar-para-a-azion.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/build/edge-application/edge-caching.mdx
- Add button import
- Add cache key note
> [NO-ISSUE] fix: import and cache keys

- src/content/docs/en/pages/secure-journey/transport-layer-security/mtls.mdx
- src/content/docs/pt-br/pages/secure-jornada/transport-layer-security/mtls.mdx
- Added PT version
- Modified some formatting things in EN
[EDU-3149]: https://aziontech.atlassian.net/browse/EDU-3149?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-3149] feat: add mtls pt guide

- src/content/docs/pt-br/pages/secure-jornada/advanced-configurations/integrar-siems.mdx
* Added new page on integrate SIEMs in PT.
[EDU-3175]: https://aziontech.atlassian.net/browse/EDU-3175?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-3175] feat: add integrate siems pt

- src/content/docs/en/pages/guides/marketplace/templates/static-template/static-template.mdx
[EDU-2219] 
- Adding guides on how to use the Suite Static Cache template
- 
n/a.
[EDU-2219]: https://aziontech.atlassian.net/browse/EDU-2219?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-2219] feat: Suite Static Cache template guide

- src/content/docs/en/pages/guides/marketplace/templates/by-pass-template/by-pass-template.mdx
[EDU-3453] 
- Adding new guides on how to use the Suite By Pass template.
n/a.
[EDU-3453]: https://aziontech.atlassian.net/browse/EDU-3453?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-3453] feat: Suite Bypass template guide

- src/content/docs/en/pages/guides/marketplace/templates/image-cache/image-cache.mdx
[EDU-3450]
- Adding guides on how to use the Suite Image Cache template
n/a.
[EDU-3450]: https://aziontech.atlassian.net/browse/EDU-3450?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-3450] feat: Suite Image Cache template

- src/content/docs/en/pages/main-menu/reference/build/edge-application/domains/mtls.mdx
- src/content/docs/en/pages/main-menu/reference/build/edge-application/edge-application.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/build/edge-application/domains/mtls.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/build/edge-application/edge-application.mdx
> [NO-ISSUE] feat: add-limits

- src/content/docs/pt-br/pages/menu-principal/referencia/observe/siem/siem.mdx
* SIEM Azion page.
[EDU-3597]: https://aziontech.atlassian.net/browse/EDU-3597?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-3597] feat: add siem azion

- src/content/docs/en/pages/main-menu/reference/marketplace/bot-protection-reference.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/marketplace/bot-protection-referencia.mdx
[EDU-3627] 
- Adding Bot protection reference.
[EDU-3627]: https://aziontech.atlassian.net/browse/EDU-3627?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-3627] Bot Protection reference

- src/content/docs/en/pages/main-menu/reference/observe/data-streaming/data-streaming.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/observe/data-streaming/data-streaming.mdx
* Added an example to better explain how packets are sent in Data Streaming.
> [NO-ISSUE] feat: dts example

- src/content/docs/en/pages/main-menu/reference/services/integration-services/instructor-led-training.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/servicos/instructor-led-training.mdx
- Modify custom ed program files
[EDU-3686]: https://aziontech.atlassian.net/browse/EDU-3686?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-3686] refactor: change custom ed programs to instructor-led

- src/content/docs/en/pages/secure-journey/advanced-configurations/block-tor-networks.mdx
* Added new page on How to block Tor exit node IP addresses.
[EDU-3145]: https://aziontech.atlassian.net/browse/EDU-3145?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-3145] feat: add block tor list

- src/content/docs/en/pages/main-menu/reference/services/integration-services/managed-configurations.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/servicos/managed-configurations.mdx
- Add PT and EN version of managed config service
[EDU-3657]: https://aziontech.atlassian.net/browse/EDU-3657?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-3657] feat: add managed config

- src/content/docs/en/pages/main-menu/reference/secure/intelligent-dns/intelligent-dns.mdx
- src/content/docs/en/pages/secure-journey/intelligent-dns/test-zone.mdx
* Added new page on testing zones.
* Removed testing zones section from reference page.
[EDU-3190]: https://aziontech.atlassian.net/browse/EDU-3190?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-3190] feat: add test zone

- src/content/docs/en/pages/secure-journey/intelligent-dns/access-root-domain.mdx
* Added new page on How to access addresses through a root domain (ANAME)
[EDU-3184]: https://aziontech.atlassian.net/browse/EDU-3184?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-3184] feat: add access root domain with aname record

- src/content/docs/pt-br/pages/secure-jornada/intelligent-dns/acessar-dominio-raiz.mdx
* New page to use root domain to access IP addresses.
[EDU-3184]: https://aziontech.atlassian.net/browse/EDU-3184?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-3184] feat: add acess root domain pt

- src/content/docs/en/pages/main-menu/reference/build/edge-application/main-settings.mdx
- src/content/docs/en/pages/main-menu/reference/glossary/glossary.mdx
> [NO-ISSUE] fix: vibes

- src/content/docs/en/pages/guides/marketplace/templates/nextjs-static-boilerplate/nextjs-static-boilerplate.mdx
- feat: add new YouTube video
Insertion of the link for the new YouTube video
> [EDU-3560] feat:insert-youtube-video

- src/content/docs/en/pages/observe-journey/data-streaming/set-payload.mdx
* New page on How to set a payload on Data Streaming.
[EDU-3734]: https://aziontech.atlassian.net/browse/EDU-3734?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-3734] feat: add set payload

- src/content/docs/en/pages/observe-journey/data-streaming/advanced-configurations/configure-sampling.mdx
* Added new page on How to configure sampling on Data Streaming.
[EDU-3746]: https://aziontech.atlassian.net/browse/EDU-3746?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-3746] feat: add configure sampling

- src/content/docs/en/pages/observe-journey/select-variables.mdx
* Added new page on How to select variables on Data Streaming.
[EDU-3751]: https://aziontech.atlassian.net/browse/EDU-3751?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-3751] feat: add select variables

- src/content/docs/en/pages/observe-journey/data-streaming/troubleshoot/understand-metrics.mdx
* New page for Understand Data Streaming metrics.
> [EDU-3754] feat: add understand metrics

- src/content/docs/en/pages/guides/grafana/grafana-plugin-custom-dash/index.mdx
- src/content/docs/en/pages/observe-journey/real-time-events/grafana-best-practices.mdx
* Created new page for Grafana best practices.
* Updated guide that previously had best practices.
[EDU-3760]: https://aziontech.atlassian.net/browse/EDU-3760?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-3760] feat: add grafana best practices

- src/content/docs/en/pages/main-menu/reference/observe/real-time-events/real-time-events.mdx
- src/content/docs/en/pages/observe-journey/real-time-events/analyze-logs/add-filters.mdx
* Added new page for Add filters on Real-Time Events.
* Modified Real-Time Events reference to remove filter content.
[EDU-3724]: https://aziontech.atlassian.net/browse/EDU-3724?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-3724] feat: add add filters events

- src/content/docs/en/pages/main-menu/reference/observe/real-time-metrics/real-time-metrics.mdx
- src/content/docs/en/pages/observe-journey/real-time-metrics/monitor-metrics/add-filters.mdx
* Created new page for Add filter on Real-Time Metrics.
* Updated content on the reference documentation to link to new guide.
[EDU-3737]: https://aziontech.atlassian.net/browse/EDU-3737?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-3757] feat: add filters real-time metrics

- src/content/docs/en/pages/observe-journey/data-streaming/integrations/standard-http-https-post.mdx
* Added new guide on How to use a HTTP/HTTPS POST connector to receive data from Data Streaming.
[EDU-3741]: https://aziontech.atlassian.net/browse/EDU-3741?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-3741] feat: add http/https guide

- src/content/docs/en/pages/observe-journey/understand-logs.mdx
* Added new page on How to understand Real-Time Events logs.
[EDU-3721]: https://aziontech.atlassian.net/browse/EDU-3721?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-3721] feat: add understand logs real-time events

- src/content/docs/en/pages/guides/real-time-metrics/use-metrics/use-real-time-metrics.mdx
- src/content/docs/en/pages/observe-journey/real-time-metrics/monitor-metrics/analyze-metrics.mdx
* New page for analyze metrics guide.
* Updated Real-Time Metrics general usage guide to link to new one.
[EDU-3787]: https://aziontech.atlassian.net/browse/EDU-3787?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-3787] feat: add analyze metrics

- src/content/docs/en/pages/observe-journey/stream-data.mdx
* Added page for Stream data.
[EDU-3772]: https://aziontech.atlassian.net/browse/EDU-3772?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-3772] feat: add stream data

- src/content/docs/en/pages/observe-journey/real-time-events/analyze-logs/analyze-navigation-data.mdx
* Added new page on How to analyze navigation data from Edge Pulse.
[EDU-3792]: https://aziontech.atlassian.net/browse/EDU-3792?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-3792] feat: add navigate data

- src/content/docs/en/pages/observe-journey/monitor-applications.mdx
- src/content/docs/en/pages/observe-journey/stream-data.mdx
* Added new page for Monitor applications.
[EDU-3775]: https://aziontech.atlassian.net/browse/EDU-3775?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-3775] feat: add monitor applications

- src/content/docs/en/pages/observe-journey/analyze-logs.mdx
* Added initial page for Analyze logs.
[EDU-3777]: https://aziontech.atlassian.net/browse/EDU-3777?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-3777] feat: add analyze logs

- src/content/docs/pt-br/pages/guias/real-time-metrics/usar-real-time-metrics/index.mdx
- src/content/docs/pt-br/pages/observe-jornada/real-time-metrics/monitor-metrics/analyze-metrics.mdx
[EDU-3787] 
- New page for analyze metrics guide.
- Updated Real-Time Metrics general usage guide to link to new one.
https://github.com/aziontech/docs/pull/588
[EDU-3787]: https://aziontech.atlassian.net/browse/EDU-3787?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-3787] feat: add analyze metrics (PT version)

- src/content/docs/pt-br/pages/guias/grafana/grafana-plugin-personalizar-dash/index.mdx
- src/content/docs/pt-br/pages/observe-jornada/real-time-events/grafana-boas-praticas.mdx
[EDU-3760]
- Created new page for Grafana best practices.
- Updated guide that previously had best practices.
https://github.com/aziontech/docs/pull/584
[EDU-3760]: https://aziontech.atlassian.net/browse/EDU-3760?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-3760] feat: add grafana best practices (PT version)

- src/content/docs/pt-br/pages/observe-jornada/stream-data.mdx
[EDU-3772]
Added page for Stream data.
https://github.com/aziontech/docs/pull/590
[EDU-3772]: https://aziontech.atlassian.net/browse/EDU-3772?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-3772] feat: add stream data (PT version)

- src/content/docs/en/pages/observe-journey/overview.mdx
* Add Observe Overview 🎉 
[EDU-3089]: https://aziontech.atlassian.net/browse/EDU-3089?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-3089] feat: add observe overview

- src/content/docs/en/pages/observe-journey/real-time-events/integrations/grafana-plugin-custom-table.mdx
* Guide to customize a dashboard with tables.
IMPORTANT: this is basically the same guide as the one published in https://www.azion.com/en/documentation/products/guides/azion-plugin-grafana-custom-dash/, except for the part that mentions using the Table visualization. I'll find ways to improve it later on, but as it's already published, I won't change other parts of the content.
[EDU-3730]: https://aziontech.atlassian.net/browse/EDU-3730?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-3730] feat: add customize table grafana

- src/content/docs/pt-br/pages/observe-jornada/real-time-events/analise-logs/analise-dados-navegacao.mdx
* Página de coletar dados de navegação com o Edge Pulse.
[EDU-3792]: https://aziontech.atlassian.net/browse/EDU-3792?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-3792] feat: add dados navegação

- src/content/docs/pt-br/pages/observe-jornada/real-time-events/analise-logs.mdx
* Nova página de Analise logs.
[EDU-3777]: https://aziontech.atlassian.net/browse/EDU-3777?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-3777] feat: add analize logs

- src/content/docs/pt-br/pages/observe-jornada/monitore-aplicacoes.mdx
* Added page for Monitore aplicacoes.
[EDU-3775]: https://aziontech.atlassian.net/browse/EDU-3775?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-3775] feat: add monitore aplicacoes

- src/content/docs/pt-br/pages/menu-principal/referencia/observe/real-time-metrics/real-time-metrics.mdx
- src/content/docs/pt-br/pages/observe-jornada/real-time-metrics/adicionar-filtros.mdx
* Added guide for Add filter Real-Time Metrics.
Note: it was already published on the reference page. Just moved the text to a new one.
[EDU-3757]: https://aziontech.atlassian.net/browse/EDU-3757?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-3757] feat: add filtros metrics

- src/content/docs/pt-br/pages/observe-jornada/data-streaming/troubleshoot/understand-metrics.mdx
[EDU-3754]
New page for Understand Data Streaming metrics.
https://github.com/aziontech/docs/pull/582
[EDU-3754]: https://aziontech.atlassian.net/browse/EDU-3754?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-3754] feat: add understand metrics (PT version)

- src/content/docs/pt-br/pages/observe-jornada/data-streaming/configuracoes-avancadas/selecionar-variaveis.mdx
[EDU-3751]: https://aziontech.atlassian.net/browse/EDU-3751?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-3751] feat: add choose variables pt

- src/content/docs/pt-br/pages/observe-jornada/data-streaming/configure-sampling.mdx
[EDU-3746]: https://aziontech.atlassian.net/browse/EDU-3746?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-3746] feat: add configure sampling pt

- src/content/docs/pt-br/pages/observe-jornada/real-time-events/analise-logs/entenda-logs.mdx
> [EDU-3721] feat: add understand logs rte

- src/content/docs/pt-br/pages/observe-jornada/data-streaming/integracoes/conector-standard-http-https-post.mdx
[EDU-3741]: https://aziontech.atlassian.net/browse/EDU-3741?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-3741] feat: add standard https conector

- src/content/docs/en/pages/main-menu/reference/marketplace/bot-protection-reference.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/marketplace/bot-protection-referencia.mdx
[No-issue]
- Fix Delayed Response section.
- Add 2 new actions and Metrics feature.
n/a.
> [No-issue] Update bot reference

- src/content/docs/en/pages/main-menu/reference/observe/real-time-metrics/real-time-metrics.mdx
- src/content/docs/pt-br/pages/devtools/api-graphql/recursos/events-campos/events-campos.mdx
- src/content/docs/pt-br/pages/devtools/api-graphql/recursos/recursos-gql.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/observe/real-time-metrics/real-time-metrics.mdx
* Added information regarding maximum aggregation time for Real-Time Metrics.
> [NO-ISSUE] feat: add metrics aggregation time

- src/content/docs/en/pages/main-menu/release-notes/release-notes.mdx
- src/content/docs/pt-br/pages/menu-principal/release-notes/release-notes.mdx
[EDU-3698]
- add new entry Release notes
n/a.
[EDU-3698]: https://aziontech.atlassian.net/browse/EDU-3698?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-3698] feat: add new entry Release notes

- src/content/docs/en/pages/guides/marketplace/integrations/fingerprint/fingerprint.mdx
- src/content/docs/pt-br/pages/guias/marketplace/integrations/fingerprint/fingerprint.mdx
Removendo informações de configuração a pedido de Rafael Garbinatto [https://aziontech.atlassian.net/browse/EDU-3827]
https://aziontech.atlassian.net/browse/EDU-3827
Removed sensitive data about fields composing fingerprint due to possible reverse engineering.
> [EDU-3827] fix: remove sensitive data

- src/content/docs/en/pages/guides/marketplace/integrations/send-event-endpoint/index.mdx
- src/content/docs/pt-br/pages/guias/marketplace/integrations/send-event-endpoint/index.mdx
- Changed json prop from `connection_args` to `http_connection_args`
https://aziontech.slack.com/archives/C05DRB16170/p1704365140994139
> [NO-ISSUE] fix: prop in json to http_connection_args in mktp send event

- src/content/docs/en/pages/guides/edge-application/ea-cors/check-cors-permissions/index.mdx
- src/content/docs/en/pages/guides/edge-application/ea-enable-gzip/index.mdx
- src/content/docs/pt-br/pages/guias/acessar-rtm/acessar-rtm.mdx
- src/content/docs/pt-br/pages/guias/debug-regras/index.mdx
- src/content/docs/pt-br/pages/guias/edge-application/ea-advanced-cache-key/index.mdx
- src/content/docs/pt-br/pages/guias/edge-application/ea-cache-policies/index.mdx
- src/content/docs/pt-br/pages/guias/edge-application/ea-cors/check-cors-permissions/index.mdx
- src/content/docs/pt-br/pages/guias/edge-application/ea-enable-gzip/index.mdx
- src/content/docs/pt-br/pages/guias/edge-application/ea-mitigate-httpoxy/index.mdx
- src/content/docs/pt-br/pages/guias/edge-application/ea-request-lets-encrypt-certificates/index.mdx
- src/content/docs/pt-br/pages/guias/edge-application/ea-rules-engine/index.mdx
- src/content/docs/pt-br/pages/guias/edge-application/ea-test-locally/index.mdx
- src/content/docs/pt-br/pages/guias/how-to-azure-saml/index.mdx
- src/content/docs/pt-br/pages/guias/how-to-google-saml/index.mdx
- src/content/docs/pt-br/pages/guias/open-ticket/index.mdx
- src/content/docs/pt-br/pages/guias/serverless-functions/index.mdx
- Modified H2 for build/platform guides
[EDU-3609]: https://aziontech.atlassian.net/browse/EDU-3609?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-3609] refactor: ajustar títulos guias imperativo

- src/content/docs/pt-br/pages/menu-principal/referencia/secure/intelligent-dns/intelligent-dns.mdx
* Removed complete test zone section from Intelligent DNS reference.
* Added button suggesting reading the Test Zone guide.
> [NO-ISSUE] refactor: remove test zone section and add button

- src/content/docs/pt-br/pages/guias/intelligent-dns/run-dig-command.mdx
Related issue:
[EDU-3882](https://aziontech.atlassian.net/browse/EDU-3882?) Fix broken youtube link PT doc DIG Command
Changes:
Update link to youtube video on PT doc DIG Command
[EDU-3882]: https://aziontech.atlassian.net/browse/EDU-3882?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-3882] fix: youtube link DIG Command

- src/content/docs/en/pages/guides/index.mdx
- src/content/docs/en/pages/guides/marketplace/integrations/waiting-room.mdx
- src/content/docs/pt-br/pages/guias/guides.mdx
- src/content/docs/pt-br/pages/guias/marketplace/integrations/waiting-room.mdx
[EDU-3708] 
- Add a how-to guide for Waiting Room integration (EN&PT)
- Add links to the guide on the Guides Page.
n/a.
[EDU-3708]: https://aziontech.atlassian.net/browse/EDU-3708?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-3708] feat: add guide Waiting Room

- src/content/docs/en/pages/deploy-journey/deploy-service.mdx
[EDU-3849](https://aziontech.atlassian.net/browse/EDU-3849)
[EDU-3849]: https://aziontech.atlassian.net/browse/EDU-3849?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> EDU-3849 add deploy a service

- src/content/docs/pt-br/pages/menu-principal/referencia/observe/data-streaming/primeiros-passos.mdx
* Changed H1 to avoid confusion with the reference doc.
> [NO-ISSUE] refactor: change h1

- src/content/docs/en/pages/deploy-journey/install-orch-agent/install-orch-agent.mdx
[EDU-3850](https://aziontech.atlassian.net/browse/EDU-3850)
[EDU-3850]: https://aziontech.atlassian.net/browse/EDU-3850?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> EDU-3850 add instal orch agent

- src/content/docs/en/pages/deploy-journey/bind-service/bind-service.mdx
- src/content/docs/en/pages/deploy-journey/install-orch-agent/install-orch-agent.mdx
Related issue:
[EDU-3853](https://aziontech.atlassian.net/browse/EDU-3853)
[EDU-3853]: https://aziontech.atlassian.net/browse/EDU-3853?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-3853] bind service and node

- src/content/docs/en/pages/deploy-journey/authorize-node/authorize-node.mdx
Related issue:
[EDU-3851](https://aziontech.atlassian.net/browse/EDU-3851)
[EDU-3851]: https://aziontech.atlassian.net/browse/EDU-3851?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-3851] auth edge node

- src/content/docs/en/pages/deploy-journey/create-service/create-service.mdx
Related issue:
[EDU-3901](https://aziontech.atlassian.net/browse/EDU-3901)
[EDU-3901]: https://aziontech.atlassian.net/browse/EDU-3901?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-3901]  create service

- src/content/docs/en/pages/deploy-journey/provision-files/provision-file.mdx
Related issue:
[EDU-3857](https://aziontech.atlassian.net/browse/EDU-3857)
[EDU-3857]: https://aziontech.atlassian.net/browse/EDU-3857?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-3857] provision files  - resources

- src/content/docs/en/pages/deploy-journey/work-with-variables/work-with-variables.mdx
Related issue:
[EDU-3855](https://aziontech.atlassian.net/browse/EDU-3855)
[EDU-3855]: https://aziontech.atlassian.net/browse/EDU-3855?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-3855] work with node services variables

- src/content/docs/en/pages/deploy-journey/unbind-service/unbind-service.mdx
Related issue:
[EDU-3856](https://aziontech.atlassian.net/browse/EDU-3856)
[EDU-3856]: https://aziontech.atlassian.net/browse/EDU-3856?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-3856] unbind a service

- src/content/docs/en/pages/deploy-journey/configure-node/watch-logs/watch-logs.mdx
Related issue:
[EDU-3852](https://aziontech.atlassian.net/browse/EDU-3852)
[EDU-3852]: https://aziontech.atlassian.net/browse/EDU-3852?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-3852] watch orch logs 

- src/content/docs/en/pages/secure-journey/intelligent-dns-advanced-configurations/activate-dnssec.mdx
- src/content/docs/en/pages/secure-journey/intelligent-dns-advanced-configurations/load-balance-dns.mdx
* Fixed title of the Activate DNSSEC guide.
* Added new page on how to perform a DNS load balance.
[EDU-3187]: https://aziontech.atlassian.net/browse/EDU-3187?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-3187] feat: add load balance a dns

- src/content/docs/en/pages/deploy-journey/advanced-config/explore-agent-commands.mdx
- src/content/docs/en/pages/deploy-journey/advanced-config/run-scripts/run-scripts.mdx
- src/content/docs/en/pages/deploy-journey/configure-node/bind-service/bind-service.mdx
Related issue:
[EDU-3860](https://aziontech.atlassian.net/browse/EDU-3860)
[EDU-3860]: https://aziontech.atlassian.net/browse/EDU-3860?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-3860] deploy - run scripts

- src/content/docs/en/pages/deploy-journey/configure-node/generate-credential/generate-credentials.mdx
Related issue:
[EDU-3919](https://aziontech.atlassian.net/browse/EDU-3919)
[EDU-3919]: https://aziontech.atlassian.net/browse/EDU-3919?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-3919] generate credentials

- src/content/docs/en/pages/deploy-journey/advanced-config/explore-usage/explore-usage.mdx
Related issue
[EDU-3869](https://aziontech.atlassian.net/browse/EDU-3869)
[EDU-3869]: https://aziontech.atlassian.net/browse/EDU-3869?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> EDU-3858 explore-usage

- src/content/docs/en/pages/deploy-journey/automate/api/automate-api.mdx
Related issue
[EDU-3864](https://aziontech.atlassian.net/browse/EDU-3864)
[EDU-3864]: https://aziontech.atlassian.net/browse/EDU-3864?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> EDU-3864 automate with api

- src/content/docs/en/pages/deploy-journey/automate/zero-touch-provisioning/zero-touch-provisioning.mdx
Related issues: 
https://aziontech.atlassian.net/browse/EDU-3865
https://aziontech.atlassian.net/browse/EDU-3866
https://aziontech.atlassian.net/browse/EDU-3867
> EDU-3865 -  EDU-3866, EDU-3867,  Zero touch provisioning

- src/content/docs/en/pages/deploy-journey/advanced-config/uninstall/uninstall-node.mdx
Related issue
[EDU-3863](https://aziontech.atlassian.net/browse/EDU-3863)
[EDU-3863]: https://aziontech.atlassian.net/browse/EDU-3863?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-3863] uninstall edge node

- src/content/docs/en/pages/secure-journey/edit-edge-firewall/instantiate-edge-functions.mdx
- src/content/docs/pt-br/pages/secure-jornada/editar-edge-firewall/instanciar-edge-functions.mdx
* Formatted an example with beautify format :)
> [NO-ISSUE] refactor: beautify example

- src/content/docs/pt-br/pages/deploy-jornada/deploy-service.mdx
[EDU-3849]
add deploy a service PT
n/a.
[EDU-3849]: https://aziontech.atlassian.net/browse/EDU-3849?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-3849] feat: add deploy a service PT

- src/content/docs/pt-br/pages/deploy-jornada/watch-logs.mdx
[EDU-3852]
add watch logs PT 
n/a.
[EDU-3852]: https://aziontech.atlassian.net/browse/EDU-3852?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-3852] feat: add watch logs PT 

- src/content/docs/pt-br/pages/deploy-jornada/overview/unbind-service.mdx
[EDU-3856]
Add unbind a service PT
n/a.
[EDU-3856]: https://aziontech.atlassian.net/browse/EDU-3856?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-3856] feat: add unbind a service PT

- src/content/docs/en/pages/main-menu/reference/build/edge-application/edge-application.mdx
* Added Billing section to Edge Application reference.
* Added info on Requests metric.
[EDU-3924]: https://aziontech.atlassian.net/browse/EDU-3924?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-3924] feat: metrics requests edge app

- src/content/docs/pt-br/pages/deploy-jornada/vincular-service/vincular-service.mdx
Related issue:
[EDU-3853](https://aziontech.atlassian.net/browse/EDU-3853)
[EDU-3853]: https://aziontech.atlassian.net/browse/EDU-3853?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-3853] bind service pt

- src/content/docs/pt-br/pages/deploy-jornada/trabalhar-variaveis/trabalhar-com-variaveis.mdx
Related issue:
[EDU-3855](https://aziontech.atlassian.net/browse/EDU-3855)
[EDU-3855]: https://aziontech.atlassian.net/browse/EDU-3855?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-3855] work with node services variables pt

- src/content/docs/pt-br/pages/deploy-jornada/provisionar-arquivos/provisionar-arquivos.mdx
- src/content/docs/pt-br/pages/deploy-jornada/trabalhar-variaveis/trabalhar-com-variaveis.mdx
Related issue: [EDU-3857](https://aziontech.atlassian.net/browse/EDU-3857)
[EDU-3857]: https://aziontech.atlassian.net/browse/EDU-3857?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-3857] provision files resources pt

- src/content/docs/pt-br/pages/deploy-jornada/gerar-credenciais/gerar-credenciais.mdx
Related issue: [EDU-3919](https://aziontech.atlassian.net/browse/EDU-3919)
[EDU-3919]: https://aziontech.atlassian.net/browse/EDU-3919?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-3919] generate credentials pt

- src/content/docs/pt-br/pages/deploy-jornada/autorizar-node/autorizar-node.mdx
- src/content/docs/pt-br/pages/deploy-jornada/explorar-uso/explorar-uso.mdx
- src/content/docs/pt-br/pages/deploy-jornada/logs/watch-logs.mdx
Related issue: [EDU-3858](https://aziontech.atlassian.net/browse/EDU-3858)
[EDU-3858]: https://aziontech.atlassian.net/browse/EDU-3858?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-3858] explore usage pt

- src/content/docs/pt-br/pages/deploy-jornada/automate-api/automate-api.mdx
Related issue: [EDU-3864](https://aziontech.atlassian.net/browse/EDU-3864)
[EDU-3864]: https://aziontech.atlassian.net/browse/EDU-3864?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-3864] automate api-pt

- src/content/docs/pt-br/pages/deploy-jornada/desinstalar-node/desinstalar-node.mdx
Related issue: [EDU-3863](https://aziontech.atlassian.net/browse/EDU-3863)
[EDU-3863]: https://aziontech.atlassian.net/browse/EDU-3863?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-3863] uninstall edge node pt

- src/content/docs/pt-br/pages/deploy-jornada/rodar-scripts/rodar-scripts.mdx
Related issue: [EDU-3860](https://aziontech.atlassian.net/browse/EDU-3860)
[EDU-3860]: https://aziontech.atlassian.net/browse/EDU-3860?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-3860] run scripts pt

- src/content/docs/en/homes/secure-home.mdx
- src/content/docs/pt-br/homes/secure-home.mdx
* Updated home descriptions to match rules.
> [NO-ISSUE] update description secure home

- src/content/docs/pt-br/pages/deploy-jornada/zero-touch-provisioning/zero-touch-provisioning.mdx
Related issues: 
[EDU-3865](https://aziontech.atlassian.net/browse/EDU-3865)
[EDU-3866](https://aziontech.atlassian.net/browse/EDU-3866)
[EDU-3867](https://aziontech.atlassian.net/browse/EDU-3867)
[EDU-3865]: https://aziontech.atlassian.net/browse/EDU-3865?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[EDU-3866]: https://aziontech.atlassian.net/browse/EDU-3866?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[EDU-3867]: https://aziontech.atlassian.net/browse/EDU-3867?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-3865] EDU-3866 EDU-3867 - Zero touch provisioning pt

- src/content/docs/en/pages/main-menu/reference/observe/data-streaming/data-streaming.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/observe/data-streaming/data-streaming.mdx
* Added Limits section to Data Streaming reference in EN and PT.
[EDU-3970]: https://aziontech.atlassian.net/browse/EDU-3970?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-3970] feat: add limits data streaming

- src/content/docs/en/pages/main-menu/reference/secure/edge-firewall/ddos-protection/ddos-protection.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/secure/edge-firewall/ddos-protection.mdx
* Added Limits to DDoS Protection reference in EN and PT.
[EDU-3985]: https://aziontech.atlassian.net/browse/EDU-3985?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-3985] feat: add ddos limit

- src/content/docs/en/pages/main-menu/reference/observe/real-time-metrics/real-time-metrics.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/observe/real-time-metrics/real-time-metrics.mdx
* Added Limits to Real-Time Metrics reference in EN and PT.
[EDU-3976]: https://aziontech.atlassian.net/browse/EDU-3976?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-3976] feat: add limits real time metrics

- src/content/docs/en/pages/main-menu/reference/build/edge-application/edge-functions.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/build/edge-application/edge-functions-edge-app.mdx
Related issue: [EDU-3958](https://aziontech.atlassian.net/browse/EDU-3958)
Changes
Added Limits to Edge Functions reference in EN and PT.
[EDU-3958]: https://aziontech.atlassian.net/browse/EDU-3958?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-3958] limits edge functions

- src/content/docs/en/pages/main-menu/reference/secure/edge-firewall/web-application-firewall/web-application-firewall.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/secure/edge-firewall/web-application-firewall.mdx
* Added Limits section to WAF reference in EN and PT.
[EDU-3991]: https://aziontech.atlassian.net/browse/EDU-3991?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-3991] feat: add waf limits

- src/content/docs/en/pages/main-menu/reference/secure/edge-firewall/edge-firewall.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/secure/edge-firewall/edge-firewall.mdx
* Added Limits section to Edge Firewall reference in EN and PT.
[EDU-3988]: https://aziontech.atlassian.net/browse/EDU-3988?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-3988] feat: add edge firewall limits

- src/content/docs/en/pages/main-menu/reference/observe/data-streaming/data-streaming.mdx
* Added Billing section to Data Streaming.
* Added Data Streaming metrics: Data Streamed and Requests.
[EDU-3925]: https://aziontech.atlassian.net/browse/EDU-3925?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[EDU-4025]: https://aziontech.atlassian.net/browse/EDU-4025?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-3925] [EDU-4025] feat: metrics data streaming

- src/content/docs/en/pages/main-menu/reference/build/edge-application/cache-settings.mdx
- src/content/docs/en/pages/main-menu/reference/build/edge-application/edge-caching.mdx
- src/content/docs/en/pages/main-menu/work-with-domains/point-domain.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/build/edge-application/cache-settings.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/build/edge-application/edge-caching.mdx
- Transfer reference material to edge caching
- Fix button
> [NO-ISSUE] refactor: cache settings + edge caching

- src/content/docs/en/pages/main-menu/reference/secure/intelligent-dns/intelligent-dns.mdx
* Added Billing section to Intelligent DNS reference.
* Added Hosted Zones and Standard Queries metrics.
[EDU-3937]: https://aziontech.atlassian.net/browse/EDU-3937?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[EDU-3938]: https://aziontech.atlassian.net/browse/EDU-3938?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-3937] [EDU-3938] feat: metrics intelligent dns

- src/content/docs/en/pages/main-menu/reference/build/edge-application/domains/domains.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/build/edge-application/domains/domains.mdx
- Add cname limit
[EDU-3952]: https://aziontech.atlassian.net/browse/EDU-3952?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-3952] feat: cname limit

- src/content/docs/en/pages/main-menu/reference/build/edge-application/domains/domains.mdx
- src/content/docs/en/pages/main-menu/reference/build/edge-application/real-time-purge.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/build/edge-application/domains/domains.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/build/edge-application/real-time-purge.mdx
- Add limits to real-time purge
[EDU-3964]: https://aziontech.atlassian.net/browse/EDU-3964?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-3964] feat: add real-time purge limits

- src/content/docs/en/pages/main-menu/reference/build/edge-application/edge-caching.mdx
- src/content/docs/en/pages/main-menu/reference/build/edge-application/rules-engine.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/build/edge-application/edge-caching.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/build/edge-application/rules-engine-edge-app.mdx
- Added limits section
[EDU-3955]: https://aziontech.atlassian.net/browse/EDU-3955?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-3955] feat: add limits to edge caching & rules engine

- src/content/docs/en/pages/main-menu/reference/services/support/technical-support.mdx
* Added Billing section to Technical Support reference.
[EDU-4024]: https://aziontech.atlassian.net/browse/EDU-4024?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-4024] feat: metrics support plan

- src/content/docs/en/pages/main-menu/reference/build/edge-application/edge-application.mdx
- src/content/docs/en/pages/main-menu/reference/build/edge-application/edge-caching.mdx
- src/content/docs/en/pages/main-menu/reference/build/edge-application/rules-engine.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/build/edge-application/edge-application.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/build/edge-application/edge-caching.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/build/edge-application/rules-engine-edge-app.mdx
- Adjusted rules engine limit
- Added object size limit
[EDU-3982]: https://aziontech.atlassian.net/browse/EDU-3982?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-3982] add objects in cache limit

- src/content/docs/en/pages/main-menu/reference/build/edge-application/edge-functions.mdx
- src/content/docs/en/pages/main-menu/reference/secure/edge-firewall/edge-functions-for-edge-firewall/edge-functions-firewall.mdx
* Added Edge Functions Billing metrics in both Edge Functions references.
[EDU-3928]: https://aziontech.atlassian.net/browse/EDU-3928?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[EDU-3930]: https://aziontech.atlassian.net/browse/EDU-3930?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-3928] [EDU-3930] feat: metrics edge functions

- src/content/docs/en/pages/main-menu/reference/secure/edge-firewall/network-layer-protection/network-layer-protection.mdx
* Added Billing section to Network Layer Protection reference.
[EDU-4022]: https://aziontech.atlassian.net/browse/EDU-4022?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-4022] feat: add metrics network layer protection

- src/content/docs/en/pages/main-menu/reference/build/edge-application/rules-engine.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/build/edge-application/rules-engine-edge-app.mdx
- Added example columns to rules engine variables
- Added missing examples
- Fixed wording in some descriptions and sections
- Removed unnecessary table spaces
- Replaced old blockquote with tip component
[EDU-3904]: https://aziontech.atlassian.net/browse/EDU-3904?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-3904] add examples to variables in rules engine

- src/content/docs/en/pages/guides/marketplace/integrations/hcaptcha.mdx
- src/content/docs/pt-br/pages/guias/marketplace/integrations/hcaptcha.mdx
[EDU-3717]
- refining adding trademark - hCaptcha (EN-PT)
n/a.
[EDU-3717]: https://aziontech.atlassian.net/browse/EDU-3717?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-3717] refactor: refining trademark - hCaptcha (EN-PT)

- src/content/docs/en/pages/main-menu/reference/secure/edge-firewall/web-application-firewall/web-application-firewall.mdx
* Added Billing section to WAF reference.
[EDU-4023]: https://aziontech.atlassian.net/browse/EDU-4023?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-4023] feat: metrics waf

- src/content/docs/en/pages/main-menu/reference/build/edge-application/image-processor.mdx
- src/content/docs/en/pages/main-menu/reference/secure/edge-firewall/edge-functions-for-edge-firewall/edge-functions-firewall.mdx
* Added Billing section to Image Processor reference.
[EDU-3934]: https://aziontech.atlassian.net/browse/EDU-3934?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-3934] feat: metrics images processed

- src/content/docs/pt-br/pages/secure-jornada/transport-layer-security/ciphers.mdx
> [NO-ISSUE] fix: broken link

- src/content/docs/en/pages/guides/object-storage/bucket-actions/index.mdx
- src/content/docs/en/pages/main-menu/reference/store/object-storage/index.mdx
- src/content/docs/pt-br/pages/guias/object-storage/bucket-actions/index.mdx
- src/content/docs/pt-br/pages/guias/object-storage/create-object-storage/index.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/store/object-storage/index.mdx
> [NO-ISSUE] fix: adjustments to object storage

- src/content/docs/en/pages/main-menu/reference/store/object-storage/index.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/store/object-storage/index.mdx
> [NO-ISSUE] fix: update limits

- src/content/docs/en/pages/guides/index.mdx
- src/content/docs/en/pages/guides/object-storage/bucket-actions/index.mdx
- src/content/docs/en/pages/guides/object-storage/use-bucket-as-origin/index.mdx
- src/content/docs/en/pages/main-menu/reference/store/object-storage/index.mdx
- src/content/docs/pt-br/pages/guias/guides.mdx
- src/content/docs/pt-br/pages/guias/object-storage/bucket-actions/index.mdx
- src/content/docs/pt-br/pages/guias/object-storage/use-bucket-as-origin/index.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/store/object-storage/index.mdx
- Added new guide to use object as bucket
- Added ref links
- Made small addendum to download objects from bucket guide
[EDU-3832]: https://aziontech.atlassian.net/browse/EDU-3832?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-3832] feat: add use bucket as origin guide

- src/content/docs/en/pages/main-menu/release-notes/release-notes.mdx
- src/content/docs/pt-br/pages/menu-principal/release-notes/release-notes.mdx
- added release note for object storage
> [NO-ISSUE] feat: update release notes for object storage

- src/content/docs/en/pages/guides/marketplace/integrations/request-data-into-header.mdx
- src/content/docs/pt-br/pages/guias/marketplace/integrations/request-data-headers.mdx
[No-ISSUE]
Fix: namespace Request Data guide.
n/a.
> [NO-ISSUE] fix: namespace request data guide

- src/content/docs/en/pages/main-menu/release-notes/release-notes.mdx
- src/content/docs/pt-br/pages/menu-principal/release-notes/release-notes.mdx
> [NO-ISSUE] feat: add note preview stage

- src/content/docs/pt-br/pages/devtools/azion-edge-runtime/compatibilidade/node.mdx
Related issue:
[EDU-3210](https://aziontech.atlassian.net/browse/EDU-3210)
Changes:
Add a table for polyfills.
Revamp built-in info.
[EDU-3210]: https://aziontech.atlassian.net/browse/EDU-3210?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-3210] add improvements to runtime and node compatibility PT

- src/content/docs/en/pages/devtools/cli/azion-cli-alpha/create/create.mdx
- src/content/docs/pt-br/pages/devtools/cli/azion-cli-alpha/create/create.mdx
[EDU-4095](https://aziontech.atlassian.net/browse/EDU-4095)
Changes: 
- Place all create commands inside a parent file for the create command. Each resource had its own page. Now, the page will be based on the CRUDL command.
- The content was not altered, only moved.
- **I avoided using ### because it was uncomfortable to the eye... nor nice**.
[EDU-4095]: https://aziontech.atlassian.net/browse/EDU-4095?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-4095] cli create command (en + pt)

- src/content/docs/en/pages/devtools/cli/azion-cli-alpha/update/update.mdx
- src/content/docs/pt-br/pages/devtools/cli/azion-cli-alpha/update/update.mdx
Related issue:
[EDU-4098](https://aziontech.atlassian.net/browse/EDU-4098)
Changes:
Place all create commands inside a parent file for the update command. Each resource had its own page. Now, the page will be based on the CRUDL command.
The content was not altered, only moved.
I avoided using ### because it was uncomfortable to the eye... nor nice.
[EDU-4098]: https://aziontech.atlassian.net/browse/EDU-4098?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-4098] add cli update command

- src/content/docs/en/pages/main-menu/release-notes/release-notes.mdx
- src/content/docs/pt-br/pages/guias/devtools/customize-console-ui/index.mdx
- src/content/docs/pt-br/pages/menu-principal/release-notes/release-notes.mdx
- Added changes merged into master from September 6 and 25
[EDU-3661]: https://aziontech.atlassian.net/browse/EDU-3661?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-3661] feat: add september release notes

- src/content/docs/en/pages/devtools/console-kit/console-kit.mdx
- src/content/docs/pt-br/pages/devtools/console-kit/console-kit.mdx
- Added console kit page and installation guide
Menu: #740
[EDU-3943]: https://aziontech.atlassian.net/browse/EDU-3943?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-3943] feat: add console kit reference

- cicd/azion-massive-redirect-en.json
- cicd/azion-massive-redirect-ptbr.json
Related issue: https://aziontech.atlassian.net/browse/EDU-4080
> [EDU-4080] redirects taskforce url

- src/content/docs/en/pages/main-menu/reference/build/edge-application/websocket.mdx
- src/content/docs/pt-br/pages/devtools/api-graphql/recursos/events-campos/events-campos.mdx
- src/content/docs/pt-br/pages/devtools/api-graphql/recursos/metrics-campos/metrics-campos.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/build/edge-application/websocket.mdx
- Fixed websocket activation requirements note
- Fixed typo on GQL API events and metrics fields
[Slack](https://aziontech.slack.com/archives/C05DRB16170/p1707936816237149)
> [NO-ISSUE] fix: websocket and gql api typo

- src/content/docs/en/pages/guides/cli/cli-vulcan-use-polyfills.mdx
https://aziontech.atlassian.net/browse/EDU-4044
- Add a guide on how to use polyfills in an azion project
> [EDU-4044] add polyfills guide

- src/content/docs/en/pages/main-menu/reference/store/object-storage/index.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/store/object-storage/index.mdx
S3 is not yet available to all Azion customers. This removes the limit mention from the reference table.
> [NO-ISSUE] fix: remove s3 limit from edge storage table

- src/content/docs/en/pages/devtools/api-graphql/features/metrics-fields/metrics-fields.mdx
- src/content/docs/pt-br/pages/devtools/api-graphql/recursos/metrics-campos/metrics-campos.mdx
* Added new field `serverProtocol` to Real-Time Metrics GQL fields doc.
[EDU-4010]: https://aziontech.atlassian.net/browse/EDU-4010?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-4010] feat: add serverProtocol field

- src/content/docs/en/pages/main-menu/release-notes/release-notes.mdx
- src/content/docs/pt-br/pages/menu-principal/release-notes/release-notes.mdx
* Added release notes for GraphQL API updates.
[EDU-4071]: https://aziontech.atlassian.net/browse/EDU-4071?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-4071] feat: add graphql release notes

- src/content/docs/pt-br/pages/observe-jornada/real-time-events/analise-logs/analise-dados-navegacao.mdx
* Updated wrong link in a button.
> [NO-ISSUE] refactor: fix button link

- src/content/docs/pt-br/pages/observe-jornada/monitorar-aplicacoes.mdx
- src/content/docs/pt-br/pages/secure-jornada/editar-edge-firewall/instanciar-edge-functions.mdx
> [NO-ISSUE] refactor: fix links

- src/content/docs/en/pages/main-menu/reference/store/object-storage/index.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/store/object-storage/index.mdx
- Modify transaction to operation
- Change class A to class C
[EDU-4170]: https://aziontech.atlassian.net/browse/EDU-4170?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-4170] feat: modify operations name and classes

- src/content/docs/en/pages/devtools/api-graphql/features/events-fields/events-fields.mdx
- src/content/docs/pt-br/pages/devtools/api-graphql/recursos/events-campos/events-campos.mdx
* Added serverProtocol field.
* Removed a non-existing field.
[EDU-4172]: https://aziontech.atlassian.net/browse/EDU-4172?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-4172] refactor: update fields gql events

- src/content/docs/en/pages/main-menu/reference/store/object-storage/index.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/store/object-storage/index.mdx
- Fix bucket names phrasing (wordy)
- Operation charging note fixed
> [NO-ISSUE] fix: modify wording for classes and names

- src/content/docs/en/pages/main-menu/release-notes/release-notes.mdx
- src/content/docs/pt-br/pages/menu-principal/release-notes/release-notes.mdx
[EDU-4175]
- Adding items Release Notes: new template and waiting room.
n/a.
[EDU-4175]: https://aziontech.atlassian.net/browse/EDU-4175?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-4175] feat: adding items Release Notes

- src/content/docs/en/pages/main-menu/reference/store/object-storage/index.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/store/object-storage/index.mdx
- Adds link to teams permissions page
> [NO-ISSUE] feat: permissions link

- src/content/docs/en/pages/guides/intelligent-dns/run-dig-command.mdx
- src/content/docs/pt-br/pages/guias/intelligent-dns/run-dig-command.mdx
* Added create account and create zone CTAs with buttons.
[EDU-3995]: https://aziontech.atlassian.net/browse/EDU-3995?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-3995] feat: add zone and account ctas

- src/content/docs/en/pages/guides/object-storage/create-object-storage/index.mdx
- src/content/docs/en/pages/guides/object-storage/use-bucket-as-origin/index.mdx
- src/content/docs/pt-br/pages/guias/object-storage/create-object-storage/index.mdx
- src/content/docs/pt-br/pages/guias/object-storage/use-bucket-as-origin/index.mdx
- fixes dash for underscore in api example
> [NO-ISSUE] fix: dash for underscore

- src/content/docs/en/pages/secure-journey/firewall-advanced-configurations/manage-bots.mdx
- src/content/docs/pt-br/pages/secure-jornada/firewall-configuracoes-avançadas/gerenciar-bots.mdx
* Updated Bot Manager name.
* Updated steps to integrate with Data Streaming.
[EDU-4195]: https://aziontech.atlassian.net/browse/EDU-4195?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-4195] refactor: update name and integration steps

- src/content/docs/en/pages/guides/index.mdx
- src/content/docs/en/pages/guides/marketplace/templates/bot-basic.mdx
- src/content/docs/pt-br/pages/guias/guides.mdx
- src/content/docs/pt-br/pages/guias/marketplace/templates/bot-basic.mdx
[EDU-4073]
- Add EN and PT guide for new template: bot basic
n/a.
[EDU-4073]: https://aziontech.atlassian.net/browse/EDU-4073?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-4073] feat: add guide - template bot basic

- src/content/docs/en/pages/guides/index.mdx
- src/content/docs/en/pages/guides/marketplace/templates/bot-with-firewall.mdx
- src/content/docs/pt-br/pages/guias/guides.mdx
- src/content/docs/pt-br/pages/guias/marketplace/templates/bot-with-firewall.mdx
[EDU-4130] 
- Add hot to guide EN and PT guide - new template bot with firewall
n/a.
[EDU-4130]: https://aziontech.atlassian.net/browse/EDU-4130?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-4130] feat: add guide - new template bot with firewall

- src/content/docs/en/pages/devtools/cli/azion-cli/commands/globals/globals.mdx
- src/content/docs/pt-br/pages/devtools/cli/azion-cli/comandos/globals/globals.mdx
Related issue: https://aziontech.atlassian.net/browse/EDU-4201
> [EDU-4201] add example to config option

- src/content/docs/en/pages/main-menu/manage-accounts/manage-profile/personal-token.mdx
[EDU-3413]: https://aziontech.atlassian.net/browse/EDU-3413?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: YouTube video link

- src/content/docs/en/pages/main-menu/manage-accounts/manage-profile/personal-token.mdx
Title fix
[EDU-3413]: https://aziontech.atlassian.net/browse/EDU-3413?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: video title

- src/content/docs/en/pages/main-menu/release-notes/release-notes.mdx
- src/content/docs/pt-br/pages/menu-principal/release-notes/release-notes.mdx
[EDU-4210] [EDU-4211] 
- Add item in release notes.
n/a.
[EDU-4210]: https://aziontech.atlassian.net/browse/EDU-4210?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[EDU-4211]: https://aziontech.atlassian.net/browse/EDU-4211?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-4210] [EDU-4211] feat: add item in release notes

- src/content/docs/pt-br/pages/guias/devtools/customizar-console-ui/index.mdx
- src/content/docs/pt-br/pages/guias/devtools/integrar-com-api/index.mdx
- src/content/docs/pt-br/pages/guias/edge-application/ea-test-locally.mdx
- src/content/docs/pt-br/pages/menu-principal/trabalhe-com-dominios/migrar-ns.mdx
- Fix warnings for atenção in pt-br
> [NO-ISSUE] fix: fix en warnings in pt

- src/content/docs/en/pages/observe-journey/data-streaming/edit-streaming/configure-main-settings.mdx
> fix: update youtube link How to configure Data Streaming

- src/content/docs/en/pages/main-menu/reference/secure/edge-firewall/web-application-firewall/web-application-firewall.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/secure/edge-firewall/web-application-firewall.mdx
* Added and improved existing information regarding WAF mode options.
[EDU-3844]: https://aziontech.atlassian.net/browse/EDU-3844?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-3844] feat: add waf mode info

- src/content/docs/en/pages/devtools/cli/azion-cli/commands/unlink/unlink.mdx
- src/content/docs/pt-br/pages/devtools/cli/azion-cli/comandos/unlink/unlink.mdx
Related issue: https://aziontech.atlassian.net/browse/EDU-4103
Changes: 
- Added unlink command en
- Added unlink command pt
> [EDU-4103] add unlink command docs

- src/content/docs/en/pages/main-menu/work-with-domains/configure-domains.mdx
Update Youtube link
[](https://www.azion.com/en/documentation/products/guides/configure-a-domain/)
> fix:Update Youtube link

- src/content/docs/en/pages/guides/data-streaming/associate-domains.mdx
Update YouTube link How to associate domains on Data Streaming
> fix: update youtube link

- src/content/docs/pt-br/pages/guias/data-streaming/associar-dominios.mdx
Update YouTube link Como associar domínios no Data Streaming
> fix: Youtube link

- src/content/docs/en/pages/observe-journey/data-streaming/integrations/connector-aws-kinesis.mdx
Update Youtube link Amazon Kinesis Data Firehose to receive data from Data Streaming
> fix:Youtube link

- src/content/docs/pt-br/pages/menu-principal/referencia/observe/real-time-events/real-time-events.mdx
* Updated data sources and its variables in PT.
* Updated remaining features in PT.
[EDU-4193]: https://aziontech.atlassian.net/browse/EDU-4193?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-4193] refactor: update events datasets variables PT

- src/content/docs/en/pages/devtools/api-graphql/features/events-fields/events-fields.mdx
- src/content/docs/pt-br/pages/devtools/api-graphql/recursos/events-campos/events-campos.mdx
* Added new field uuid to activityHistory dataset.
* Added return info on wafScore and referenceError fields.
[EDU-4182]: https://aziontech.atlassian.net/browse/EDU-4182?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[EDU-4219]: https://aziontech.atlassian.net/browse/EDU-4219?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[EDU-4231]: https://aziontech.atlassian.net/browse/EDU-4231?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-4182] [EDU-4219] [EDU-4231] feat: add field and complementary info GQL

- src/content/docs/en/pages/main-menu/reference/secure/edge-firewall/rules-engine.mdx
Insert Youtube link
https://www.azion.com/en/documentation/products/secure/edge-firewall/rules-engine/
> fix: insert youtube link

- src/content/docs/en/pages/devtools/cli/azion-cli/commands/whoami/whoami.mdx
- src/content/docs/pt-br/pages/devtools/cli/azion-cli/comandos/whoami/whoami.mdx
Related issue: https://aziontech.atlassian.net/browse/EDU-4101
Changes: 
- add whoami command docs
> [EDU-4101] - add whoami command docs

- src/content/docs/en/pages/main-menu/reference/secure/edge-firewall/web-application-firewall/waf-rule-sets.mdx
Update Youtube link
https://www.azion.com/en/documentation/products/secure/edge-firewall/web-application-firewall/rules-set/
> fix: upload youtube link

- src/content/docs/en/pages/devtools/cli/azion-cli/commands/logs/logs.mdx
- src/content/docs/pt-br/pages/devtools/cli/azion-cli/comandos/logs/logs.mdx
Related issue: https://aziontech.atlassian.net/browse/EDU-4102
Changes: 
- Add cli logs command docs
> [EDU-4102] cli logs

- src/content/docs/pt-br/pages/devtools/api-graphql/recursos/recursos-gql.mdx
Fix first paragraph of GraphQL API "Reamostragem" concept.
> fix: reamostra

- src/content/docs/en/pages/build-journey/develop-with-azion/frameworks/framework-overview.mdx
- src/content/docs/pt-br/pages/build-jornada/desenvolva-com-azion/guias-frameworks/framework-overview.mdx
[NO-ISSUE]
- Add links to framework guides - templates via UI
n/a.
> [NO-ISSUE] refactor: add links to framework guides - UI

- src/content/docs/en/pages/guides/index.mdx
- src/content/docs/en/pages/guides/marketplace/templates/astro-blog-template.mdx
- src/content/docs/pt-br/pages/guias/guides.mdx
- src/content/docs/pt-br/pages/guias/marketplace/templates/astro-blog-template.mdx
[EDU-4075]
- Adding how-to guide - Astro blog template
n/a.
[EDU-4075]: https://aziontech.atlassian.net/browse/EDU-4075?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-4075] feat: add guide - Astro blog template

- src/content/docs/en/pages/main-menu/reference/build/edge-application/digital-certificates.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/build/edge-application/digital-certificates.mdx
* Added reference for CRL in Digital Certificates in EN and PT.
[EDU-4186]: https://aziontech.atlassian.net/browse/EDU-4186?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-4186] feat: add CRL digital certificates

- src/content/docs/en/pages/main-menu/release-notes/release-notes.mdx
- src/content/docs/pt-br/pages/menu-principal/release-notes/release-notes.mdx
[EDU-4266]
- Add item in Release Notes - Astro Blog Starter Kit launch
n/a.
[EDU-4266]: https://aziontech.atlassian.net/browse/EDU-4266?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-4266] feat: add Release Note - Astro blog

- src/content/docs/en/pages/main-menu/reference/secure/edge-firewall/web-application-firewall/waf-rule-sets.mdx
Duplicated Youtube link
https://www.azion.com/en/documentation/products/secure/edge-firewall/web-application-firewall/rules-set/
> fix:duplicated youtube link

- src/content/docs/en/pages/main-menu/reference/build/edge-application/digital-certificates.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/build/edge-application/digital-certificates.mdx
* Made adjustments so information is better described.
> [NO-ISSUE] refactor: clearer rules

- src/content/docs/en/pages/main-menu/release-notes/release-notes.mdx
- src/content/docs/pt-br/pages/menu-principal/release-notes/release-notes.mdx
* Added release notes regarding CRL management.
[EDU-4292]: https://aziontech.atlassian.net/browse/EDU-4292?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-4292] feat: add release notes CRL

- src/content/docs/en/pages/guides/index.mdx
- src/content/docs/en/pages/guides/open-ticket/open-ticket.mdx
- src/content/docs/pt-br/pages/guias/open-ticket/open-ticket.mdx
- Removed severity description from guide (no longer set by the customer)
- Reviewed some sections of the guide for wording
[EDU-4299]: https://aziontech.atlassian.net/browse/EDU-4299?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-4299] chore: update tickets guide

- src/content/docs/en/pages/guides/open-ticket/open-ticket.mdx
- src/content/docs/pt-br/pages/guias/open-ticket/open-ticket.mdx
> hotfix: remove severity

- src/content/docs/en/pages/main-menu/reference/build/edge-application/rules-engine.mdx
- src/content/docs/en/pages/main-menu/reference/secure/edge-firewall/rules-engine.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/build/edge-application/rules-engine-edge-app.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/secure/edge-firewall/rules-engine-edge-firewall.mdx
- src/includes/snippets/RulesEngineExecution/en/snippet.mdx
- src/includes/snippets/RulesEngineExecution/pt/snippet.mdx
- Added snippet on rule execution logic to rules engine for EA and EF
[EDU-4183]: https://aziontech.atlassian.net/browse/EDU-4183?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-4183] feat: add new snippet to rules engine pages

- src/content/docs/en/pages/guides/index.mdx
- src/content/docs/en/pages/guides/marketplace/templates/vite-boilerplate.mdx
- src/content/docs/pt-br/pages/guias/guides.mdx
- src/content/docs/pt-br/pages/guias/marketplace/templates/vite-boilerplate.mdx
[EDU-4291]
-  Add a how-to guide to deploy the Vite Boilerplate.
- Include links in the Guides page.
n/a.
[EDU-4291]: https://aziontech.atlassian.net/browse/EDU-4291?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-4291] feat: add Vite Boilerplate guide

- src/content/docs/en/pages/build-journey/develop-with-azion/frameworks/framework-next.mdx
fix link youtube link video
https://www.azion.com/en/documentation/products/cli/frameworks/next/
> Edu 4324 fix link youtube link video

- src/content/docs/en/pages/main-menu/release-notes/release-notes.mdx
- src/content/docs/pt-br/pages/menu-principal/release-notes/release-notes.mdx
[EDU-4325]
- Add item in Release notes to inform new Marketplace launches: Vite Boilerplate and Upstash Rate Limiting integration.
n/a.
[EDU-4325]: https://aziontech.atlassian.net/browse/EDU-4325?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-4325] feat: add item in Release notes - Marketplace

- src/content/docs/en/pages/agreements/tos/terms-of-service.mdx
- src/content/docs/pt-br/pages/contratos/tos/index.mdx
> Fix: Update date release TOS

- src/content/docs/en/pages/main-menu/compliance/pci-dss.mdx
- src/content/docs/pt-br/pages/menu-principal/compliance/pci-dss.mdx
[NO-ISSUE] 
- Add how to request information sentence - PCI DSS certification
n/a.
> [NO-ISSUE] refactor: add how to request info sentence - PCI DSS certification

- src/content/docs/en/pages/guides/marketplace/templates/next-app-config.mdx
- src/content/docs/pt-br/pages/guias/marketplace/templates/next-app-config.mdx
[EDU-4214]
- Add new how-to guide EN and PT - Next App Configs template
n/a.
[EDU-4214]: https://aziontech.atlassian.net/browse/EDU-4214?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-4214] feat: add guide - Next App Configs template

- src/content/docs/en/pages/guides/marketplace/templates/next-app-middleware.mdx
- src/content/docs/pt-br/pages/guias/marketplace/templates/next-app-middleware.mdx
[EDU-4285]
- Add new how-to guide EN and PT- Next App Middleware template
n/a.
[EDU-4285]: https://aziontech.atlassian.net/browse/EDU-4285?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-4285] feat: add guide - Next App Middleware template

- src/content/docs/en/pages/guides/marketplace/templates/next-pages-config.mdx
- src/content/docs/pt-br/pages/guias/marketplace/templates/next-pages-config.mdx
[EDU-4287] 
- Add new how-to guide EN and PT- Next Pages Configs template
n/a.
[EDU-4287]: https://aziontech.atlassian.net/browse/EDU-4287?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-4287] feat: add guide - Next Pages Configs

- src/content/docs/en/pages/guides/marketplace/templates/next-pages-middleware.mdx
- src/content/docs/pt-br/pages/guias/marketplace/templates/next-pages-middleware.mdx
[EDU-4288]
- Add new how-to guide EN and PT- Next Pages MIddleware template
n/a.
[EDU-4288]: https://aziontech.atlassian.net/browse/EDU-4288?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-4288] feat: add guide - Next Pages + Middleware

- src/content/docs/en/pages/devtools/api-graphql/features/features.mdx
- src/content/docs/en/pages/devtools/api-graphql/first-steps/first-steps.mdx
- src/content/docs/en/pages/guides/graphql/query-graphql-postman.mdx
- src/content/docs/pt-br/pages/devtools/api-graphql/primeiros-passos/primeiros-passo-gql.mdx
- src/content/docs/pt-br/pages/devtools/api-graphql/recursos/recursos-gql.mdx
- src/content/docs/pt-br/pages/guias/graphql/query-postman.mdx
* Adding components to GraphQL docs.
[EDU-4188]: https://aziontech.atlassian.net/browse/EDU-4188?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-4188] feat: add components

- src/content/docs/en/pages/devtools/api-graphql/features/features.mdx
- src/content/docs/en/pages/guides/graphql/graphql-metadata.mdx
- src/content/docs/pt-br/pages/devtools/api-graphql/recursos/recursos-gql.mdx
- src/content/docs/pt-br/pages/guias/graphql/graphql-metadados.mdx
* Updated fields and responses in GraphQL queries.
[EDU-4279]: https://aziontech.atlassian.net/browse/EDU-4279?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-4279] refactor: update graphql queries

- src/content/docs/pt-br/pages/menu-principal/gerencie-contas/gerenciar-perfis/personal-token.mdx
Youtube link video
[EDU-3413]: https://aziontech.atlassian.net/browse/EDU-3413?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: youtube video

- src/content/docs/en/pages/devtools/api-graphql/features/events-fields/events-fields.mdx
- src/content/docs/en/pages/devtools/api-graphql/features/metrics-fields/metrics-fields.mdx
- src/content/docs/pt-br/pages/devtools/api-graphql/recursos/events-campos/events-campos.mdx
- src/content/docs/pt-br/pages/devtools/api-graphql/recursos/metrics-campos/metrics-campos.mdx
* Added a few fields and updated existing ones.
[EDU-4167]: https://aziontech.atlassian.net/browse/EDU-4167?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-4167] refactor: gql fields check

- src/content/docs/en/pages/main-menu/compliance/soc-2.mdx
- src/content/docs/pt-br/pages/menu-principal/compliance/soc.mdx
[No-issue]
- Minor fix in soc documentation.
n/a.
> [No-issue] fix: soc documentation

- src/content/docs/en/pages/devtools/cli/azion-cli/commands/dev-command/dev.mdx
- src/content/docs/pt-br/pages/devtools/cli/azion-cli/comandos/dev-command/dev.mdx
Related issue: https://aziontech.atlassian.net/browse/EDU-4444
> [EDU-4444] feat: add new flag to dev command

- src/content/docs/en/pages/guides/index.mdx
- src/content/docs/en/pages/guides/marketplace/templates/turso-starter-kit.mdx
- src/content/docs/pt-br/pages/guias/guides.mdx
- src/content/docs/pt-br/pages/guias/marketplace/templates/turso-starter-kit.mdx
[EDU-4321] 
- Add a how-to guide to deploy the new Turso Starter Kit.
- Add links to the guides page.
n/a.
[EDU-4321]: https://aziontech.atlassian.net/browse/EDU-4321?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-4321] feat: add guide - Turso Starter Kit

- src/content/docs/en/pages/guides/index.mdx
- src/content/docs/en/pages/guides/marketplace/templates/next-turso.mdx
- src/content/docs/pt-br/pages/guias/guides.mdx
- src/content/docs/pt-br/pages/guias/marketplace/templates/next-turso.mdx
[EDU-4323]
- Add how-to guide to deploy the new Next + Turso template.
- Add links to the guides page.
n/a.
[EDU-4323]: https://aziontech.atlassian.net/browse/EDU-4323?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-4323] feat: add guide - Next + Turso template

- src/content/docs/en/pages/devtools/cli/azion-cli/commands/create/create.mdx
- src/content/docs/en/pages/devtools/cli/azion-cli/commands/list/list.mdx
- src/content/docs/pt-br/pages/devtools/cli/azion-cli/comandos/create/create.mdx
- src/content/docs/pt-br/pages/devtools/cli/azion-cli/comandos/list/list.mdx
Related issue: https://aziontech.atlassian.net/browse/EDU-4445
Changes:
- Add edge storage bucket create and list commands (cli)
> [EDU-4445] add edge storage bucket commands

- src/content/docs/en/pages/guides/marketplace/integrations/bot-protection.mdx
- src/content/docs/pt-br/pages/guias/marketplace/integrations/bot-protection.mdx
[NO-ISSUE]
- Adjust action naming in the table.
- Add note about actions.
n/a.
> [NO-ISSUE] fix: action naming

- src/content/docs/en/pages/guides/index.mdx
- src/content/docs/en/pages/guides/marketplace/templates/gatsby-boilerplate.mdx
- src/content/docs/pt-br/pages/guias/guides.mdx
- src/content/docs/pt-br/pages/guias/marketplace/templates/gatsby-boilerplate.mdx
[EDU-4133]
- Add Gatsby boilerplate guide PT and EN.
- Add link to Guides pages
n/a.
[EDU-4133]: https://aziontech.atlassian.net/browse/EDU-4133?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-4133] feat: add Gatsby boilerplate guide.

- src/content/docs/en/pages/guides/marketplace/templates/nextjs-static-boilerplate.mdx
- src/content/docs/pt-br/pages/guias/marketplace/templates/next-static-boilerplate.mdx
[EDU-4446]
- update Next Static Boilerplate version.
n/a.
[EDU-4446]: https://aziontech.atlassian.net/browse/EDU-4446?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-4446] refactor: update Next Static Boilerplate version

- src/content/docs/en/pages/main-menu/additional-resources/templates-and-integrations/understand-azion-templates.mdx
- src/content/docs/pt-br/pages/menu-principal/recursos-adicionais/templates-e-integracoes/templates-visao-geral.mdx
[No-issue] 
- Add new templates to the Reference doc.
n/a.
> [No-issue] feat: add new templates - Reference

- src/content/docs/en/pages/devtools/cli/azion-cli/commands/create/create.mdx
- src/content/docs/en/pages/devtools/cli/azion-cli/commands/delete/delete.mdx
- src/content/docs/en/pages/devtools/cli/azion-cli/commands/describe/describe.mdx
- src/content/docs/en/pages/devtools/cli/azion-cli/commands/list/list.mdx
- src/content/docs/en/pages/devtools/cli/azion-cli/commands/update/update.mdx
- src/content/docs/pt-br/pages/devtools/cli/azion-cli/comandos/create/create.mdx
- src/content/docs/pt-br/pages/devtools/cli/azion-cli/comandos/delete/delete.mdx
- src/content/docs/pt-br/pages/devtools/cli/azion-cli/comandos/describe/describe.mdx
- src/content/docs/pt-br/pages/devtools/cli/azion-cli/comandos/list/list.mdx
- src/content/docs/pt-br/pages/devtools/cli/azion-cli/comandos/update/update.mdx
Related issue: https://aziontech.atlassian.net/browse/EDU-4462
Changes: 
- Add CLI edge storage bucket commands
- Add CLI edge storage object commands
> [EDU-4462] edge storage objects cli

- src/content/docs/en/pages/guides/index.mdx
- src/content/docs/en/pages/guides/marketplace/templates/htmx-minimal.mdx
- src/content/docs/en/pages/main-menu/additional-resources/templates-and-integrations/understand-azion-templates.mdx
- src/content/docs/pt-br/pages/guias/guides.mdx
- src/content/docs/pt-br/pages/guias/marketplace/templates/htmx-minimal.mdx
- src/content/docs/pt-br/pages/menu-principal/recursos-adicionais/templates-e-integracoes/templates-visao-geral.mdx
[EDU-4481]
- Add HTMX template guide - PT/EN
- Add link to guides page and reference.
n/a.
[EDU-4481]: https://aziontech.atlassian.net/browse/EDU-4481?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-4481] feat: add HTMX template guide

- src/content/docs/en/pages/main-menu/release-notes/release-notes.mdx
- src/content/docs/pt-br/pages/guias/marketplace/templates/htmx-minimal.mdx
- src/content/docs/pt-br/pages/menu-principal/release-notes/release-notes.mdx
[PMK- 7524][PMK-7514] 
- Add release note new templates: Azion Starter Kit + HTMX
n/a.
[PMK-7514]: https://aziontech.atlassian.net/browse/PMK-7514?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [PMK- 7524][PMK-7514] feat: add release note new templates

- src/content/docs/en/pages/devtools/cli/azion-cli/commands/link-project/link.mdx
- src/content/docs/pt-br/pages/devtools/cli/azion-cli/comandos/link-project/link.mdx
Related issue: https://aziontech.atlassian.net/browse/EDU-4487
> [EDU-4487] add remote flag to link command docs

- src/content/docs/en/pages/observe-journey/real-time-events/analyze-logs/investigate-requests.mdx
* Added new guide for investigation steps using GraphQL API.
[EDU-3763]: https://aziontech.atlassian.net/browse/EDU-3763?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-3763] feat: guide for investigation flow with graphql

- src/content/docs/pt-br/pages/observe-jornada/real-time-events/analise-logs/investigue-requisicoes.mdx
* Added new guide for investigation steps using GraphQL API.
[EDU-3763]: https://aziontech.atlassian.net/browse/EDU-3763?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-3763] feat: guide for investigation flow with graphql PT

- src/content/docs/en/pages/guides/data-streaming/associate-domains.mdx
- src/content/docs/en/pages/guides/data-streaming/custom-template.mdx
- src/content/docs/en/pages/guides/data-streaming/debug-functions-dts.mdx
- src/content/docs/en/pages/guides/real-time-metrics/use-real-time-metrics.mdx
- src/content/docs/en/pages/observe-journey/data-stream/advanced-configurations/configure-sampling.mdx
- src/content/docs/en/pages/observe-journey/data-stream/advanced-configurations/select-variables.mdx
- src/content/docs/en/pages/observe-journey/data-stream/edit-stream/configure-main-settings.mdx
- src/content/docs/en/pages/observe-journey/data-stream/edit-stream/set-payload.mdx
- src/content/docs/en/pages/observe-journey/data-stream/integrations/connector-amazon-s3.mdx
- src/content/docs/en/pages/observe-journey/data-stream/integrations/connector-aws-kinesis.mdx
- src/content/docs/en/pages/observe-journey/data-stream/integrations/connector-azure-blob.mdx
- src/content/docs/en/pages/observe-journey/data-stream/integrations/connector-azure-monitor.mdx
- src/content/docs/en/pages/observe-journey/data-stream/integrations/connector-big-query.mdx
- src/content/docs/en/pages/observe-journey/data-stream/integrations/connector-datadog.mdx
- src/content/docs/en/pages/observe-journey/data-stream/integrations/connector-elasticsearch.mdx
- src/content/docs/en/pages/observe-journey/data-stream/integrations/connector-splunk.mdx
- src/content/docs/en/pages/observe-journey/data-stream/integrations/connector-standard-http-https-post.mdx
- src/content/docs/en/pages/observe-journey/real-time-events/analyze-logs/add-filters.mdx
- src/content/docs/en/pages/observe-journey/real-time-events/analyze-logs/analyze-navigation-data.mdx
In Observe EN guides:
* Added note explaining Azion UIs
* Added tabs
* Separated steps according to the added tabs
[EDU-3612]: https://aziontech.atlassian.net/browse/EDU-3612?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-3612] feat: add tabs and console steps observe guides

- src/content/docs/pt-br/pages/guias/data-streaming/associar-dominios.mdx
- src/content/docs/pt-br/pages/guias/data-streaming/criar-template-personalizado.mdx
- src/content/docs/pt-br/pages/guias/data-streaming/debug-functions-dts.mdx
- src/content/docs/pt-br/pages/guias/real-time-metrics/usar-real-time-metrics.mdx
- src/content/docs/pt-br/pages/observe-jornada/data-stream/configuracoes-avancadas/configure-sampling.mdx
- src/content/docs/pt-br/pages/observe-jornada/data-stream/configuracoes-avancadas/selecionar-variaveis.mdx
- src/content/docs/pt-br/pages/observe-jornada/data-stream/editar-stream/adicionar-payload.mdx
- src/content/docs/pt-br/pages/observe-jornada/data-stream/editar-stream/configure-main-settings.mdx
- src/content/docs/pt-br/pages/observe-jornada/data-stream/integracoes/conector-azure-blob-storage.mdx
- src/content/docs/pt-br/pages/observe-jornada/data-stream/integracoes/conector-azure-monitor.mdx
- src/content/docs/pt-br/pages/observe-jornada/data-stream/integracoes/conector-big-query.mdx
- src/content/docs/pt-br/pages/observe-jornada/data-stream/integracoes/conector-datadog.mdx
- src/content/docs/pt-br/pages/observe-jornada/data-stream/integracoes/conector-elasticsearch.mdx
- src/content/docs/pt-br/pages/observe-jornada/data-stream/integracoes/conector-kinesis-data-firehose.mdx
- src/content/docs/pt-br/pages/observe-jornada/data-stream/integracoes/conector-s3.mdx
- src/content/docs/pt-br/pages/observe-jornada/data-stream/integracoes/conector-splunk.mdx
- src/content/docs/pt-br/pages/observe-jornada/data-stream/integracoes/conector-standard-http-https-post.mdx
- src/content/docs/pt-br/pages/observe-jornada/real-time-events/analise-logs/adicione-filtros.mdx
- src/content/docs/pt-br/pages/observe-jornada/real-time-events/analise-logs/analise-dados-navegacao.mdx
In Observe PT guides:
- Added note explaining Azion UIs
- Added tabs
- Separated steps according to the added tabs
[EDU-3612]: https://aziontech.atlassian.net/browse/EDU-3612?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-3612] feat: add tabs and console steps observe guides PT

- src/content/docs/en/homes/home-docs.mdx
- src/content/docs/en/pages/devtools/cli/azion-cli/azion-overview/azion-overview.mdx
- src/content/docs/en/pages/guides/graphql/graphql-metadata.mdx
- src/content/docs/en/pages/guides/index.mdx
- src/content/docs/en/pages/guides/intelligent-dns/run-dig-command.mdx
- src/content/docs/en/pages/main-menu/additional-resources/templates-and-integrations/use-a-template.mdx
- src/content/docs/en/pages/main-menu/reference/secure/edge-firewall/network-layer-protection/network-layer-protection.mdx
- src/content/docs/en/pages/main-menu/reference/secure/edge-firewall/network-layer-protection/network-list.mdx
- src/content/docs/en/pages/secure-journey/automate/integrate-siems.mdx
- src/content/docs/en/pages/secure-journey/secure-dns.mdx
- Changed `description` fields on some front matters to test improved SEO.
[EDU-2397]: https://aziontech.atlassian.net/browse/EDU-2397?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-2397] refactor: descriptions for seo

- src/content/docs/en/pages/main-menu/reference/build/edge-application/digital-certificates.mdx
- src/content/docs/en/pages/main-menu/reference/secure/edge-dns/dnssec/dnssec.mdx
- src/content/docs/en/pages/main-menu/reference/secure/edge-dns/edge-dns.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/build/edge-application/digital-certificates.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/secure/edge-dns/dnssec.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/secure/edge-dns/edge-dns.mdx
- Added buttons in Edge DNS, DNSSEC, and Digital Certificates references including links from Secure journey guides
[EDU-4189]: https://aziontech.atlassian.net/browse/EDU-4189?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-4189] feat: add buttons in edge dns reference

- src/content/docs/en/pages/main-menu/reference/build/edge-application/digital-certificates.mdx
- src/content/docs/en/pages/main-menu/reference/build/edge-application/domains/mtls.mdx
- src/content/docs/en/pages/main-menu/reference/build/edge-application/main-settings.mdx
- src/content/docs/en/pages/main-menu/reference/secure/edge-firewall/ddos-protection/ddos-protection.mdx
- src/content/docs/en/pages/main-menu/reference/secure/edge-firewall/edge-firewall.mdx
- src/content/docs/en/pages/main-menu/reference/secure/edge-firewall/edge-functions-for-edge-firewall/edge-functions-instances.mdx
- src/content/docs/en/pages/main-menu/reference/secure/edge-firewall/network-layer-protection/network-layer-protection.mdx
- src/content/docs/en/pages/main-menu/reference/secure/edge-firewall/network-layer-protection/network-list.mdx
- src/content/docs/en/pages/main-menu/reference/secure/edge-firewall/rules-engine.mdx
- src/content/docs/en/pages/main-menu/reference/secure/edge-firewall/web-application-firewall/web-application-firewall.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/build/edge-application/digital-certificates.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/build/edge-application/domains/mtls.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/build/edge-application/main-settings.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/secure/edge-firewall/ddos-protection.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/secure/edge-firewall/edge-firewall.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/secure/edge-firewall/edge-functions-instances-para-edge-firewall.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/secure/edge-firewall/network-layer-protection.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/secure/edge-firewall/network-lists.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/secure/edge-firewall/rules-engine-edge-firewall.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/secure/edge-firewall/web-application-firewall.mdx
- Added buttons in Edge Firewall-related references including links from Secure journey guides
- Fixed some tables formatting
[EDU-4189]: https://aziontech.atlassian.net/browse/EDU-4189?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-4189] feat: add buttons to edge firewall from secure journey

- src/content/docs/en/pages/build-journey/develop-with-azion/frameworks/framework-overview.mdx
- src/content/docs/en/pages/devtools/azion-edge-runtime/compatibility/frameworks.mdx
- src/content/docs/pt-br/pages/build-jornada/desenvolva-com-azion/guias-frameworks/framework-overview.mdx
- src/content/docs/pt-br/pages/devtools/azion-edge-runtime/compatibilidade/frameworks.mdx
Related issue: https://aziontech.atlassian.net/browse/EDU-4513
Changes: 
- add new presets to compatibility docs
> Upkeep frameworks compatibility

- src/content/docs/en/pages/guides/import-from-github/import-from-github.mdx
- src/content/docs/en/pages/guides/index.mdx
- src/content/docs/pt-br/pages/guias/guides.mdx
- src/content/docs/pt-br/pages/guias/importar-do-github/importar-do-github.mdx
[EDU-1360]
- Add Import from GitHub guide.
- Add the link to the guides page.
n/a.
[EDU-1360]: https://aziontech.atlassian.net/browse/EDU-1360?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-1360] feat: add Import from GitHub guide

- src/content/docs/en/pages/main-menu/get-started/get-started.mdx
- src/content/docs/pt-br/pages/menu-principal/ponto-de-partida/ponto-de-partida.mdx
[EDU-643] 
- Add a tip to Get Started, including Import from GitHub.
n/a.
[EDU-643]: https://aziontech.atlassian.net/browse/EDU-643?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-643] feat: Import from GitHub - add tip to Get Started

- src/content/docs/en/pages/guides/azion-github-app.mdx
- src/content/docs/en/pages/guides/index.mdx
- src/content/docs/pt-br/pages/guias/azion-github-app.mdx
- src/content/docs/pt-br/pages/guias/guides.mdx
[EDU-1559]
- Add Azion GitHub App guide.
- Add the link to the guides page.
n/a.
[EDU-1559]: https://aziontech.atlassian.net/browse/EDU-1559?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-1559] feat: add Azion GitHub App guide

- src/content/docs/en/pages/main-menu/manage-accounts/create-accountd.mdx
- src/content/docs/pt-br/pages/menu-principal/gerencie-contas/criar-conta.mdx
[EDU-4524] 
- Update the create account guide and align it with the console interface.
n/a.
[EDU-4524]: https://aziontech.atlassian.net/browse/EDU-4524?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-4524] feat: update create account guide

- src/content/docs/en/pages/guides/create-button/create-button.mdx
- src/content/docs/en/pages/guides/index.mdx
- src/content/docs/en/pages/main-menu/get-started/get-started.mdx
- src/content/docs/pt-br/pages/guias/create-button/create-button.mdx
- src/content/docs/pt-br/pages/guias/guides.mdx
- src/content/docs/pt-br/pages/menu-principal/ponto-de-partida/ponto-de-partida.mdx
[EDU-4479]
- Add How to use the Create button guide.
- Update a Get Started tip to include the link.
n/a.
[EDU-4479]: https://aziontech.atlassian.net/browse/EDU-4479?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-4479] feat: add How to use the Create button guide

- src/content/docs/en/pages/devtools/cli/azion-cli/commands/create/create.mdx
- src/content/docs/pt-br/pages/devtools/cli/azion-cli/comandos/create/create.mdx
Related issue: https://aziontech.atlassian.net/browse/EDU-4545
> [EDU-4545] feat: add json examples where missing

- src/content/docs/en/pages/main-menu/reference/build/edge-application/real-time-purge.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/build/edge-application/real-time-purge.mdx
[EDU-4566]
refactor purge confirmation details in product reference. 
https://aziontech.atlassian.net/browse/UXE-2498
[EDU-4566]: https://aziontech.atlassian.net/browse/EDU-4566?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-4566] refactor: purge confirmation details

- src/content/docs/en/pages/guides/import-from-github/import-from-github.mdx
- src/content/docs/pt-br/pages/guias/importar-do-github/importar-do-github.mdx
[UXE-2836]
- add a tip about the Variables key, in Import from GitHub guide
n/a.
[UXE-2836]: https://aziontech.atlassian.net/browse/UXE-2836?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [UXE-2836] refactor: add tip in Import from GitHub guide

- src/content/docs/en/pages/main-menu/additional-resources/templates-and-integrations/use-a-template.mdx
- src/content/docs/pt-br/pages/guias/marketplace/templates/wordpress-instacreator.mdx
- src/content/docs/pt-br/pages/menu-principal/recursos-adicionais/templates-e-integracoes/usar-um-template-via-rtm.mdx
[EDU-4471]
- Refine Use a template guide to reflect the updated flow.
n/a.
[EDU-4471]: https://aziontech.atlassian.net/browse/EDU-4471?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-4471] refactor: refine Use a template guide

- src/content/docs/en/pages/guides/intelligent-dns/run-dig-command.mdx
Azion CTAs moved to the end of the guide.
* Console create zone button
* Console Signup button
> [EDU-4578] Refactor EN run-dig-command.mdx

- src/content/docs/en/pages/guides/marketplace/integrations/fingerprint.mdx
- src/content/docs/pt-br/pages/guias/marketplace/integrations/fingerprint.mdx
[EDU-4564]
- Improve the Fingerprint guide, refining "embedding the script" instructions.
n/a.
[EDU-4564]: https://aziontech.atlassian.net/browse/EDU-4564?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-4564] refactor: refine Fingerprint guide

- src/content/docs/en/pages/main-menu/additional-resources/templates-and-integrations/understand-azion-templates.mdx
- src/content/docs/pt-br/pages/menu-principal/recursos-adicionais/templates-e-integracoes/templates-visao-geral.mdx
[EDU-4486]
- Refactor: reorganize and align use cases/templates reference.
n/a.
[EDU-4486]: https://aziontech.atlassian.net/browse/EDU-4486?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-4486] refactor: reorganize and align use cases/templates reference

- src/content/docs/en/pages/main-menu/reference/secure/edge-firewall/web-application-firewall/web-application-firewall.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/secure/edge-firewall/web-application-firewall/web-application-firewall.mdx
Minor refactoring for SEO. This doc competes in SERP with a blog page.
> [EDU-4614] Refactor web-application-firewall

- src/content/docs/en/pages/main-menu/reference/store/object-storage/index.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/store/edge-storage/index.mdx
[EDU-4547]
Improvements Edge Storage reference:
- Fix in the free operations note.
- Add info for ore clarity in the S3 credentials section.
n/a.
[EDU-4547]: https://aziontech.atlassian.net/browse/EDU-4547?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-4547] refactor: improvements Edge Storage reference.

- src/content/docs/en/pages/main-menu/reference/secure/edge-dns/edge-dns.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/secure/edge-dns/edge-dns.mdx
[EDU-4561]
Refactor Edge DNS reference to:
- Add DS type (Not documented)
- Improve DNS record types examples.
- Minor style fixes.
n/a.
[EDU-4561]: https://aziontech.atlassian.net/browse/EDU-4561?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-4561] refactor: Edge DNS ref update

- src/content/docs/en/pages/main-menu/reference/store/edge-sql/edge-sql.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/store/edge-sql/edge-sql.mdx
- Added Edge SQL reference in EN and PT
**Important**: links, examples, and the Features not supported section will be updated before merging.
[ENG-29956]: https://aziontech.atlassian.net/browse/ENG-29956?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-29956] feat: add edge sql reference

- src/content/docs/en/pages/guides/edge-sql/retrieve-data/index.mdx
related issue: https://aziontech.atlassian.net/browse/ENG-29958
> [ENG-29958] feat: add sql functions guide

- src/content/docs/en/pages/devtools/api-graphql/features/metrics-fields.mdx
- src/content/docs/pt-br/pages/devtools/api-graphql/recursos/metrics-campos.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/observe/real-time-metrics/real-time-metrics.mdx
[EDU-4577] 
Update WAF/Metrics docs about threats:
- GraphQL: edit table field to clarify variable in learning mode.
- Real-Time Metrics: edit section to align with UI and clarify variable in learning mode.
[PR Help Center - learning mode comment for the variable in EN version](https://github.com/aziontech/docs_help_center/pull/143/files)
[EDU-4577]: https://aziontech.atlassian.net/browse/EDU-4577?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-4577] Update WAF/Metrics docs about threats

- src/content/docs/en/pages/guides/debug-rules/debug-rules.mdx
- src/content/docs/en/pages/main-menu/reference/observe/real-time-events/real-time-events.mdx
- src/content/docs/en/pages/secure-journey/troubleshoot/edge-firewall-understand-metrics.mdx
- src/content/docs/pt-br/pages/guias/debug-regras/debug-regras.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/observe/real-time-events/real-time-events.mdx
- src/content/docs/pt-br/pages/secure-jornada/troubleshoot/edge-firewall-monitorar-metricas..mdx
[EDU-4616]
- Add note about debug rules behavior.
n/a.
[EDU-4616]: https://aziontech.atlassian.net/browse/EDU-4616?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-4616] Refactor: add note about debug rules

- src/content/docs/en/pages/devtools/cli/azion-cli/config/azion-config-js.mdx
related issue: https://aziontech.atlassian.net/browse/UXE-3212
> [UXE-3212] feat: add azion config file docs

- src/content/docs/pt-br/pages/secure-jornada/firewall-configuracoes-avancadas/criar-waf-rule-set.mdx
[No-Issue]
- Fix broken link in WAF rule set guide.
n/a.
> [No-issue] fix: broken link in WAF rule set guide

- src/content/docs/en/pages/main-menu/compliance/pci-dss.mdx
- src/content/docs/en/pages/main-menu/compliance/soc-2.mdx
- src/content/docs/pt-br/pages/menu-principal/compliance/pci-dss.mdx
- src/content/docs/pt-br/pages/menu-principal/compliance/soc.mdx
[EDU-4655] 
- refactor: compliance contact.
n/a.
[EDU-4655]: https://aziontech.atlassian.net/browse/EDU-4655?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-4655] refactor: compliance contact

- src/content/docs/en/pages/guides/index.mdx
- src/content/docs/en/pages/guides/marketplace/templates/jekyll-boilerplate.mdx
- src/content/docs/en/pages/main-menu/additional-resources/templates-and-integrations/understand-azion-templates.mdx
- src/content/docs/pt-br/pages/guias/guides.mdx
- src/content/docs/pt-br/pages/guias/marketplace/templates/jekyll-boilerplate.mdx
- src/content/docs/pt-br/pages/menu-principal/recursos-adicionais/templates-e-integracoes/templates-visao-geral.mdx
[EDU-4599]
- Add Jekyll Boilerplate guide (PT and EN).
- Add the link to the Guides page and Templates reference.
n/a.
[EDU-4599]: https://aziontech.atlassian.net/browse/EDU-4599?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-4599] feat: add Jekyll Boilerplate guide

- src/content/docs/en/pages/main-menu/reference/secure/edge-firewall/web-application-firewall/custom-allowed-rule.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/secure/edge-firewall/web-application-firewall/waf-custom-allowed-rules.mdx
[EDU-4648]
Adjust Custom Allowed Rules table:
- fix 1210 rule ID in EN.
- fix 1209 rule value and add 1210 rule in PT. 
n/a.
[EDU-4648]: https://aziontech.atlassian.net/browse/EDU-4648?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-4648] fix: adjust Custom Allowed Rules table

- src/content/docs/en/pages/main-menu/reference/observe/real-time-metrics/real-time-metrics.mdx
[EDU-4706]
- adjust product name: Edge DNS name and link in Real-Time Metrics ref.
n/a.
[EDU-4706]: https://aziontech.atlassian.net/browse/EDU-4706?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-4706] fix: adjust product name

- src/content/docs/en/pages/main-menu/release-notes/release-notes.mdx
- src/content/docs/pt-br/pages/menu-principal/release-notes/release-notes.mdx
[EDU-4704] 
- Add release note - Jekyll and Svelte Boilerplates. PT and EN.
- Fix link to PT.
n/a.
[EDU-4704]: https://aziontech.atlassian.net/browse/EDU-4704?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-4704] feat: Add release note - Jekyll and Svelte Boilerplates

- src/content/docs/en/pages/devtools/cli/azion-cli/commands/update/update.mdx
- src/content/docs/pt-br/pages/devtools/cli/azion-cli/comandos/update/update.mdx
Related issue: https://aziontech.atlassian.net/browse/EDU-4546
> [EDU-4546] feat: add json example to file flag

- src/content/docs/en/pages/main-menu/reference/services/integration-services/instructor-led-training.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/servicos/instructor-led-training.mdx
> [NO-ISSUE] fix: delete link

- src/content/docs/en/pages/guides/marketplace/integrations/bot-protection.mdx
- src/content/docs/pt-br/pages/guias/marketplace/integrations/bot-protection.mdx
[EDU-4622]
Update Bot Manager guide:
- Add variables: internal_logs and should_write_warning_logs.
- Organize non-mandatory variables alphabetically.
n/a.
[EDU-4622]: https://aziontech.atlassian.net/browse/EDU-4622?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-4622] refactor: update Bot Manager guide

- src/content/docs/en/pages/devtools/cli/azion-cli/azion-overview/azion-overview.mdx
- [EDU-4760] add: youtube video on doc: https://www.azion.com/en/documentation/products/azion-cli/overview/
[EDU-4760]: https://aziontech.atlassian.net/browse/EDU-4760?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> add: youtube video on doc

- src/content/docs/en/pages/guides/marketplace/integrations/rate-limiting-with-penalty.mdx
- src/content/docs/en/pages/guides/marketplace/templates/upstash-rate-limiting.mdx
[EDU-4001] fix: youtube link para doc /documentation/products/guides/upstash-rate-limiting/
[EDU-4001]: https://aziontech.atlassian.net/browse/EDU-4001?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: fix youtube link on doc

- src/content/docs/en/pages/guides/marketplace/integrations/hcaptcha.mdx
- [EDU-4754] add: Youtube video on doc
(https://www.azion.com/en/documentation/products/guides/hcaptcha/)
[EDU-4754]: https://aziontech.atlassian.net/browse/EDU-4754?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> add: Youtube video

- src/content/docs/en/pages/guides/marketplace/templates/angular-boilerplate.mdx
- [EDU-4753] add: Youtube video link on doc: https://www.azion.com/en/documentation/products/guides/angular-boilerplate/
[EDU-4753]: https://aziontech.atlassian.net/browse/EDU-4753?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> add: Youtube video link on doc

- src/content/docs/en/pages/guides/edge-storage/use-bucket-as-origin/index.mdx
- src/content/docs/pt-br/pages/guias/edge-storage/use-bucket-as-origin/index.mdx
[EDU-4552]
Update 'Use a bucket as origin' guide:
- Use tabs.
- Add tip to next steps.
n/a.
[EDU-4552]: https://aziontech.atlassian.net/browse/EDU-4552?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-4552] refactor: update 'Use a bucket as origin' guide

- src/content/docs/en/pages/main-menu/release-notes/release-notes.mdx
- src/content/docs/pt-br/pages/menu-principal/release-notes/release-notes.mdx
[EDU-4705]
- Update Release Notes with recent launches.
n/a.
[EDU-4705]: https://aziontech.atlassian.net/browse/EDU-4705?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-4705] feature: update Release Notes

- src/content/docs/en/pages/main-menu/reference/secure/edge-firewall/web-application-firewall/custom-allowed-rule.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/secure/edge-firewall/waf-custom-allowed-rules.mdx
[EDU-4766]
- Refine note in Allowed Rules reference about learning mode.
n/a.
[EDU-4766]: https://aziontech.atlassian.net/browse/EDU-4766?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-4766] fix: refine Allowed Rules note

- src/content/docs/en/pages/devtools/cli/azion-cli/config/azion-config-js.mdx
- src/content/docs/pt-br/pages/devtools/cli/azion-cli/configs/azion-config-js.mdx
https://aziontech.atlassian.net/browse/EDU-4762
> [EDU-4762] refactor: keep azionconfig docs update

- src/content/docs/en/pages/guides/index.mdx
- src/content/docs/en/pages/guides/waf/configure-allowed-rules.mdx
- src/content/docs/pt-br/pages/guias/guides.mdx
- src/content/docs/pt-br/pages/guias/waf/configurar-allowed-rules.mdx
[EDU-4688]
- Add Custom Allowed Rules guide - PT and EN.
- Add links to the Guides page.
n/a.
[EDU-4688]: https://aziontech.atlassian.net/browse/EDU-4688?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-4688] feat: add Custom Allowed Rules guide

- src/content/docs/en/pages/devtools/cli/azion-cli/config/azion-config-js.mdx
- src/content/docs/pt-br/pages/devtools/cli/azion-cli/configs/azion-config-js.mdx
https://aziontech.atlassian.net/browse/EDU-4808
> [EDU-4808 ] Adjust azion config js file

- src/content/docs/en/pages/main-menu/release-notes/release-notes.mdx
- src/content/docs/pt-br/pages/menu-principal/release-notes/release-notes.mdx
[EDU-3663]
- Add items to Release Notes (EN-PT).
n/a.
[EDU-3663]: https://aziontech.atlassian.net/browse/EDU-3663?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-3663] feature: add items to Release Notes (EN-PT)

- src/content/docs/en/pages/guides/edge-firewall/update-edge-firewall.mdx
- src/content/docs/en/pages/guides/index.mdx
- src/content/docs/pt-br/pages/guias/edge-firewall/atualizar-edge-firewall.mdx
- src/content/docs/pt-br/pages/guias/guides.mdx
[EDU-846]
- Review and align the 'How to update firewall' guide.
n/a.
> [EDU-846] refactor: review and align the 'How to update firewall' guide

- src/content/docs/en/pages/guides/edge-dns/run-dig-command.mdx
[No-issue]
- Fix a broken link of video in Dig command guide
n/a.
> [No-issue] fix: Broken link of video in Dig command guide

- src/content/docs/en/pages/main-menu/release-notes/release-notes.mdx
- src/content/docs/pt-br/pages/menu-principal/release-notes/release-notes.mdx
[EDU-4859] 
Add item from June 2024 to update the Release Notes page.
n/a.
[EDU-4859]: https://aziontech.atlassian.net/browse/EDU-4859?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-4859] feature: update Release Notes - June 2024.

- src/content/docs/en/pages/main-menu/reference/accounts/account-settings.mdx
- src/content/docs/en/pages/main-menu/reference/accounts/activity-history.mdx
- src/content/docs/en/pages/main-menu/reference/accounts/clients.mdx
- src/content/docs/en/pages/main-menu/reference/accounts/multi-factor-authentication.mdx
- src/content/docs/en/pages/main-menu/reference/accounts/personal-tokens.mdx
- src/content/docs/en/pages/main-menu/reference/accounts/social-login.mdx
- src/content/docs/en/pages/main-menu/reference/accounts/sso-integration.mdx
- src/content/docs/en/pages/main-menu/reference/accounts/teams-permissions.mdx
- src/content/docs/en/pages/main-menu/reference/accounts/users-management.mdx
- src/content/docs/en/pages/main-menu/reference/accounts/your-settings.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/contas/activity-history.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/contas/clientes.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/contas/configuracoes-conta.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/contas/multi-factor-authentication.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/contas/personal-tokens.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/contas/social-login.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/contas/sso.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/contas/teams-permissions.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/contas/users-management.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/contas/your-settings.mdx
[EDU-4478] 
- Refine Account references to be interface-agnostic.
n/a.
[EDU-4478]: https://aziontech.atlassian.net/browse/EDU-4478?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-4478] refactor: refine Account references

- src/content/docs/en/pages/guides/edge-dns/run-dig-command.mdx
Moving the video to the beginning of page
> [EDU-4853] Refactor 2 - run-dig-command.mdx

- src/content/docs/en/pages/main-menu/work-with-domains/configure-domains.mdx
- src/content/docs/en/pages/main-menu/work-with-domains/create-certificate.mdx
- src/content/docs/en/pages/main-menu/work-with-domains/migrate-ns.mdx
- src/content/docs/en/pages/main-menu/work-with-domains/point-domain.mdx
- src/content/docs/pt-br/pages/menu-principal/trabalhe-com-dominios/apontar-dominio.mdx
- src/content/docs/pt-br/pages/menu-principal/trabalhe-com-dominios/configurar-dominio.mdx
- src/content/docs/pt-br/pages/menu-principal/trabalhe-com-dominios/criar-certificado.mdx
- src/content/docs/pt-br/pages/menu-principal/trabalhe-com-dominios/migrar-ns.mdx
[EDU-4906]
- Add tabs to guides in the "Work with domains" (main menu) section.
n/a.
[EDU-4906]: https://aziontech.atlassian.net/browse/EDU-4906?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-4906] refactor: add tabs to "Work with domains" section

- src/content/docs/en/homes/platform-home.mdx
- src/content/docs/pt-br/homes/platform-home.mdx
[EDU-3068] 
- Add cards to Platform home: Social Login, Activity History, Your Settings (EN-PT).
n/a.
[EDU-3068]: https://aziontech.atlassian.net/browse/EDU-3068?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-3068] feature: add cards to Platform home

- src/content/docs/en/pages/main-menu/release-notes/release-notes.mdx
- src/content/docs/pt-br/pages/menu-principal/release-notes/release-notes.mdx
[EDU-4909]
-  Add the Release Note item related to the deprecation of Real-Time Metrics REST APIs.
n/a.
[EDU-4909]: https://aziontech.atlassian.net/browse/EDU-4909?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-4909] feature: add Release Note item - Real-Time Metrics REST APIs

- src/content/docs/en/pages/main-menu/release-notes/release-notes.mdx
- src/content/docs/pt-br/pages/menu-principal/release-notes/release-notes.mdx
[PMK-8487]
- Add the following item to the release notes: Docusaurus boilerplates - EN-PT.
n/a.
[PMK-8487]: https://aziontech.atlassian.net/browse/PMK-8487?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [PMK-8487] feature: add item to release notes: Docusaurus boilerplates

- src/content/docs/en/pages/guides/marketplace/integrations/ab-testing.mdx
- src/content/docs/pt-br/pages/guias/marketplace/integrations/ab-testing.mdx
[EDU-4946]
- Adjusting info in A/B Testing file - EN-PT.
n/a.
[EDU-4946]: https://aziontech.atlassian.net/browse/EDU-4946?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-4946] fix: adjusting info in A/B Testing file.

- src/content/docs/en/pages/main-menu/reference/accounts/teams-permissions.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/contas/teams-permissions.mdx
[EDU-4914] 
- Add permissions related to Edge SQL in the Team permissions reference.
n/a.
[EDU-4914]: https://aziontech.atlassian.net/browse/EDU-4914?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-4914] feature: add SQL Team permissions

- src/content/docs/en/pages/guides/edge-dns/run-dig-command.mdx
fix autoplay youtube video
/en/documentation/products/guides/run-the-dig-command/
> fix: autoplay youtube video

- src/content/docs/en/pages/main-menu/release-notes/release-notes.mdx
- src/content/docs/pt-br/pages/menu-principal/release-notes/release-notes.mdx
[PMK-8487]
- Add item to Release notes - Docusaurus templates: Docusaurus Blog Starter Kit and Docusaurus with Material UI.
n/a.
[PMK-8487]: https://aziontech.atlassian.net/browse/PMK-8487?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [PMK-8487] feature: add item to Release notes - Docusaurus templates

- src/content/docs/en/pages/devtools/azion-edge-runtime/api-reference/edge-sql/edge-sql.mdx
- src/content/docs/en/pages/guides/edge-sql/retrieve-data/index.mdx
- src/content/docs/en/pages/main-menu/reference/store/edge-sql/edge-sql.mdx
- src/content/docs/pt-br/pages/devtools/azion-edge-runtime/api-reference/edge-sql/edge-sql.mdx
- src/content/docs/pt-br/pages/guias/edge-sql/gerenciar-banco.mdx
- src/content/docs/pt-br/pages/guias/edge-sql/listar-dados/index.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/store/edge-sql/edge-sql.mdx
[EDU-4944]
- Add a comment in the Edge SQL reference to explain the Main/Replicas logic better.
- Add a button with the link to the reference in SQL-related guides.
n/a.
[EDU-4944]: https://aziontech.atlassian.net/browse/EDU-4944?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-4944] refactor: add comment in Edge SQL reference

- src/content/docs/en/pages/devtools/cli/azion-cli/azion-overview/azion-overview.mdx
> fix: youtube video link to cli

- src/content/docs/en/pages/store-journey/storage/create-bucket.mdx
https://aziontech.atlassian.net/browse/EDU-5092
> [EDU-5092] feat: refactor create a bucket guide and add it

- src/content/docs/en/pages/store-journey/storage/list-buckets.mdx
> [EDU-5094] feat: add list buckets 

- src/content/docs/en/pages/main-menu/reference/secure/edge-firewall/web-application-firewall/custom-allowed-rule.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/secure/edge-firewall/web-application-firewall/waf-custom-allowed-rules.mdx
[EDU-5142]
- Adjust WAF custom rules note.
n/a.
[EDU-5142]: https://aziontech.atlassian.net/browse/EDU-5142?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-5142] fix: adjust WAF custom rules note

- src/content/docs/en/pages/guides/edge-application/ea-configure-cache-policies.mdx
- src/content/docs/pt-br/pages/guias/edge-application/ea-cache-policies.mdx
Replace 'response phase' with 'request phase' on forward cookies rule guide
> [EDU-5205] fix: forward cookies on request phase

- src/content/docs/en/pages/main-menu/manage-accounts/manage-account/billing-and-subscriptions.mdx
- src/content/docs/en/pages/main-menu/reference/accounts/billing.mdx
- src/content/docs/pt-br/pages/menu-principal/gerencie-contas/gerenciar-contas/faturamento-e-assinaturas.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/contas/faturamento.mdx
[EDU-4846]
- Update Billing docs to reflect new pages in Console.
n/a.
[EDU-4846]: https://aziontech.atlassian.net/browse/EDU-4846?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-4846] refactor: update Billing docs

- src/content/docs/en/pages/guides/graphql/connected-users-dataset.mdx
- src/content/docs/pt-br/pages/guias/graphql/connected-users-dataset.mdx
[NO-ISSUE]
- Adjust connectedUsersMetrics dataset naming
n/a.
> [NO-ISSUE] fix: connectedUsersMetrics dataset naming

- src/content/docs/en/pages/build-journey/develop-with-azion/frameworks/framework-overview.mdx
- src/content/docs/en/pages/devtools/azion-edge-runtime/compatibility/frameworks.mdx
- src/content/docs/pt-br/pages/build-jornada/desenvolva-com-azion/guias-frameworks/framework-overview.mdx
Update supported frameworks list on the framework-specific overview.
> [EDU-5217] Update supported framework list

- src/content/docs/en/homes/home-docs.mdx
Update sections and cards to prioritize user intention
> [EDU-4818] feat: Update home texts and cards

- src/content/docs/en/pages/guides/marketplace/integrations/how-to-massive-redirection.mdx
[EDU-5291]
- delete tip with a link to a deleted file.
https://github.com/aziontech/docs/pull/1185
[EDU-5291]: https://aziontech.atlassian.net/browse/EDU-5291?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-5291] fix: delete tip with deleted file

- src/content/docs/pt-br/homes/doc-home.mdx
> [EDU-5305] Translate home page

- src/content/docs/en/pages/guides/idp/microsoft-entra-user-provisioning.mdx
- src/content/docs/en/pages/guides/index.mdx
- src/content/docs/pt-br/pages/guias/guides.mdx
- src/content/docs/pt-br/pages/guias/idp/provisionamento-usuarios-microsoft-entra.mdx
[EDU-5149]
- Add Automated user provisioning with Microsoft Entra guide EN/PT.
- Add the link to the Guides page EN/PT.
https://github.com/aziontech/docs/pull/1173
[EDU-5149]: https://aziontech.atlassian.net/browse/EDU-5149?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-5149] feature: add Automated user provisioning with Microsoft Entra guide

- src/content/docs/en/pages/secure-journey/edit-zone/add-records.mdx
> fix: update broken url

- src/content/docs/en/pages/deploy-journey/configure-node/authorize-node/authorize-node.mdx
- src/content/docs/pt-br/pages/deploy-jornada/configurar-node/autorizar-node/autorizar-node.mdx
Fix  "Authorize a node" guide.
> [EDU-5336] Revise authorize node guide

- src/content/docs/en/pages/deploy-journey/configure-node/create-service/create-service.mdx
- src/content/docs/pt-br/pages/deploy-jornada/configurar-node/criar-service/criar-service.mdx
> [EDU-5228] fix: Revise create service guide

- src/content/docs/en/pages/deploy-journey/configure-node/bind-service/bind-service.mdx
- src/content/docs/pt-br/pages/deploy-jornada/configurar-node/vincular-service/vincular-service.mdx
Revise "Bind an edge service"guide.
> [EDU-5339] fix: revise bind service guide

- src/content/docs/en/pages/main-menu/additional-resources/templates-and-integrations/understand-azion-templates.mdx
- src/content/docs/pt-br/pages/menu-principal/recursos-adicionais/templates-e-integracoes/templates-visao-geral.mdx
[EDU-5285]
- Add Deploy button to Templates reference PT/EN.
https://github.com/aziontech/docs/pull/1201
https://github.com/aziontech/docs/pull/1204
[EDU-5285]: https://aziontech.atlassian.net/browse/EDU-5285?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-5285] [EDU-5286] feature: add Deploy button to Templates reference

- src/content/docs/en/pages/deploy-journey/configure-node/provision-files/provision-file.mdx
- src/content/docs/pt-br/pages/deploy-jornada/configurar-node/provisionar-arquivos/provisionar-arquivos.mdx
Revise "Provision files" guide.
> [EDU-5340] Fix: revise provision files guide

- src/content/docs/en/pages/deploy-journey/configure-node/work-with-variables/work-with-variables.mdx
- src/content/docs/pt-br/pages/deploy-jornada/configurar-node/trabalhar-variaveis/trabalhar-com-variaveis.mdx
Revise "Working with variables" guide.
> fix: revise work with variables

- src/content/docs/en/pages/deploy-journey/configure-node/unbind-service/unbind-service.mdx
- src/content/docs/pt-br/pages/deploy-jornada/configurar-node/desvincular-service/unbind-service.mdx
Revise "Unbind an edge service" guide.
> [EDU-5342] Fix: revise unbinding a service

- src/content/docs/en/pages/guides/account-lockout-policy/configure-account-lockout-policy.mdx
- src/content/docs/en/pages/guides/account-lockout-policy/logs-account-lockout-policy.mdx
- src/content/docs/en/pages/guides/account-lockout-policy/unlock-user-account-lockout-policy.mdx
- src/content/docs/en/pages/guides/accounts/conditional-access-by-ip.mdx
- src/content/docs/en/pages/guides/accounts/configure-user-session-timeout.mdx
- src/content/docs/en/pages/main-menu/reference/accounts/account-lockout-policy.mdx
- src/content/docs/en/pages/main-menu/reference/accounts/user-session-timeout.mdx
- src/content/docs/en/pages/main-menu/release-notes/release-notes.mdx
- src/content/docs/pt-br/pages/guias/account-lockout-policy/configure-account-lockout-policy.mdx
- src/content/docs/pt-br/pages/guias/account-lockout-policy/logs-account-lockout-policy.mdx
- src/content/docs/pt-br/pages/guias/account-lockout-policy/unlock-user-account-lockout-policy.mdx
- src/content/docs/pt-br/pages/guias/contas/conditional-access-by-ip.mdx
- src/content/docs/pt-br/pages/guias/contas/configurar-user-session-timeout.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/contas/account-lockout-policy.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/contas/user-session-timeout.mdx
- src/content/docs/pt-br/pages/menu-principal/release-notes/release-notes.mdx
[EDU-5361]
Add Preview tag to docs:
- Account Lockout Policy
- User Session Timeout Policy
- Conditional Access by IP Address.
- Release Notes
n/a.
[EDU-5361]: https://aziontech.atlassian.net/browse/EDU-5361?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-5361] fix: add Preview tag to docs

- src/content/docs/en/pages/deploy-journey/advanced-config/run-scripts/run-scripts.mdx
- src/content/docs/pt-br/pages/deploy-jornada/avancado/rodar-scripts/rodar-scripts.mdx
> [EDU-5344] Fix: revise run scripts guide

- src/content/docs/en/pages/deploy-journey/advanced-config/uninstall/uninstall-node.mdx
- src/content/docs/pt-br/pages/deploy-jornada/avancado/desinstalar-node/desinstalar-node.mdx
Revise "Uninstall node" guide.
> [EDU-5345] Fix: revise uninstall node

- src/content/docs/en/pages/deploy-journey/automate/api/automate-api.mdx
- src/content/docs/en/pages/deploy-journey/automate/zero-touch-provisioning/zero-touch-provisioning.mdx
- src/content/docs/pt-br/pages/deploy-jornada/automatizar/zero-touch-provisioning/zero-touch-provisioning.mdx
Revise "Zero-touch provisioning" page in deploy journey
> [EDU-5347] Fix: revise zero-touch provisioning

- src/content/docs/pt-br/pages/menu-principal/release-notes/release-notes.mdx
> Release notes Minor fix - data format

- cicd/azion-massive-redirect-en.json
- cicd/azion-massive-redirect-ptbr.json
[No-Issue]
- Include redirect for deleted guide, EN/PT.
n/a.
> [No-Issue] fix: redirect - deleted guide

- src/content/docs/en/pages/main-menu/release-notes/release-notes.mdx
- src/content/docs/pt-br/pages/menu-principal/release-notes/release-notes.mdx
Added missing entry on August Release Notes.
> [EDU-5374] Update release notes

- src/content/docs/en/pages/guides/index.mdx
- src/content/docs/en/pages/guides/marketplace/integrations/add-request-id.mdx
- src/content/docs/en/pages/main-menu/additional-resources/templates-and-integrations/understand-azion-integrations.mdx
- src/content/docs/pt-br/pages/guias/guides.mdx
- src/content/docs/pt-br/pages/guias/marketplace/integrations/add-request-id.mdx
- src/content/docs/pt-br/pages/menu-principal/recursos-adicionais/templates-e-integracoes/integracoes-visao-geral.mdx
[EDU-5203]
- Add 'Add Request ID' integration guide EN/PT.
- Add the link to the Guides page.
- Add the link and info in the Integrations reference.
n/a.
[EDU-5203]: https://aziontech.atlassian.net/browse/EDU-5203?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-5203] feature: add 'Add Request ID' integration guide

- src/content/docs/en/pages/guides/index.mdx
- src/content/docs/en/pages/guides/waf/allowlist-waf-cookie.mdx
- src/content/docs/pt-br/pages/guias/guides.mdx
- src/content/docs/pt-br/pages/guias/waf/allowlist-waf-cookie.mdx
[EDU-4603]
- Add WAF rules for specific cookie guide EN/PT.
- Add the link to the Guides Page.
n/a.
[EDU-4603]: https://aziontech.atlassian.net/browse/EDU-4603?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-4603] feature: add WAF rules for specific cookie guide

- src/content/docs/en/pages/main-menu/release-notes/release-notes.mdx
- src/content/docs/pt-br/pages/menu-principal/release-notes/release-notes.mdx
[PMK-7228] [PMK-8628]
- Add items - Release Notes EN/PT: Deployy button and Add Request ID integration.
n/a.
[PMK-7228]: https://aziontech.atlassian.net/browse/PMK-7228?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[PMK-8628]: https://aziontech.atlassian.net/browse/PMK-8628?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [PMK-7228] [PMK-8628] feature: add items - Release Notes

- src/content/docs/en/pages/guides/waf/check-waf-mode.mdx
> add: Link to youtube video

- src/content/docs/en/pages/main-menu/reference/secure/edge-firewall/web-application-firewall/waf-rule-sets.mdx
[EDU-5381] fix: Youtube Title playlist on WAF rule sets
[EDU-5381]: https://aziontech.atlassian.net/browse/EDU-5381?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: Title youtube playlist

- src/content/docs/en/pages/main-menu/reference/secure/edge-firewall/web-application-firewall/web-application-firewall.mdx
[EDU-5382]: https://aziontech.atlassian.net/browse/EDU-5382?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> add: Youtube playlist on waf doc

- src/content/docs/en/pages/store-journey/sql/insert-into-table.mdx
Creates "Insert into table" guide on Store Journey.
> [EDU-5109] Insert into table guide on Store Journey

- src/content/docs/en/pages/store-journey/sql/delete-database.mdx
Creates the "Delete database"guide on Store Journey.
> [EDU-5107] delete database journey guide

- src/content/docs/en/pages/guides/idp/microsoft-entra-user-provisioning.mdx
- src/content/docs/pt-br/pages/guias/idp/provisionamento-usuarios-microsoft-entra.mdx
[No-Issue]
- Delete an item from a step in the Microsoft Entra provisioning guide.
n/a.
> [No-Issue] fix: delete item from Microsoft Entra provisioning guide

- src/content/docs/en/pages/guides/marketplace/templates/wordpress-edgeaccelerator.mdx
> add:video-link-on-doc-wordpress-edgeaccelerator

- src/content/docs/en/pages/guides/marketplace/templates/upstash-rate-limiting.mdx
> add:Youtube link on doc Upstash rate limit

- src/content/docs/en/pages/guides/marketplace/templates/turso-starter-kit.mdx
> add:youtube video link on turso starter kit doc

- src/content/docs/en/pages/guides/marketplace/templates/static-cache.mdx
> add:youtube video link suite starter kit on doc

- src/content/docs/en/pages/guides/marketplace/templates/qstash-scheduler.mdx
> add: QStash Edge function youtube video link on doc

- src/content/docs/en/pages/guides/marketplace/templates/mongodb-template.mdx
> add: youtube link to MongoDB Atlas Boilerplate

- src/content/docs/en/pages/guides/marketplace/templates/image-optimization.mdx
> add:Youtube video link to Image Optimization on doc

- src/content/docs/en/pages/guides/marketplace/templates/fauna-template.mdx
https://www.azion.com/en/documentation/products/guides/fauna-template/
> add:Youtube video link on doc Fauna DB boilerplate

- src/content/docs/en/pages/guides/marketplace/templates/edge-application-proxy.mdx
https://www.azion.com/en/documentation/products/guides/edge-application-proxy-template/
> add: Youtube video link edge applicatiion proxy on doc

- src/content/docs/en/pages/guides/marketplace/templates/dynamic-and-static-file-optimization.mdx
https://www.azion.com/en/documentation/products/guides/dynamic-and-static-file-optimization-template/
> add:Youtube video link Dynamic and Static File on Azion doc

- src/content/docs/en/pages/guides/marketplace/templates/bot-with-firewall.mdx
http://localhost:4321/en/documentation/products/guides/bot-manager-integration-kit/
> add: Youtube link video Bot Manager integration Kit

- src/content/docs/en/pages/guides/marketplace/templates/bot-with-tor.mdx
https://www.azion.com/en/documentation/products/guides/bot-manager-and-tor-block-starter-kit/
> add: Youtube link Bot Manager and Tor Block Starter Kit on doc

- src/content/docs/en/pages/guides/marketplace/templates/azion-starter-kit.mdx
https://www.azion.com/en/documentation/products/guides/azion-starter-kit/
> add: Youtube link Azion Starter Kit on Azion doc

- src/content/docs/en/pages/build-journey/develop-with-azion/frameworks/framework-hexo.mdx
https://www.azion.com/en/documentation/products/cli/frameworks/hexo/
> add:Youtube Hexo video on Azion doc

- src/content/docs/en/pages/build-journey/develop-with-azion/frameworks/framework-vite.mdx
https://www.azion.com/en//documentation/products/cli/frameworks/vite/
> add: Vite Youtube Video link on Azion doc

- src/content/docs/en/pages/guides/cli/cli-vulcan-use-polyfills.mdx
https://www.azion.com/en/documentation/devtools/guides/cli/use-polyfills/
> add: Youtube video link polyfills on doc

- src/content/docs/en/pages/build-journey/develop-with-azion/frameworks/framework-react.mdx
https://www.azion.com/en//documentation/products/cli/frameworks/react/
> add: react Youtube video link on azion doc

- src/content/docs/en/pages/build-journey/develop-with-azion/frameworks/framework-vue.mdx
https://www.azion.com/en//documentation/products/cli/frameworks/vue/
> add: Vue Youtube video link on Azion doc

- src/content/docs/en/pages/main-menu/reference/store/object-storage/index.mdx
https://www.azion.com/en/documentation/products/store/edge-storage/
> add:Youtube video link on Azion doc

- src/content/docs/en/pages/architectures/compliance/compliance-architecture.mdx
- src/content/docs/pt-br/pages/arquiteturas/compliance/compliance-architecture.mdx
The solution link is still not available. Temporary fix
> Fix 404 compliance-architecture

- src/content/docs/en/pages/devtools/azion-edge-runtime/api-reference/object-storage/object-storage.mdx
https://www.azion.com/en/documentation/runtime/api-reference/storage/
> add:Edge Storage API interface Youtube video on doc

- src/content/docs/en/pages/architectures/edge-native/edge-native-apps.mdx
- src/content/docs/pt-br/pages/arquiteturas/edge-native-apps.mdx
- src/content/docs/pt-br/pages/arquiteturas/edge-native/edge-native-apps.mdx
Translates Edge-Native Application architecture.
> [EDU-5448] Translate edge-native arch

- src/content/docs/en/pages/devtools/cli/azion-cli/commands/list/list.mdx
https://www.azion.com/en/documentation/devtools/cli/list/
> add:youtube video link about  Azion Edge Storage via CLI

- src/content/docs/en/pages/guides/edge-sql/create-database.mdx
https://www.azion.com/en/documentation/products/guides/manage-databases-edge-sql/
> add:Youtube video to how to manage edge sql on doc

- src/content/docs/en/pages/guides/edge-sql/retrieve-data/index.mdx
https://www.azion.com/en/documentation/products/guides/edge-sql/retrieve-data-with-edge-functions/
> add: youtube video on how to retrieve data with edge functions

- src/content/docs/en/pages/main-menu/reference/store/edge-sql/edge-sql.mdx
https://www.azion.com/en/documentation/products/store/edge-sql/#interacting-with-edge-sql-via-terminal
> add: video edge sql via terminal

- src/content/docs/en/pages/architectures/compliance/compliance-architecture.mdx
- src/content/docs/pt-br/pages/arquiteturas/compliance/compliance-architecture.mdx
[EDU-5283] 
- Add link to solution page in Compliance architecture, PT/EN
n/a.
[EDU-5283]: https://aziontech.atlassian.net/browse/EDU-5283?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-5283] refactor: add link to solution page in Compliance architecture

- src/content/docs/en/pages/devtools/cli/azion-cli/commands/link-project/link.mdx
https://www.azion.com/en/documentation/products/cli/link-command/
> add: youtube video cli link command on azion doc

- src/content/docs/en/pages/build-journey/develop-with-azion/frameworks/framework-astro.mdx
https://www.azion.com/en/documentation/products/cli/frameworks/astro/#answering-no-to-local-dev
> add: Astro local dev youtube video link on Azion doc

- src/content/docs/en/pages/guides/debugging-functions-graphql/debug-functions-gql.mdx
https://www.azion.com/en/documentation/products/guides/debugging-functions-graphql/
> add: Debugging edge functions and graphql api Youtube video link on doc

- src/content/docs/en/pages/devtools/azion-edge-runtime/debugging/debugging.mdx
https://www.azion.com/en/documentation/devtools/debugging/
> add: debugging youtube video on Azion's doc

- src/content/docs/en/pages/devtools/cli/azion-cli/commands/logs/logs.mdx
https://www.azion.com/en/documentation/devtools/cli/logs/
> add: Tail command youtube video on Azion's doc

- src/content/docs/en/pages/devtools/api-graphql/queries/queries.mdx
https://www.azion.com/en/documentation/devtools/graphql-api/queries/
> add: operators api youtube video on Azion's doc

- src/content/docs/en/pages/main-menu/additional-resources/developer-tools/graphql-playground.mdx
https://www.azion.com/en/documentation/products/devtools/graphql-playground/
> add: graphql playgroun video on Azion's doc

- src/content/docs/en/pages/store-journey/storage/create-bucket.mdx
- src/content/docs/en/pages/store-journey/storage/delete-bucket.mdx
- src/content/docs/en/pages/store-journey/storage/delete-object.mdx
- src/content/docs/en/pages/store-journey/storage/list-objects-.mdx
- src/content/docs/en/pages/store-journey/storage/update-bucket.mdx
- src/content/docs/en/pages/store-journey/storage/update-object.mdx
- src/content/docs/en/pages/store-journey/storage/upload-object.mdx
- src/content/docs/en/pages/store-journey/storage/use-bucket-as-origin.mdx
- src/content/docs/pt-br/pages/store-jornada/storage/atualizar-bucket.mdx
- src/content/docs/pt-br/pages/store-jornada/storage/atualizar-objeto.mdx
- src/content/docs/pt-br/pages/store-jornada/storage/criar-bucket.mdx
- src/content/docs/pt-br/pages/store-jornada/storage/deletar-bucket.mdx
- src/content/docs/pt-br/pages/store-jornada/storage/deletar-objeto.mdx
- src/content/docs/pt-br/pages/store-jornada/storage/listar-buckets.mdx
- src/content/docs/pt-br/pages/store-jornada/storage/listar-objetos.mdx
- src/content/docs/pt-br/pages/store-jornada/storage/upload-objeto.mdx
- src/content/docs/pt-br/pages/store-jornada/storage/usar-bucket-como-origem.mdx
- src/content/docs/pt-br/pages/store-jornada/visao-geral.mdx
Translates the guides under the section "Bucket operations" in the Store journey, as well as the journey overview page.
Additional adjustments in the journey guides.
> [EDU-5463] Translate bucket operations guides

- src/content/docs/en/pages/main-menu/reference/secure/edge-firewall/web-application-firewall/web-application-firewall.mdx
https://www.azion.com/en/documentation/products/secure/edge-firewall/web-application-firewall/
> update: waf playlist on doc

- src/content/docs/en/pages/store-journey/storage/use-s3.mdx
- src/content/docs/pt-br/pages/store-jornada/storage/usar-s3.mdx
- src/content/docs/pt-br/pages/usar-s3.mdx
Translate S3 Compatibility guide in store journey
> [EDU-5466] Translate S3 compatibilty guide

- src/content/docs/en/pages/store-journey/sql/delete-database.mdx
- src/content/docs/en/pages/store-journey/sql/delete-record.mdx
- src/content/docs/en/pages/store-journey/sql/list-db.mdx
- src/content/docs/en/pages/store-journey/sql/query-rows.mdx
- src/content/docs/pt-br/pages/store-jornada/sql/criar-banco.mdx
- src/content/docs/pt-br/pages/store-jornada/sql/criar-tabela.mdx
- src/content/docs/pt-br/pages/store-jornada/sql/deletar-banco.mdx
- src/content/docs/pt-br/pages/store-jornada/sql/deletar-registro.mdx
- src/content/docs/pt-br/pages/store-jornada/sql/inserir-em-tabela.mdx
- src/content/docs/pt-br/pages/store-jornada/sql/listar-db.mdx
- src/content/docs/pt-br/pages/store-jornada/sql/query-rows.mdx
- src/content/docs/pt-br/pages/store-jornada/sql/recuperar-informacoes-banco.mdx
> [EDU-5467] Translate Edge SQL guides

- src/content/docs/en/pages/architectures/orch/application-deliver-operation.mdx
- src/content/docs/pt-br/pages/arquiteturas/orch/application-deliver-automation.mdx
Translates the Application Delivery Automation architecture.
> feat: translate application delivery architecture

- src/content/docs/en/homes/architectures.mdx
- src/content/docs/pt-br/homes/arquiteturas.mdx
Adds "Application Delivery Automation" card to the architectures home.
> Add arch to architectures home

- src/content/docs/en/pages/architectures/edge-application/serverless-apps.mdx
- src/content/docs/en/pages/guides/graphql/connected-users-dataset.mdx
- src/content/docs/en/pages/guides/marketplace/integrations/add-request-id.mdx
- src/content/docs/en/pages/guides/marketplace/templates/bot-starter-kit.mdx
- src/content/docs/en/pages/observe-journey/real-time-events/analyze-logs/investigate-requests.mdx
- src/content/docs/en/pages/store-journey/sql/create-table.mdx
- src/content/docs/en/pages/store-journey/storage/create-bucket.mdx
- src/content/docs/pt-br/pages/arquiteturas/compliance/compliance-architecture.mdx
- src/content/docs/pt-br/pages/guias/graphql/connected-users-dataset.mdx
- src/content/docs/pt-br/pages/guias/marketplace/integrations/add-request-id.mdx
- src/content/docs/pt-br/pages/guias/marketplace/templates/bot-starter-kit.mdx
- src/content/docs/pt-br/pages/observe-jornada/real-time-events/analise-logs/investigue-requisicoes.mdx
- src/content/docs/pt-br/pages/store-jornada/sql/criar-tabela.mdx
- src/content/docs/pt-br/pages/store-jornada/sql/inserir-em-tabela.mdx
- src/content/docs/pt-br/pages/store-jornada/sql/recuperar-informacoes-banco.mdx
- src/content/docs/pt-br/pages/store-jornada/storage/criar-bucket.mdx
- src/content/docs/pt-br/pages/store-jornada/storage/usar-bucket-como-origem.mdx
[EDU-5469]
- Fix broken URLs to avoid returning 404 and other errors
n/a.
[EDU-5469]: https://aziontech.atlassian.net/browse/EDU-5469?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-5469] fix: broken urls 404 errors

- src/content/docs/en/homes/architectures.mdx
> Minor fix on architectures

- src/content/docs/en/pages/guides/index.mdx
- src/content/docs/en/pages/guides/marketplace/templates/devscard.mdx
- src/content/docs/en/pages/main-menu/additional-resources/templates-and-integrations/understand-azion-templates.mdx
- src/content/docs/pt-br/pages/guias/guides.mdx
- src/content/docs/pt-br/pages/guias/marketplace/templates/devscard.mdx
- src/content/docs/pt-br/pages/menu-principal/recursos-adicionais/templates-e-integracoes/templates-visao-geral.mdx
Adds guide for DevsCard template.
> [EDU-5279] Guide devscard template

- src/content/docs/en/pages/guides/marketplace/templates/image-optimization.mdx
- src/content/docs/en/pages/guides/marketplace/templates/static-cache.mdx
> update: videos image optimization and static cache on Azion docs

- src/content/docs/en/pages/architectures/edge-firewall/waap-architecture.mdx
- src/content/docs/en/pages/architectures/security-modernization/security-modernization-with-edge-computing.mdx
- src/content/docs/en/pages/main-menu/compliance/pci-dss.mdx
- src/content/docs/en/pages/main-menu/compliance/soc-2.mdx
- src/content/docs/en/pages/main-menu/reference/secure/edge-firewall/ddos-protection/ddos-protection.mdx
- src/content/docs/en/pages/main-menu/reference/secure/edge-firewall/edge-firewall.mdx
- src/content/docs/en/pages/secure-journey/edit-edge-firewall/edit-main-settings.mdx
- src/content/docs/en/pages/secure-journey/overview.mdx
- src/content/docs/pt-br/pages/arquiteturas/edge-firewall/waap-arquitetura.mdx
- src/content/docs/pt-br/pages/arquiteturas/security-modernization/security-modernization-com-edge-computing.mdx
- src/content/docs/pt-br/pages/menu-principal/compliance/pci-dss.mdx
- src/content/docs/pt-br/pages/menu-principal/compliance/soc.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/secure/edge-firewall/ddos-protection/ddos-protection.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/secure/edge-firewall/edge-firewall.mdx
- src/content/docs/pt-br/pages/secure-jornada/editar-edge-firewall/editar-main settings.mdx
- src/content/docs/pt-br/pages/secure-jornada/visao-geral.mdx
[EDU-5476]
- Adjust and update DDoS Protection reference.
- Adjust naming.
https://github.com/aziontech/docs/pull/1302
[EDU-5476]: https://aziontech.atlassian.net/browse/EDU-5476?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-5476] refactor: adjust and update DDoS Protection reference

- src/content/docs/en/pages/main-menu/reference/secure/edge-firewall/ddos-protection/ddos-mitigation.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/secure/edge-firewall/ddos-protection/ddos-mitigation.mdx
[EDU-5476]
- Adjust and update DDoS mitigation file
https://github.com/aziontech/docs/pull/1300
[EDU-5476]: https://aziontech.atlassian.net/browse/EDU-5476?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-5476] refactor: adjust and update DDoS mitigation file

- src/content/docs/en/pages/guides/index.mdx
- src/content/docs/en/pages/guides/marketplace/templates/eleventy-ecommerce-collection.mdx
- src/content/docs/en/pages/main-menu/additional-resources/templates-and-integrations/understand-azion-templates.mdx
- src/content/docs/pt-br/pages/guias/guides.mdx
- src/content/docs/pt-br/pages/guias/marketplace/templates/eleventy-ecommerce-collection.mdx
- src/content/docs/pt-br/pages/menu-principal/recursos-adicionais/templates-e-integracoes/templates-visao-geral.mdx
Creates the guide for the Eleventy E-commerce Templates collection.
> [EDU-5389] Eleventy E-commerce Templates guide

- src/content/docs/en/pages/guides/index.mdx
- src/content/docs/en/pages/guides/marketplace/templates/nextjs-ecommerce-collection.mdx
- src/content/docs/en/pages/main-menu/additional-resources/templates-and-integrations/understand-azion-templates.mdx
- src/content/docs/pt-br/pages/guias/guides.mdx
- src/content/docs/pt-br/pages/guias/marketplace/templates/nextjs-ecommerce-collection.mdx
- src/content/docs/pt-br/pages/menu-principal/recursos-adicionais/templates-e-integracoes/templates-visao-geral.mdx
Creates the Next.js E-commerce Templates guide.
> [EDU -5393] Next.js e-commerce templates guide

- src/content/docs/en/pages/guides/index.mdx
- src/content/docs/en/pages/guides/marketplace/templates/react-book-store.mdx
- src/content/docs/en/pages/main-menu/additional-resources/templates-and-integrations/understand-azion-templates.mdx
- src/content/docs/pt-br/pages/guias/guides.mdx
- src/content/docs/pt-br/pages/guias/marketplace/templates/astro-ecommerce-collection.mdx
- src/content/docs/pt-br/pages/guias/marketplace/templates/eleventy-ecommerce-collection.mdx
- src/content/docs/pt-br/pages/guias/marketplace/templates/gatsby-ecommerce-theme.mdx
- src/content/docs/pt-br/pages/guias/marketplace/templates/hugo-ecommerce-collection.mdx
- src/content/docs/pt-br/pages/guias/marketplace/templates/jekyll-ecommerce-collection.mdx
- src/content/docs/pt-br/pages/guias/marketplace/templates/react-book-store.mdx
- src/content/docs/pt-br/pages/guias/marketplace/templates/webpage-to-pdf-resume.mdx
- src/content/docs/pt-br/pages/menu-principal/recursos-adicionais/templates-e-integracoes/templates-visao-geral.mdx
Creates the Book Store React template guide.
Small fix on Gatsby template namespace.
> [EDU-5394] Book Store React template guide

- src/content/docs/pt-br/pages/guias/graphql/query-bot-manager-data.mdx
- src/content/docs/pt-br/pages/observe-jornada/real-time-events/analise-logs/investigue-requisicoes.mdx
- src/content/docs/pt-br/pages/secure-jornada/firewall-configuracoes-avancadas/gerenciar-bots.mdx
[EDU-5497] 
Adjust broken links in Docs.
n/a
[EDU-5497]: https://aziontech.atlassian.net/browse/EDU-5497?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-5497] fix: adjust broken links in Docs

- src/content/docs/en/pages/deploy-journey/configure-node/bind-service/bind-service.mdx
- src/content/docs/pt-br/pages/deploy-jornada/configurar-node/vincular-service/vincular-service.mdx
Updates edge service guides (console instructions)
> [EDU-5487] Update edge service guides

- src/content/docs/en/pages/guides/marketplace/templates/image-optimization.mdx
https://www.azion.com/en/documentation/products/guides/image-optimization-template/
> update: youtube video image optimization on doc

- src/content/docs/en/pages/guides/marketplace/templates/edge-application-proxy.mdx
https://www.azion.com/en/documentation/products/guides/edge-application-proxy-template/
> update: edge application proxy video on Azion doc

- src/content/docs/en/pages/guides/marketplace/templates/azion-starter-kit.mdx
https://www.azion.com/en/documentation/products/guides/azion-starter-kit/
> update: Azion Starter kit video on Azion docs

- src/content/docs/en/pages/main-menu/release-notes/release-notes.mdx
- src/content/docs/pt-br/pages/menu-principal/release-notes/release-notes.mdx
Adds new CLI version on release notes
> CLI 2.0 release notes

- src/content/docs/en/pages/devtools/api-graphql/features/features.mdx
- src/content/docs/en/pages/devtools/api-graphql/features/metrics-fields.mdx
- src/content/docs/en/pages/main-menu/reference/observe/real-time-metrics/real-time-metrics.mdx
- src/content/docs/pt-br/pages/devtools/api-graphql/recursos/metrics-campos.mdx
- src/content/docs/pt-br/pages/devtools/api-graphql/recursos/recursos-gql.mdx
- src/content/docs/pt-br/pages/guias/graphql/query-bot-manager-data.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/observe/real-time-metrics/real-time-metrics.mdx
- src/content/docs/pt-br/pages/observe-jornada/real-time-events/analise-logs/investigue-requisicoes.mdx
- src/content/docs/pt-br/pages/secure-jornada/firewall-configuracoes-avancadas/gerenciar-bots.mdx
[EDU-5478] 
Update existing docs to add information related to botManagerBreakdownMetrics dataset and graphs:
- Add the dataset to table in graphql-features file.
- Add the dataset description and fields to metrics-fields file.
- Add graphs description to Metrics reference.
n/a.
[EDU-5478]: https://aziontech.atlassian.net/browse/EDU-5478?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-5478] refactor: update existing docs to add information related to botManagerBreakdownMetrics dataset and graphs

- src/content/docs/en/pages/devtools/api-graphql/features/metrics-fields.mdx
- src/content/docs/pt-br/pages/devtools/api-graphql/recursos/metrics-campos.mdx
[EDU-5478]
- Detail Bot Manager actions in the Metrics Fields table, related to the dataset. 
n/a.
[EDU-5478]: https://aziontech.atlassian.net/browse/EDU-5478?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-5478] refactor: detail Bot Manager actions in Metrics Fields table. 

- src/content/docs/en/pages/devtools/cli/azion-cli/azion-overview/azion-overview.mdx
- src/content/docs/pt-br/pages/devtools/cli/azion-cli/azion-overview/azion-overview.mdx
Minor changes on CLI Overview page.
> [EDU-5524] Update CLI overview

- src/content/docs/en/pages/devtools/cli/azion-cli/commands/dev-command/dev.mdx
- src/content/docs/pt-br/pages/devtools/cli/azion-cli/comandos/dev-command/dev.mdx
Small changes on `dev` CLI command guide to clarify the purpose of the `link` command
> [EDU-5526] improve dev command reference

- src/content/docs/en/pages/main-menu/release-notes/release-notes.mdx
- src/content/docs/pt-br/pages/menu-principal/release-notes/release-notes.mdx
[PMK-8457]
Add item to Release Notes to announce Azion Copilot launch. EN/PT.
n/a.
[PMK-8457]: https://aziontech.atlassian.net/browse/PMK-8457?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [PMK-8457] feature: add item to Release Notes - Copilot

- src/content/docs/en/pages/devtools/azion-edge-runtime/compatibility/frameworks.mdx
- src/content/docs/en/pages/guides/marketplace/integrations/ipqs.mdx
- src/content/docs/pt-br/pages/devtools/azion-edge-runtime/compatibilidade/frameworks.mdx
- src/content/docs/pt-br/pages/guias/marketplace/integrations/ipqs.mdx
> [no-issue] fix: update broken external links

- cicd/azion-massive-redirect-en.json
- cicd/azion-massive-redirect-ptbr.json
- src/content/docs/en/homes/architectures.mdx
- src/content/docs/en/homes/home-docs.mdx
- src/content/docs/en/pages/architectures/api-gateways/api-gateways-security.mdx
- src/content/docs/en/pages/architectures/bot-management/bot-management-architecture.mdx
- src/content/docs/en/pages/architectures/compliance/compliance-architecture.mdx
- src/content/docs/en/pages/architectures/edge-application/microservices.mdx
- src/content/docs/en/pages/architectures/edge-enhanced/edge-enhanced.mdx
- src/content/docs/en/pages/architectures/edge-firewall/waap-architecture.mdx
- src/content/docs/en/pages/architectures/edge-native/edge-native-apps.mdx
- src/content/docs/en/pages/architectures/jamstack/jamstack.mdx
- src/content/docs/en/pages/architectures/live-streaming/live-streaming-delivery-hls.mdx
- src/content/docs/en/pages/architectures/security-modernization/security-modernization-with-edge-computing.mdx
- src/content/docs/pt-br/homes/arquiteturas.mdx
- src/content/docs/pt-br/homes/doc-home.mdx
- src/content/docs/pt-br/pages/arquiteturas/api-gateways/api-gateways-security.mdx
- src/content/docs/pt-br/pages/arquiteturas/bot-management/bot-management-arquitetura.mdx
- src/content/docs/pt-br/pages/arquiteturas/compliance/compliance-architecture.mdx
- src/content/docs/pt-br/pages/arquiteturas/edge-application/application-acceleration.mdx
- src/content/docs/pt-br/pages/arquiteturas/edge-application/content-delivery.mdx
- src/content/docs/pt-br/pages/arquiteturas/edge-application/microservices.mdx
- src/content/docs/pt-br/pages/arquiteturas/edge-enhanced/edge-enhanced.mdx
- src/content/docs/pt-br/pages/arquiteturas/edge-firewall/waap-arquitetura.mdx
- src/content/docs/pt-br/pages/arquiteturas/edge-native/edge-native-apps.mdx
- src/content/docs/pt-br/pages/arquiteturas/jamstack/jamstack.mdx
- src/content/docs/pt-br/pages/arquiteturas/live-streaming-delivery/live-streming-delivery-com-hls.mdx
- src/content/docs/pt-br/pages/arquiteturas/security-modernization/security-modernization-com-edge-computing.mdx
Updates the urls of architectures pages and links on cards to meet better standards.
Additionally, redirects are added from the previous urls.
> [EDU-5470] Update architectures urls

- src/content/docs/en/pages/architectures/api-gateways/api-gateways-security.mdx
- src/content/docs/en/pages/architectures/bot-management/bot-management-architecture.mdx
- src/content/docs/en/pages/architectures/security-modernization/security-modernization-with-edge-computing.mdx
- src/content/docs/en/pages/guides/edge-application/ea-enforce-hls.mdx
- src/content/docs/pt-br/pages/arquiteturas/api-gateways/api-gateways-security.mdx
- src/content/docs/pt-br/pages/arquiteturas/bot-management/bot-management-arquitetura.mdx
- src/content/docs/pt-br/pages/arquiteturas/live-streaming-delivery/live-streming-delivery-com-hls.mdx
- src/content/docs/pt-br/pages/arquiteturas/security-modernization/security-modernization-com-edge-computing.mdx
- src/content/docs/pt-br/pages/guias/edge-application/ea-enforce-hls.mdx
Fix architectures broken links.
> [no-issue] fix architectures links

- src/content/docs/en/pages/main-menu/reference/secure/edge-firewall/web-application-firewall/custom-allowed-rule.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/secure/edge-firewall/web-application-firewall/waf-custom-allowed-rules.mdx
[EDU-5586]
Relocate note in Custom Allowed Rules file for better UX
n/a.
[EDU-5586]: https://aziontech.atlassian.net/browse/EDU-5586?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-5586] refactor: relocate note in Custom Allowed Rules file

- src/content/docs/en/pages/main-menu/reference/observe/real-time-metrics/real-time-metrics.mdx
- src/content/docs/en/pages/main-menu/release-notes/release-notes.mdx
- src/content/docs/pt-br/pages/menu-principal/release-notes/release-notes.mdx
[EDU-5591] [EDU-5605]
- Add new items to the Release Notes page related to the GraphQL filter and updates in Events and the Bot Manager dashboard in Metrics.
n/a.
[EDU-5591]: https://aziontech.atlassian.net/browse/EDU-5591?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[EDU-5605]: https://aziontech.atlassian.net/browse/EDU-5605?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-5591] [EDU-5605] features: add new items to the Release Notes page

- src/content/docs/en/pages/guides/index.mdx
- src/content/docs/en/pages/guides/marketplace/templates/nuxt-static-boilerplate.mdx
- src/content/docs/en/pages/main-menu/additional-resources/templates-and-integrations/understand-azion-templates.mdx
- src/content/docs/pt-br/pages/guias/guides.mdx
- src/content/docs/pt-br/pages/guias/marketplace/templates/nuxt-static-boilerplate.mdx
- src/content/docs/pt-br/pages/menu-principal/recursos-adicionais/templates-e-integracoes/templates-visao-geral.mdx
Creates the Nuxt 3 Static Boilerplate template guide.
> [EDU-5543] Nuxt boilerplate guide

- src/content/docs/en/pages/devtools/cli/azion-cli/commands/deploy/deploy.mdx
- src/content/docs/pt-br/pages/devtools/cli/azion-cli/comandos/deploy/deploy.mdx
Adds the --local flag to the deploy command reference.
> [EDU-5539] Add local flag on deploy command

- src/content/docs/en/pages/store-journey/overview.mdx
- src/content/docs/pt-br/pages/store-jornada/visao-geral.mdx
Updates Store journey overview to be more consistent to other journeys.
> [EDU-5531] Improve store journey overview

- src/content/docs/en/pages/devtools/cli/azion-cli/commands/deploy/deploy.mdx
- src/content/docs/pt-br/pages/devtools/cli/azion-cli/comandos/deploy/deploy.mdx
Adds information about the use of the `--debug` flag with the `deploy` command and the viewing of logs on the terminal.
> [EDU-5541] update debug flag

- src/content/docs/en/pages/guides/edge-dns/run-dig-command.mdx
/documentation/products/guides/run-the-dig-command/
Update on doc - Dig command
> update: dig command doc

- src/content/docs/en/pages/guides/index.mdx
- src/content/docs/en/pages/guides/marketplace/templates/nuxt-content.mdx
- src/content/docs/en/pages/main-menu/additional-resources/templates-and-integrations/understand-azion-templates.mdx
- src/content/docs/pt-br/pages/guias/guides.mdx
- src/content/docs/pt-br/pages/guias/marketplace/templates/nuxt-content.mdx
- src/content/docs/pt-br/pages/menu-principal/recursos-adicionais/templates-e-integracoes/templates-visao-geral.mdx
Creates the Nuxt Content Template guide.
> [EDU]-5618 Nuxt content guide

- src/content/docs/en/pages/guides/marketplace/integrations/send-event-endpoint.mdx
- src/content/docs/pt-br/pages/guias/marketplace/integrations/send-event-endpoint.mdx
Updates arguments for the "Send events to endpoint" function.
> [EDU-5629] - Update Send event to endpoint guide

- src/includes/snippets/InterfaceNote/en/snippet.mdx
- src/includes/snippets/InterfaceNote/pt/snippet.mdx
Updates the note about user interface to display a notice about the imminent discontinuation of RTM.
The notice is already being shown in all pages which contain RTM steps.
> [EDU-5622] RTM final notice

- src/content/docs/en/pages/main-menu/reference/secure/edge-firewall/azion-bot-manager.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/secure/edge-firewall/azion-bot-manager.mdx
Updates the Bot Manager reference page to include more information on bot classification.
> [EDU-5668] Update Bot Manager reference page

- src/content/docs/en/homes/home-docs.mdx
- src/content/docs/pt-br/homes/doc-home.mdx
Changed broken url in Next template.
> docs: change broken url

- src/content/docs/en/pages/main-menu/release-notes/release-notes.mdx
- src/content/docs/pt-br/pages/menu-principal/release-notes/release-notes.mdx
> [EDU-5636] Update release notes

- src/content/docs/en/pages/main-menu/reference/build/edge-application/rules-engine.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/build/edge-application/rules-engine-edge-app.mdx
Adds the request_body variable on Rules Engine reference.
> [EDU-5628] Add request_body variable on rules engine

- src/content/docs/en/pages/observe-journey/data-stream/edit-stream/configure-main-settings.mdx
- src/content/docs/pt-br/pages/observe-jornada/data-stream/editar-stream/configure-main-settings.mdx
Add permissions note on Data Stream guide
> [EDU-5670] Edit Data Stream guide

- src/content/docs/en/pages/devtools/azion-edge-runtime/debugging/debugging.mdx
- src/content/docs/pt-br/pages/devtools/azion-edge-runtime/debugging/debugging.mdx
Fixes and updates the Debugging with Edge Functions page to match the patterns of a guide, show updated steps and configurations, and provide links to the related reference pages.
> [EDU-5137] Adjust debugging documentation

- src/content/docs/en/pages/observe-journey/data-stream/edit-stream/configure-main-settings.mdx
- src/content/docs/en/pages/observe-journey/data-stream/integrations/connector-amazon-s3.mdx
- src/content/docs/en/pages/observe-journey/data-stream/integrations/connector-aws-kinesis.mdx
- src/content/docs/en/pages/observe-journey/data-stream/integrations/connector-azion-edge-storage.mdx
- src/content/docs/en/pages/observe-journey/data-stream/integrations/connector-azure-blob.mdx
- src/content/docs/en/pages/observe-journey/data-stream/integrations/connector-azure-monitor.mdx
- src/content/docs/en/pages/observe-journey/data-stream/integrations/connector-big-query.mdx
- src/content/docs/en/pages/observe-journey/data-stream/integrations/connector-datadog.mdx
- src/content/docs/en/pages/observe-journey/data-stream/integrations/connector-elasticsearch.mdx
- src/content/docs/en/pages/observe-journey/data-stream/integrations/connector-splunk.mdx
- src/content/docs/en/pages/observe-journey/data-stream/integrations/connector-standard-http-https-post.mdx
- src/content/docs/pt-br/pages/observe-jornada/data-stream/editar-stream/configure-main-settings.mdx
- src/content/docs/pt-br/pages/observe-jornada/data-stream/integracoes/conector-azure-blob-storage.mdx
- src/content/docs/pt-br/pages/observe-jornada/data-stream/integracoes/conector-azure-monitor.mdx
- src/content/docs/pt-br/pages/observe-jornada/data-stream/integracoes/conector-big-query.mdx
- src/content/docs/pt-br/pages/observe-jornada/data-stream/integracoes/conector-datadog.mdx
- src/content/docs/pt-br/pages/observe-jornada/data-stream/integracoes/conector-elasticsearch.mdx
- src/content/docs/pt-br/pages/observe-jornada/data-stream/integracoes/conector-kinesis-data-firehose.mdx
- src/content/docs/pt-br/pages/observe-jornada/data-stream/integracoes/conector-s3.mdx
- src/content/docs/pt-br/pages/observe-jornada/data-stream/integracoes/conector-splunk.mdx
- src/content/docs/pt-br/pages/observe-jornada/data-stream/integracoes/conector-standard-http-https-post.mdx
- src/content/docs/pt-br/pages/observe-jornada/data-stream/integracoes/connector-azion-edge-storage.mdx
[EDU-5812]
- Update note in Data Stream installation guide.
- Add note in installation guides on how to use connectors to receive data from Data Stream.
n/a.
[EDU-5812]: https://aziontech.atlassian.net/browse/EDU-5812?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-5812] refactor: update and add note in Data Stream docs

- src/content/docs/en/pages/guides/edge-storage/create-object-storage/index.mdx
- src/content/docs/en/pages/main-menu/reference/store/object-storage/index.mdx
- src/content/docs/en/pages/store-journey/storage/create-bucket.mdx
- src/content/docs/en/pages/store-journey/storage/update-bucket.mdx
- src/content/docs/en/pages/store-journey/storage/use-bucket-as-origin.mdx
- src/content/docs/pt-br/pages/guias/edge-storage/create-object-storage/index.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/store/edge-storage/index.mdx
- src/content/docs/pt-br/pages/store-jornada/storage/atualizar-bucket.mdx
- src/content/docs/pt-br/pages/store-jornada/storage/criar-bucket.mdx
- src/content/docs/pt-br/pages/store-jornada/storage/usar-bucket-como-origem.mdx
[NO-ISSUE] 
Add warning in the Edge Storage docs, related to permissions.
n/a.
> [NO-ISSUE] refactor: add warning in the Edge Storage docs

- src/content/docs/en/pages/architectures/bot-management/bot-management-architecture.mdx
- src/content/docs/en/pages/architectures/edge-application/image-processing.mdx
- src/content/docs/en/pages/architectures/edge-firewall/waap-architecture.mdx
- src/content/docs/en/pages/architectures/security-modernization/security-modernization-with-edge-computing.mdx
- src/content/docs/pt-br/pages/arquiteturas/bot-management/bot-management-arquitetura.mdx
- src/content/docs/pt-br/pages/arquiteturas/edge-application/image-processor.mdx
- src/content/docs/pt-br/pages/arquiteturas/edge-firewall/waap-arquitetura.mdx
- src/content/docs/pt-br/pages/arquiteturas/security-modernization/security-modernization-com-edge-computing.mdx
Adds the "Deploy with Azion" button on architectures associated with templates.
> [EDU-5665] Update architectures with Deploy button

- src/includes/snippets/InterfaceNote/en/snippet.mdx
- src/includes/snippets/InterfaceNote/pt/snippet.mdx
Updates the date for RTM End-of-line in the interface note snippet.
> [EDU-5843] Update RTM End of Line note

- src/content/docs/en/pages/guides/marketplace/integrations/waiting-room.mdx
- src/content/docs/pt-br/pages/guias/marketplace/integrations/waiting-room.mdx
Adds new arguments to Upstash Waiting Room guide.
> [EDU-5819] Update Upstash Waiting Room guide

- src/content/docs/en/pages/main-menu/release-notes/release-notes.mdx
- src/content/docs/pt-br/pages/menu-principal/release-notes/release-notes.mdx
[EDU-5849]
- Add an item in the Release Notes page: Simple Storage Service (S3) connector update in file name structure. EN/PT
n/a.
[EDU-5849]: https://aziontech.atlassian.net/browse/EDU-5849?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-5849] feature: add Simple Storage Service (S3) connector update in Release Notes

- src/content/docs/en/pages/agreements/2021-01-14-index.mdx
- src/content/docs/en/pages/agreements/savings-plan/savings-plan.mdx
- src/content/docs/pt-br/pages/contratos/contratos.mdx
- src/content/docs/pt-br/pages/contratos/savings-plan/savings-plan.mdx
[EDU-5669]
Add and publish the Terms and Conditions of the Savings Plan files EN/PT.
Include the link in the Agreements page EN/PT.
n/a.
[EDU-5669]: https://aziontech.atlassian.net/browse/EDU-5669?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-5669] feature: add and publish Savings Plan Terms and Conditions

- src/content/docs/en/pages/main-menu/reference/observe/data-stream/data-stream.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/observe/data-streaming/data-streaming.mdx
[EDU-5813] 
Adjust and update description in Data Stream reference, for Object Key Prefix in S3 connectors.
n/a.
[EDU-5813]: https://aziontech.atlassian.net/browse/EDU-5813?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-5813] refactor: adjust description in Data Stream ref

- src/content/docs/en/pages/main-menu/reference/store/object-storage/index.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/store/edge-storage/index.mdx
[EDU-4447]
- Update the Edge Storage operations section in the reference file to separate and include operations via API and S3 protocol.
n/a.
[EDU-4447]: https://aziontech.atlassian.net/browse/EDU-4447?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-4447] refactor: update Edge Storage operations

- src/content/docs/en/pages/main-menu/additional-resources/templates-and-integrations/install-an-integration.mdx
- src/content/docs/pt-br/pages/menu-principal/recursos-adicionais/templates-e-integracoes/instalar-uma-integracao.mdx
Oi, fiz alguns ajustes de terminologia para padronizar os dois idiomas.
> [EDU-5874] refactor: ajuste de terminologia

- src/content/docs/en/pages/guides/index.mdx
- src/content/docs/en/pages/guides/marketplace/templates/vuepress-boilerplate.mdx
- src/content/docs/en/pages/main-menu/additional-resources/templates-and-integrations/understand-azion-templates.mdx
- src/content/docs/pt-br/pages/guias/guides.mdx
- src/content/docs/pt-br/pages/guias/marketplace/templates/vuepress-boilerplate.mdx
- src/content/docs/pt-br/pages/menu-principal/recursos-adicionais/templates-e-integracoes/templates-visao-geral.mdx
Adds the VuePress Boilerplate guide.
> [EDU-5633] Vuepress Boilerplate guide

- src/content/docs/en/pages/guides/index.mdx
- src/content/docs/en/pages/guides/marketplace/integrations/cardstream.mdx
- src/content/docs/en/pages/main-menu/additional-resources/templates-and-integrations/understand-azion-integrations.mdx
- src/content/docs/pt-br/pages/guias/guides.mdx
- src/content/docs/pt-br/pages/guias/marketplace/integrations/cardstream.mdx
- src/content/docs/pt-br/pages/menu-principal/recursos-adicionais/templates-e-integracoes/integracoes-visao-geral.mdx
Adds the Axur Cardstream integration guide, already fit to the new version of the function.
> [EDU-5231] Axur Cardstream guide

- src/content/docs/en/pages/guides/index.mdx
- src/content/docs/en/pages/guides/marketplace/templates/stencil-pwa-boilerplate.mdx
- src/content/docs/en/pages/main-menu/additional-resources/templates-and-integrations/understand-azion-templates.mdx
- src/content/docs/pt-br/pages/guias/guides.mdx
- src/content/docs/pt-br/pages/guias/marketplace/templates/stencil-pwa-boilerplate.mdx
- src/content/docs/pt-br/pages/menu-principal/recursos-adicionais/templates-e-integracoes/templates-visao-geral.mdx
Creates the Stencil PWA Boilerplate guide.
> [EDU-5856] Stencil PWA Boilerplate guide

- src/content/docs/en/pages/architectures/security-automation/security-automation.mdx
> ]no-issue] Fix 404 link

- src/content/docs/en/pages/main-menu/reference/observe/real-time-metrics/real-time-metrics.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/observe/real-time-metrics/real-time-metrics.mdx
[EDU-5968]
adjust terms in Real-Time Metrics reference: Edge Application to Data Transferred to be aligned with UI.
n/a.
[EDU-5968]: https://aziontech.atlassian.net/browse/EDU-5968?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-5968] refactor: adjust terms in Real-Time Metrics reference

- src/content/docs/en/pages/guides/marketplace/templates/stencil-pwa-boilerplate.mdx
- src/content/docs/pt-br/pages/guias/marketplace/templates/stencil-pwa-boilerplate.mdx
Amended the PWA template version after confirming with @pablodiehl
> [EDU-5979] fix: amended-template-version-on-the-PWA-guide

- src/content/docs/en/pages/guides/marketplace/integrations/cardstream.mdx
- src/content/docs/pt-br/pages/guias/marketplace/integrations/cardstream.mdx
Adds a note about the use of the function variables.
> [EDU-5974] Add explanatory note on Axus Cardstream integration guide

- src/content/docs/en/pages/changelog/changelog.mdx
- src/content/docs/en/pages/changelog/previous-years/previous-years-changelog.mdx
- src/content/docs/en/pages/main-menu/reference/secure/edge-firewall/web-application-firewall/custom-allowed-rule.mdx
- src/content/docs/pt-br/pages/changelog/anos-passados/anos-passados-changelog.mdx
- src/content/docs/pt-br/pages/changelog/changelog.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/secure/edge-firewall/web-application-firewall/waf-custom-allowed-rules.mdx
[EDU-5986] 
Review Changelog previous year and delete item.
Delete items in table - Custom Allowed Rules.
n/a.
[EDU-5986]: https://aziontech.atlassian.net/browse/EDU-5986?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-5986] Review Changelog previous year

- src/content/docs/en/pages/main-menu/reference/observe/real-time-events/real-time-events.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/observe/real-time-events/real-time-events.mdx
[EDU-5971]
Adjust value in Real-Time Events reference - Limits. PT/EN
n/a.
[EDU-5971]: https://aziontech.atlassian.net/browse/EDU-5971?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-5971] refactor: adjust value in Real-Time Events reference

- src/content/docs/pt-br/pages/changelog/changelog.mdx
- src/content/docs/pt-br/pages/menu-principal/release-notes/release-notes.mdx
[EDU-5980]
adjust term in PT - Changelog
n/a.
[EDU-5980]: https://aziontech.atlassian.net/browse/EDU-5980?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-5980] fix: adjust term in PT - Changelog

- src/content/docs/en/pages/guides/index.mdx
- src/content/docs/en/pages/guides/marketplace/templates/videoteca-static-cache.mdx
- src/content/docs/en/pages/main-menu/additional-resources/templates-and-integrations/understand-azion-templates.mdx
- src/content/docs/pt-br/pages/guias/guides.mdx
- src/content/docs/pt-br/pages/guias/marketplace/templates/videoteca-static-cache.mdx
- src/content/docs/pt-br/pages/menu-principal/recursos-adicionais/templates-e-integracoes/templates-visao-geral.mdx
Creates Static Cache + Videoteca Player template guide.
> [Edu-5536] Static Cache + Videoteca Player template

- src/content/docs/en/pages/main-menu/additional-resources/developer-tools/graphql-playground.mdx
- src/content/docs/pt-br/pages/menu-principal/recursos-adicionais/developer-tools/graphql-playground.mdx
[EDU-5976]
- Add new advanced Top Attacks query to GraphQL API Playground reference - EN/PT
https://github.com/aziontech/docs/pull/1434
[EDU-5976]: https://aziontech.atlassian.net/browse/EDU-5976?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-5976] refactor: update GraphQL API Playground reference

- src/content/docs/en/pages/devtools/cli/azion-cli/azion-overview/azion-overview.mdx
- src/content/docs/pt-br/pages/devtools/cli/azion-cli/azion-overview/azion-overview.mdx
> feat-Include-CLI-Windows-Instalation 

- src/content/docs/en/pages/main-menu/reference/build/edge-application/domains/domains.mdx
- src/content/docs/en/pages/main-menu/work-with-domains/configure-domains.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/build/edge-application/domains/domains.mdx
- src/content/docs/pt-br/pages/menu-principal/trabalhe-com-dominios/configurar-dominio.mdx
[EDU-5981]
add anchor to CNAME - Domains reference
n/a.
[EDU-5981]: https://aziontech.atlassian.net/browse/EDU-5981?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-5981] refactor: add anchor to CNAME - Domains reference

- src/content/docs/en/pages/guides/index.mdx
- src/content/docs/en/pages/guides/marketplace/templates/butter-cms.mdx
- src/content/docs/en/pages/main-menu/additional-resources/templates-and-integrations/understand-azion-templates.mdx
- src/content/docs/pt-br/pages/guias/guides.mdx
- src/content/docs/pt-br/pages/guias/marketplace/templates/butter-templates-collection.mdx
- src/content/docs/pt-br/pages/menu-principal/recursos-adicionais/templates-e-integracoes/templates-visao-geral.mdx
New ButterCMS guide, and also the respective pages for links and architecture to be reviewed.
> [EDU-5767] feat: new buttercms guide

- src/includes/snippets/InterfaceNote/en/snippet.mdx
- src/includes/snippets/InterfaceNote/pt/snippet.mdx
Amended the date to reflect the new RTM`s EOL.
> [EDU-6053]fix:new-RTM-EOL-date

- src/content/docs/en/pages/main-menu/reference/secure/edge-firewall/network-layer-protection/network-layer-protection.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/secure/edge-firewall/network-layer-protection/network-layer-protection.mdx
Added new sentence as per Rossa`s request.
> [EDU-6007] fix: insert-new-sentence

- src/content/docs/en/pages/main-menu/reference/build/edge-application/digital-certificates.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/build/edge-application/digital-certificates.mdx
[EDU-6059] 
- Update Digital Certificates reference to include new info. 
n/a.
[EDU-6059]: https://aziontech.atlassian.net/browse/EDU-6059?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-6059] refactor: update Digital Certificates reference

- src/content/docs/en/pages/main-menu/release-notes/release-notes.mdx
- src/content/docs/pt-br/pages/menu-principal/pricing/pricing.mdx
- src/content/docs/pt-br/pages/menu-principal/release-notes/release-notes.mdx
[EDU-6087]
add item to the Release Note page - Edge Storage Billing
n/a.
[EDU-6087]: https://aziontech.atlassian.net/browse/EDU-6087?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-6087] feature: add item to the Release Note page - Edge Storage Billing

- src/content/docs/en/pages/main-menu/reference/store/object-storage/index.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/store/edge-storage/index.mdx
Add a note to Edge Storage reference to clarify about S3 ops - EN/PT
n/a.
> [EDU-6120] refactor: add note to Edge Storage reference

- src/content/docs/en/pages/build-journey/edit-edge-app/edit-cache-settings/cache-settings.mdx
- src/content/docs/pt-br/pages/build-jornada/edite-edge-app/cache-settings.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/secure/edge-firewall/network-layer-protection/network-layer-protection.mdx
Reverts aziontech/docs#1471
Please note that @PedroMiolaSilva didn`t commit our proposed changes but resolved the conversations, hence me reverting the PR for review.
> Revert "[EDU-6114] AI documentation update - 2025-01-24 - tune cache settings"

- src/content/docs/en/pages/devtools/api-graphql/queries/queries.mdx
Source updated: https://www.azion.com/en/documentation/devtools/graphql-api/queries/
> [EDU-6112] AI documentation update - 2025-01-24 - queries

- src/content/docs/pt-br/pages/devtools/api-graphql/queries/queries-gql.mdx
[EDU-6112] 
Update and fix an example in the GraphQL API Queries file. 
https://github.com/aziontech/docs/pull/1466
[EDU-6112]: https://aziontech.atlassian.net/browse/EDU-6112?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-6112] AI documentation update - 2025-01-24 - queries (PT)

- src/content/docs/en/pages/main-menu/pricing/pricing.mdx
- src/content/docs/pt-br/pages/menu-principal/pricing/pricing.mdx
[EDU-6156]
Add Domains to the pricing page - EN/PT
n/a.
[EDU-6156]: https://aziontech.atlassian.net/browse/EDU-6156?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-6156] refactor: Add Domains to the pricing page - EN/PT

- src/content/docs/en/pages/guides/edge-dns/run-dig-command.mdx
- src/content/docs/pt-br/pages/guias/edge-dns/run-dig-command.mdx
Fixes indentation of a code block component.
> [no-issue] fix code block

- src/content/docs/en/pages/devtools/cli/azion-cli/config/azion-config-js.mdx
- src/content/docs/pt-br/pages/devtools/cli/azion-cli/configs/azion-config-js.mdx
Adjusts the language on a code block to avoid errors.
> [no-issue] Adjust language definition on code block

- src/content/docs/en/pages/main-menu/reference/observe/data-stream/data-stream.mdx
- src/content/docs/en/pages/observe-journey/data-stream/integrations/connector-elasticsearch.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/observe/data-streaming/data-streaming.mdx
- src/content/docs/pt-br/pages/observe-jornada/data-stream/integracoes/conector-elasticsearch.mdx
[EDU-4623]
Adjusting API Key field description for Elasticsearch endpoints:
- Data Stream reference.
- How-to guide.
n/a.
[EDU-4623]: https://aziontech.atlassian.net/browse/EDU-4623?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-4623] fix: adjusting API Key field description for Elasticsearch endpoints - Data Stream

- src/content/docs/en/pages/guides/index.mdx
- src/content/docs/en/pages/guides/marketplace/templates/edge-function-starter-kit.mdx
- src/content/docs/en/pages/main-menu/additional-resources/templates-and-integrations/understand-azion-templates.mdx
- src/content/docs/pt-br/pages/guias/guides.mdx
- src/content/docs/pt-br/pages/guias/marketplace/templates/edge-function-starter-kit.mdx
- src/content/docs/pt-br/pages/menu-principal/recursos-adicionais/templates-e-integracoes/templates-visao-geral.mdx
Adds the Edge Function Starter Kit template guide.
> [EDU-6180] Edge Function template guide

- src/content/docs/en/pages/main-menu/release-notes/release-notes.mdx
- src/content/docs/pt-br/pages/menu-principal/release-notes/release-notes.mdx
Adds the release note for the Edge Function Starter Kit template
> [EDU-6187] Add Edge Function Starter Kit template release note

- src/content/docs/en/pages/guides/index.mdx
- src/content/docs/en/pages/guides/marketplace/templates/langgraph-template.mdx
- src/content/docs/en/pages/main-menu/additional-resources/templates-and-integrations/understand-azion-templates.mdx
- src/content/docs/pt-br/pages/guias/guides.mdx
- src/content/docs/pt-br/pages/guias/marketplace/templates/langgraph-template.mdx
- src/content/docs/pt-br/pages/menu-principal/recursos-adicionais/templates-e-integracoes/templates-visao-geral.mdx
> [Edu-6159] langgraph template guide

- src/content/docs/en/pages/deploy-journey/advanced-config/run-scripts/run-scripts.mdx
- src/content/docs/en/pages/deploy-journey/advanced-config/uninstall/uninstall-node.mdx
- src/content/docs/en/pages/deploy-journey/configure-node/authorize-node/authorize-node.mdx
- src/content/docs/en/pages/deploy-journey/configure-node/bind-service/bind-service.mdx
- src/content/docs/en/pages/deploy-journey/configure-node/create-service/create-service.mdx
- src/content/docs/en/pages/deploy-journey/configure-node/provision-files/provision-file.mdx
- src/content/docs/en/pages/deploy-journey/configure-node/unbind-service/unbind-service.mdx
- src/content/docs/en/pages/deploy-journey/configure-node/work-with-variables/work-with-variables.mdx
- src/content/docs/pt-br/pages/deploy-jornada/avancado/desinstalar-node/desinstalar-node.mdx
- src/content/docs/pt-br/pages/deploy-jornada/avancado/rodar-scripts/rodar-scripts.mdx
- src/content/docs/pt-br/pages/deploy-jornada/configurar-node/autorizar-node/autorizar-node.mdx
- src/content/docs/pt-br/pages/deploy-jornada/configurar-node/criar-service/criar-service.mdx
- src/content/docs/pt-br/pages/deploy-jornada/configurar-node/desvincular-service/unbind-service.mdx
- src/content/docs/pt-br/pages/deploy-jornada/configurar-node/provisionar-arquivos/provisionar-arquivos.mdx
- src/content/docs/pt-br/pages/deploy-jornada/configurar-node/trabalhar-variaveis/trabalhar-com-variaveis.mdx
- src/content/docs/pt-br/pages/deploy-jornada/configurar-node/vincular-service/vincular-service.mdx
Removed rtm tabs from deploy guides
> [EDU-6018] Remove RTM tabs | Deploy

- src/content/docs/en/pages/main-menu/reference/observe/real-time-metrics/real-time-metrics.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/observe/real-time-metrics/real-time-metrics.mdx
[EDU-6150] [EDU-6037]
- Add new graphs info - Real-Time Metrics reference.
- Adjust wording.
Note: EN version uses Includes to pull information from the Help Center.
n/a.
[EDU-6150]: https://aziontech.atlassian.net/browse/EDU-6150?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[EDU-6037]: https://aziontech.atlassian.net/browse/EDU-6037?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-6150] [EDU-6037] refactor: add new graphs info - Real-Time Metrics reference

- src/content/docs/pt-br/pages/observe-jornada/data-stream/integracoes/conector-big-query.mdx
removes tabs from conector bigqueruy
> fix: Remove tab rtm conector big query

- src/content/docs/en/pages/guides/marketplace/templates/astro-boilerplate.mdx
- src/content/docs/en/pages/main-menu/additional-resources/templates-and-integrations/understand-azion-templates.mdx
- src/content/docs/pt-br/pages/guias/marketplace/templates/astro-boilerplate.mdx
- src/content/docs/pt-br/pages/menu-principal/recursos-adicionais/templates-e-integracoes/templates-visao-geral.mdx
Changed the astro boilerplate guide to match the newer guides.
> [EDU-6192 ]Refactor astro boilerplate  guide

- src/content/docs/en/pages/guides/edge-application/ea-request-lets-encrypt-certificates.mdx
- src/content/docs/en/pages/main-menu/reference/build/edge-application/digital-certificates.mdx
- src/content/docs/en/pages/main-menu/reference/secure/edge-firewall/digital-certificates.mdx
- src/content/docs/pt-br/pages/guias/edge-application/ea-requet-lets-encrypt-certificates.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/build/edge-application/digital-certificates.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/secure/edge-firewall/digital-certificates.mdx
[EDU-6288] 
- add note to Let's Encrypt-related documentation: references for Build and Secure; how-to guide.
n/a.
[EDU-6288]: https://aziontech.atlassian.net/browse/EDU-6288?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-6288] refactor: add note to Let's Encrypt-related documentation

- src/content/docs/en/pages/secure-journey/troubleshoot/edge-firewall-understand-metrics.mdx
remove deprecated youtube about waf metrics
> fix: remove deprecated youtube waf metrics

- src/content/docs/en/pages/main-menu/reference/secure/edge-firewall/web-application-firewall/waf-rule-sets.mdx
Remove deprecated youtube video regarding XSS attack
> fix: remove deprecated youtube video xss atack

- src/content/docs/en/pages/guides/marketplace/templates/nextjs-static-boilerplate.mdx
remove deprecated youtube video next js boilerplate
> fix: remove deprecated youtube video next js boilerplate

- src/content/docs/en/pages/main-menu/reference/secure/edge-firewall/network-layer-protection/network-list.mdx
Remove deprecated youtube video on network list
> fix: remove deprecated youtube video network list

- src/content/docs/pt-br/pages/guias/open-ticket/open-ticket.mdx
Fix youtube link on open tickets doc
> fix: update YouTube video link for open ticket guide

- src/content/docs/en/pages/devtools/azion-lib/usage/ai-client.mdx
- src/content/docs/pt-br/pages/devtools/azion-lib/usage/ai-client.mdx
Docs for the ai client module.
> [EDU-6232] Azion Lib | Ai client

- src/content/docs/en/pages/main-menu/reference/store/edge-sql/edge-sql.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/store/edge-sql/edge-sql.mdx
added link to list databases guide  in edge sql reference
> [EDU-6320] added link to list databases guide 

- src/content/docs/en/pages/guides/marketplace/templates/langgraph-template.mdx
- src/content/docs/pt-br/pages/guias/marketplace/templates/langgraph-template.mdx
Adds information about authentication configuration to LangGraph template guide.
> [EDU-6300] Update langgraph-template documentation to include auth

- src/content/docs/en/pages/main-menu/reference/observe/real-time-metrics/first-steps.mdx
> fix: youtube link on first step page of real time metrics

- src/content/docs/en/pages/guides/accounts/conditional-access-by-ip.mdx
- src/content/docs/pt-br/pages/guias/contas/conditional-access-by-ip.mdx
[EDU-6321]
Update fields and refine samples that appear in the guide.
n/a.
[EDU-6321]: https://aziontech.atlassian.net/browse/EDU-6321?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-6321] fix: adjust Account policies guide

- src/content/docs/en/pages/guides/graphql/query-data-stream-usage-data.mdx
- src/content/docs/en/pages/guides/graphql/query-tiered-cache-usage-data.mdx
- src/content/docs/en/pages/guides/index.mdx
- src/content/docs/pt-br/pages/guias/graphql/query-data-stream-usage-data.mdx
- src/content/docs/pt-br/pages/guias/graphql/query-tiered-cache-usage-data.mdx
- src/content/docs/pt-br/pages/guias/guides.mdx
- src/i18n/en/graphqlMenu.ts
- src/i18n/pt-br/graphqlMenu.ts
[EDU-6313] [EDU-6314] 
- Add new guides related to the Consumption dataset: how to query Tiered Cache and Data Stream usage data.
- Add links to the left menu.
- Add links to the Guides Page.
n/a.
[EDU-6313]: https://aziontech.atlassian.net/browse/EDU-6313?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[EDU-6314]: https://aziontech.atlassian.net/browse/EDU-6314?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-6313] [EDU-6314] feature: add new guides related to the Consumption dataset

- src/content/docs/en/pages/guides/marketplace/templates/qwik-boilerplate.mdx
- src/content/docs/en/pages/guides/marketplace/templates/qwik-minimal.mdx
- src/content/docs/pt-br/pages/guias/marketplace/templates/qwik-boilerplate.mdx
- src/content/docs/pt-br/pages/guias/marketplace/templates/qwik-minimal.mdx
> [EDU-6186] fix: deploy url for templates

- src/content/docs/en/pages/guides/index.mdx
- src/content/docs/en/pages/guides/marketplace/templates/edgesql-starter-kit.mdx
- src/content/docs/en/pages/main-menu/additional-resources/templates-and-integrations/understand-azion-templates.mdx
- src/content/docs/pt-br/pages/guias/guides.mdx
- src/content/docs/pt-br/pages/guias/marketplace/templates/edgesql-starter-kit.mdx
- src/content/docs/pt-br/pages/menu-principal/recursos-adicionais/templates-e-integracoes/templates-visao-geral.mdx
added edgesql starterkit template guides.
> [EDU-6320] feat: edgesql starter kit template guides

- src/content/docs/en/pages/guides/graphql/query-edge-application-usage-data.mdx
- src/content/docs/en/pages/guides/index.mdx
- src/content/docs/pt-br/pages/guias/graphql/query-edge-application-usage-data.mdx
- src/content/docs/pt-br/pages/guias/guides.mdx
- src/i18n/en/graphqlMenu.ts
- src/i18n/pt-br/graphqlMenu.ts
[EDU-6278]
- Add a new guide related to the Consumption dataset: query Edge Application usage data.
- Add links to menu and Guides page. 
n/a.
[EDU-6278]: https://aziontech.atlassian.net/browse/EDU-6278?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-6278] feature: add new guide related to Consumption dataset

- src/content/docs/en/pages/devtools/azion-lib/usage/application.mdx
- src/content/docs/en/pages/guides/marketplace/templates/edgesql-starter-kit.mdx
- src/content/docs/pt-br/pages/devtools/azion-lib/usage/ai-client.mdx
- src/content/docs/pt-br/pages/devtools/azion-lib/usage/application.mdx
- src/content/docs/pt-br/pages/guias/marketplace/templates/edgesql-starter-kit.mdx
[No-Issue]
- Adjusting language spelling in code samples: using Uppercase letters breaks the build.
- Adjusting {} in table.
- Adding missing "" for a link in a component.
n/a.
> [No-Issue] fix: adjusting language spelling in code samples

- src/content/docs/en/pages/main-menu/release-notes/release-notes.mdx
- src/content/docs/pt-br/pages/menu-principal/release-notes/release-notes.mdx
> [EDU-6339] Added new releases to release notes

- src/content/docs/en/pages/guides/marketplace/templates/edgesql-starter-kit.mdx
- src/content/docs/en/pages/guides/marketplace/templates/preact-javascript-boilerplate.mdx
- src/content/docs/en/pages/guides/marketplace/templates/preact-typescript-boilerplate.mdx
- src/content/docs/pt-br/pages/guias/marketplace/templates/edgesql-starter-kit.mdx
- src/content/docs/pt-br/pages/guias/marketplace/templates/preact-javascript-boilerplate.mdx
- src/content/docs/pt-br/pages/guias/marketplace/templates/preact-typescript-boilerplate.mdx
> [NO-ISSUE] fix: deploy url in new template guides

- src/content/docs/en/pages/devtools/api-graphql/features/consumption-fields.mdx
- src/content/docs/en/pages/guides/graphql/query-data-stream-usage-data.mdx
- src/content/docs/en/pages/guides/graphql/query-edge-application-usage-data.mdx
- src/content/docs/en/pages/guides/graphql/query-edge-functions-usage-data.mdx
- src/content/docs/en/pages/guides/graphql/query-image-processor-usage-data.mdx
- src/content/docs/en/pages/guides/graphql/query-tiered-cache-usage-data.mdx
- src/content/docs/en/pages/main-menu/release-notes/release-notes.mdx
- src/content/docs/pt-br/pages/devtools/api-graphql/recursos/consumption-campos.mdx
- src/content/docs/pt-br/pages/guias/graphql/query-data-stream-usage-data.mdx
- src/content/docs/pt-br/pages/guias/graphql/query-edge-application-usage-data.mdx
- src/content/docs/pt-br/pages/guias/graphql/query-edge-functions-usage-data.mdx
- src/content/docs/pt-br/pages/guias/graphql/query-image-processor-usage-data.mdx
- src/content/docs/pt-br/pages/guias/graphql/query-tiered-cache-usage-data.mdx
[EDU-6344]
Update TTL for Consumption GraphQL API dataset, EN/PT.
n/a.
[EDU-6344]: https://aziontech.atlassian.net/browse/EDU-6344?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-6344] refactor: update TTL for Consumption GraphQL API dataset

- src/content/docs/en/pages/devtools/api-graphql/first-steps/first-steps.mdx
- src/content/docs/en/pages/devtools/azion-edge-runtime/compatibility/frameworks.mdx
fix: delete youtube links from graphql and frameworks playlists on docs
> fix: delete youtube links from graphql and frameworks playlists on docs

- src/content/docs/en/pages/main-menu/reference/build/edge-application/edge-application.mdx
- src/content/docs/en/pages/main-menu/reference/secure/edge-firewall/edge-firewall.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/build/edge-application/edge-application.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/secure/edge-firewall/edge-firewall.mdx
- src/i18n/en/nav.ts
- src/i18n/pt-br/nav.ts
[EDU-6330]
Reorganizing the main left menu as demanded in the tasks and alignment calls.
n/a.
[EDU-6330]: https://aziontech.atlassian.net/browse/EDU-6330?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-6330] refactor: reorganizing main left menu

- src/content/docs/en/pages/main-menu/release-notes/release-notes.mdx
- src/content/docs/pt-br/pages/menu-principal/release-notes/release-notes.mdx
Added node js compatibility to release notes.
> [EDU-6324] added nodejs to release notes

- src/content/docs/en/pages/architectures/artificial-intelligence/ai-agent-copilot.mdx
- src/content/docs/pt-br/pages/arquiteturas/artificial-intelligence/ai-agent-copilot.mdx
- src/content/docs/pt-br/pages/menu-principal/release-notes/release-notes.mdx
> [EDU-6366] fixed broken links in docs

- src/content/docs/en/pages/main-menu/reference/build/edge-application/image-processor.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/build/edge-application/image-processor.mdx
https://aziontech.atlassian.net/browse/EDU-6342
> [EDU-6343] added limits table to image processor doc

- src/content/docs/en/pages/main-menu/reference/build/edge-application/rules-engine.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/build/edge-application/rules-engine-edge-app.mdx
Added rules engine rules limit.
> [EDU-6349] fix: added rules engine limit

- src/content/docs/en/pages/main-menu/reference/build/edge-application/image-processor.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/build/edge-application/image-processor.mdx
Moved limts to the end of the file
> [NO-ISSUE] fix: image processor limits position

- src/content/docs/en/pages/main-menu/reference/build/edge-application/real-time-purge.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/build/edge-application/real-time-purge.mdx
> [EDU-6384] fix: added aditional purge limits

- src/content/docs/en/pages/main-menu/reference/secure/edge-firewall/web-application-firewall/custom-allowed-rule.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/secure/edge-firewall/web-application-firewall/waf-custom-allowed-rules.mdx
Ajuste feito na doc do WAF Custom Allowed Rule para melhorar a identificação do conteúdo pelo Copilot.
> [EDU-6343] feat:new-waf-allowed-rule-content

- src/content/docs/en/pages/main-menu/reference/observe/real-time-metrics/historical-real-time-metrics/historical-real-time-metrics.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/observe/real-time-metrics/historico-real-time-metrics.mdx
> [EDU-6418] fix: removed product subscription message

- src/content/docs/en/pages/main-menu/manage-accounts/manage-account/billing-and-subscriptions.mdx
- src/content/docs/pt-br/pages/menu-principal/gerencie-contas/gerenciar-contas/faturamento-e-assinaturas.mdx
Removed emntions to subscriptions in mainmenu/manage-account
> [EDU-6417] fix: removed subscription mention in billing guide

- src/i18n/pt-br/nav.ts
https://aziontech.atlassian.net/browse/UXE-6947
* added missing index in navigation
https://aziontech.atlassian.net/browse/DX-153
> fix: added origin shield index in docs navigation

- src/content/docs/en/pages/guides/marketplace/templates/angular-boilerplate.mdx
- src/content/docs/en/pages/guides/marketplace/templates/astro-blog-template.mdx
- src/content/docs/en/pages/guides/marketplace/templates/astro-boilerplate.mdx
- src/content/docs/en/pages/guides/marketplace/templates/astro-ecommerce-collection.mdx
- src/content/docs/en/pages/guides/marketplace/templates/azion-starter-kit.mdx
- src/content/docs/en/pages/guides/marketplace/templates/bot-starter-kit.mdx
- src/content/docs/en/pages/guides/marketplace/templates/bot-with-firewall.mdx
- src/content/docs/en/pages/guides/marketplace/templates/bot-with-tor.mdx
- src/content/docs/en/pages/guides/marketplace/templates/butter-cms.mdx
- src/content/docs/en/pages/guides/marketplace/templates/clean-angular-sanity.mdx
- src/content/docs/en/pages/guides/marketplace/templates/clean-astro-sanity.mdx
- src/content/docs/en/pages/guides/marketplace/templates/clean-nuxt-sanity.mdx
- src/content/docs/en/pages/guides/marketplace/templates/cosmic-agency-website.mdx
- src/content/docs/en/pages/guides/marketplace/templates/cosmic-simple-astro-blog.mdx
- src/content/docs/en/pages/guides/marketplace/templates/cosmicjs-simple-next-blog-template.mdx
- src/content/docs/en/pages/guides/marketplace/templates/devscard.mdx
- src/content/docs/en/pages/guides/marketplace/templates/docusaurus-javascript-boilerplate.mdx
- src/content/docs/en/pages/guides/marketplace/templates/docusaurus-material-ui-template.mdx
- src/content/docs/en/pages/guides/marketplace/templates/docusaurus-typescript-boilerplate.mdx
- src/content/docs/en/pages/guides/marketplace/templates/dynamic-and-static-file-optimization.mdx
- src/content/docs/en/pages/guides/marketplace/templates/edge-application-proxy.mdx
- src/content/docs/en/pages/guides/marketplace/templates/edge-function-github-autopeploy.mdx
- src/content/docs/en/pages/guides/marketplace/templates/edge-function-starter-kit.mdx
- src/content/docs/en/pages/guides/marketplace/templates/edgesql-starter-kit.mdx
- src/content/docs/en/pages/guides/marketplace/templates/eleventy-ecommerce-collection.mdx
Removed subscription mentions from english template guides
> [EDU-6408] fix: removed subscription messages from template guides - EN - PART 1

- src/content/docs/en/pages/devtools/azion-edge-runtime/compatibility/frameworks.mdx
- src/content/docs/pt-br/pages/devtools/azion-edge-runtime/compatibilidade/frameworks.mdx
Added missing frameworks.
Ordered by alphabetical order.
> [EDU-6426] fix: added missing frameworks

- src/content/docs/en/pages/devtools/azion-edge-runtime/compatibility/node-polyfills/cells-node.mdx
- src/content/docs/pt-br/pages/devtools/azion-edge-runtime/compatibilidade/node-polyfills/node.mdx
Added node matrix as per PM request
> [EDU-6466] add node matrix url

- src/content/docs/en/pages/main-menu/manage-accounts/manage-profile/delete-account.mdx
- src/content/docs/pt-br/pages/menu-principal/gerencie-contas/gerenciar-perfis/deletar-conta.mdx
> [EDU-6487] fix: replaced rtm url

- src/content/docs/en/pages/devtools/azion-edge-runtime/compatibility/frameworks.mdx
- src/content/docs/pt-br/pages/devtools/azion-edge-runtime/compatibilidade/frameworks.mdx
- src/content/docs/pt-br/pages/guias/marketplace/templates/azion-starter-kit.mdx
- src/content/docs/pt-br/pages/guias/marketplace/templates/bot-with-tor.mdx
> [EDU-6492] fixed broken urls

- src/i18n/en/nav.ts
move edge ai reference menu to build
> move-edge-ai-reference-menu-to-build

- src/content/docs/en/pages/main-menu/release-notes/release-notes.mdx
- src/content/docs/pt-br/pages/menu-principal/release-notes/release-notes.mdx
> Update Edge AI documentation links in release notes

- src/content/docs/en/pages/main-menu/release-notes/release-notes.mdx
- src/content/docs/pt-br/pages/menu-principal/release-notes/release-notes.mdx
> [EDU-6400] add build and scale launch release notes

- src/content/docs/en/pages/main-menu/release-notes/release-notes.mdx
- src/content/docs/pt-br/pages/menu-principal/release-notes/release-notes.mdx
> [EDU-6400] devex release notes

- src/content/docs/en/pages/main-menu/release-notes/release-notes.mdx
Removed vector searche message.
> remove vector search message

- src/content/docs/en/pages/devtools/azion-edge-runtime/api-reference/edge-sql/edge-sql.mdx
- src/content/docs/en/pages/devtools/azion-edge-runtime/nextjs/2023-02-14-index.mdx
- src/content/docs/en/pages/devtools/cli/azion-cli/azion-overview/azion-overview.mdx
- src/content/docs/en/pages/devtools/cli/azion-cli/commands/init-build-deploy/azion-create-deploy-application.mdx
- src/content/docs/en/pages/devtools/cli/azion-cli/commands/link-project/link.mdx
Replaced in devtools english docs.
> [EDU-6484] fix: replaced azion edge platform in devtools -en

- src/content/docs/pt-br/pages/devtools/azion-edge-runtime/nextjs/nextjs.mdx
> [EDU-6490] remove azion edge -devtools pt

- src/content/docs/pt-br/pages/arquiteturas/orch/application-deliver-automation.mdx
- src/content/docs/pt-br/pages/arquiteturas/orch/infra-automation.mdx
- src/content/docs/pt-br/pages/build-jornada/desenvolva-com-azion/guias-frameworks/framework-vue.mdx
- src/content/docs/pt-br/pages/devtools/azion-edge-runtime/nextjs/nextjs.mdx
- src/content/docs/pt-br/pages/guias/create-button/create-button.mdx
- src/content/docs/pt-br/pages/guias/marketplace/templates/angular-boilerplate.mdx
- src/content/docs/pt-br/pages/guias/marketplace/templates/next-static-boilerplate.mdx
- src/content/docs/pt-br/pages/guias/marketplace/templates/vue-boilerplate.mdx
Replaced 'Azion Edge Platform -ptbr docs'
> [EDU-6503] removed azion edge plaform pt-br docs

- src/content/docs/pt-br/pages/guias/marketplace/templates/azion-starter-kit.mdx
- src/content/docs/pt-br/pages/guias/marketplace/templates/videoteca-static-cache.mdx
> [EDU-6481] replaced azion edge platform

- src/content/docs/en/pages/devtools/azion-edge-runtime/compatibility/node-polyfills/cells-node.mdx
- src/content/docs/pt-br/pages/devtools/azion-edge-runtime/compatibilidade/node-polyfills/node.mdx
> [EDU-6509] fix duplicated text

- src/content/docs/pt-br/pages/menu-principal/gerencie-contas/criar-conta.mdx
- src/content/docs/pt-br/pages/menu-principal/recursos-adicionais/templates-e-integracoes/templates-visao-geral.mdx
> [EDU-6508] replaced azion edge platform main menu extras

- src/content/docs/en/pages/architectures/api-gateways/api-gateways-security.mdx
- src/content/docs/en/pages/architectures/bot-management/bot-management-architecture.mdx
- src/content/docs/en/pages/architectures/compliance/compliance-architecture.mdx
- src/content/docs/en/pages/architectures/edge-application/application-modernization.mdx
- src/content/docs/en/pages/architectures/edge-application/content-delivery.mdx
- src/content/docs/en/pages/architectures/edge-application/image-processing.mdx
- src/content/docs/en/pages/architectures/edge-application/microservices.mdx
- src/content/docs/en/pages/architectures/edge-application/serverless-apps.mdx
- src/content/docs/en/pages/architectures/edge-enhanced/edge-enhanced.mdx
- src/content/docs/en/pages/architectures/edge-firewall/online-fraud-prevention.mdx
- src/content/docs/en/pages/architectures/edge-firewall/waap-architecture.mdx
- src/content/docs/en/pages/architectures/edge-native/edge-native-apps.mdx
- src/content/docs/en/pages/architectures/jamstack/jamstack.mdx
- src/content/docs/en/pages/architectures/live-streaming/live-streaming-delivery-hls.mdx
- src/content/docs/en/pages/architectures/orch/application-deliver-operation.mdx
- src/content/docs/en/pages/architectures/orch/infra-automation.mdx
- src/content/docs/en/pages/architectures/security-automation/security-automation.mdx
- src/content/docs/en/pages/architectures/security-modernization/security-modernization-with-edge-computing.mdx
> [EDU-6504]fix:replaced azion edge platform in architectures

- src/content/docs/en/pages/build-journey/develop-with-azion/frameworks/framework-angular.mdx
- src/content/docs/en/pages/build-journey/develop-with-azion/frameworks/framework-astro.mdx
- src/content/docs/en/pages/build-journey/develop-with-azion/frameworks/framework-docusaurus.mdx
- src/content/docs/en/pages/build-journey/develop-with-azion/frameworks/framework-eleventy.mdx
- src/content/docs/en/pages/build-journey/develop-with-azion/frameworks/framework-gatsby.mdx
- src/content/docs/en/pages/build-journey/develop-with-azion/frameworks/framework-hexo.mdx
- src/content/docs/en/pages/build-journey/develop-with-azion/frameworks/framework-hono.mdx
- src/content/docs/en/pages/build-journey/develop-with-azion/frameworks/framework-hugo.mdx
- src/content/docs/en/pages/build-journey/develop-with-azion/frameworks/framework-jekyll.mdx
- src/content/docs/en/pages/build-journey/develop-with-azion/frameworks/framework-next.mdx
- src/content/docs/en/pages/build-journey/develop-with-azion/frameworks/framework-overview.mdx
- src/content/docs/en/pages/build-journey/develop-with-azion/frameworks/framework-react.mdx
- src/content/docs/en/pages/build-journey/develop-with-azion/frameworks/framework-svelte.mdx
- src/content/docs/en/pages/build-journey/develop-with-azion/frameworks/framework-vite.mdx
- src/content/docs/en/pages/build-journey/develop-with-azion/frameworks/framework-vue.mdx
- src/content/docs/en/pages/build-journey/develop-with-azion/toolsCli/overview.mdx
- src/content/docs/en/pages/build-journey/overview/overview.mdx
> [EDU-6477]fix: replaced azion edge platform in build journey

- src/content/docs/en/pages/main-menu/additional-resources/templates-and-integrations/overview.mdx
- src/content/docs/en/pages/main-menu/additional-resources/templates-and-integrations/understand-azion-integrations.mdx
- src/content/docs/en/pages/main-menu/additional-resources/templates-and-integrations/understand-azion-templates.mdx
- src/content/docs/en/pages/main-menu/additional-resources/templates-and-integrations/use-a-template.mdx
- src/content/docs/en/pages/main-menu/get-started/azion-platform-overview.mdx
- src/content/docs/en/pages/main-menu/get-started/start-with-a-template.mdx
- src/content/docs/en/pages/main-menu/manage-accounts/create-accountd.mdx
- src/content/docs/en/pages/main-menu/release-notes/release-notes.mdx
Replaced Azion Edge Platform with Azion Web Platform.
> [EDU-6512] fix: Replaced Azion Edge Platform in Main Menu docs

- src/content/docs/pt-br/pages/build-jornada/desenvolva-com-azion/devtools/tools-cli.mdx
- src/content/docs/pt-br/pages/build-jornada/desenvolva-com-azion/guias-frameworks/framework-angular.mdx
- src/content/docs/pt-br/pages/build-jornada/desenvolva-com-azion/guias-frameworks/framework-astro.mdx
- src/content/docs/pt-br/pages/build-jornada/desenvolva-com-azion/guias-frameworks/framework-docusaurus.mdx
- src/content/docs/pt-br/pages/build-jornada/desenvolva-com-azion/guias-frameworks/framework-eleventy.mdx
- src/content/docs/pt-br/pages/build-jornada/desenvolva-com-azion/guias-frameworks/framework-gatsby.mdx
- src/content/docs/pt-br/pages/build-jornada/desenvolva-com-azion/guias-frameworks/framework-hexo.mdx
- src/content/docs/pt-br/pages/build-jornada/desenvolva-com-azion/guias-frameworks/framework-hono.mdx
- src/content/docs/pt-br/pages/build-jornada/desenvolva-com-azion/guias-frameworks/framework-hugo.mdx
- src/content/docs/pt-br/pages/build-jornada/desenvolva-com-azion/guias-frameworks/framework-jekyll.mdx
- src/content/docs/pt-br/pages/build-jornada/desenvolva-com-azion/guias-frameworks/framework-next.mdx
- src/content/docs/pt-br/pages/build-jornada/desenvolva-com-azion/guias-frameworks/framework-overview.mdx
- src/content/docs/pt-br/pages/build-jornada/desenvolva-com-azion/guias-frameworks/framework-react.mdx
- src/content/docs/pt-br/pages/build-jornada/desenvolva-com-azion/guias-frameworks/framework-svelte.mdx
- src/content/docs/pt-br/pages/build-jornada/desenvolva-com-azion/guias-frameworks/framework-vite.mdx
- src/content/docs/pt-br/pages/build-jornada/desenvolva-com-azion/guias-frameworks/framework-vue.mdx
- src/content/docs/pt-br/pages/build-jornada/visao-geral/visao-geral.mdx
> [EDU-6517]fix: replaced plataforma de edge da azion - build jornada

- src/content/docs/en/homes/build-home.mdx
- src/content/docs/en/homes/home-docs.mdx
- src/content/docs/pt-br/homes/doc-home.mdx
> [EDU-6515] fix: replace azion edge in homes

- src/includes/docs_help_center/en/build-application/build/build-from-scratch/build-with-edge-application/index.md
- src/includes/docs_help_center/en/import-an-existing-project/import-an-existing-project/index.md
- src/includes/docs_help_center/en/welcome/getting-started/index.md
> [EDU-6516] fix: replaced azion edge platform in help center

- src/content/docs/pt-br/pages/arquiteturas/api-gateways/api-gateways-security.mdx
- src/content/docs/pt-br/pages/arquiteturas/bot-management/bot-management-arquitetura.mdx
- src/content/docs/pt-br/pages/arquiteturas/compliance/compliance-architecture.mdx
- src/content/docs/pt-br/pages/arquiteturas/edge-application/application-modernization.mdx
- src/content/docs/pt-br/pages/arquiteturas/edge-application/image-processor.mdx
- src/content/docs/pt-br/pages/arquiteturas/edge-application/serverless-apps.mdx
- src/content/docs/pt-br/pages/arquiteturas/edge-firewall/prevencao-fraude-online.mdx
- src/content/docs/pt-br/pages/arquiteturas/edge-firewall/waap-arquitetura.mdx
- src/content/docs/pt-br/pages/arquiteturas/edge-native/edge-native-apps.mdx
- src/content/docs/pt-br/pages/arquiteturas/live-streaming-delivery/live-streming-delivery-com-hls.mdx
- src/content/docs/pt-br/pages/arquiteturas/security-automation/security-automation.mdx
- src/content/docs/pt-br/pages/arquiteturas/security-modernization/security-modernization-com-edge-computing.mdx
> [EDU-6504] fix: replaced plataforma de edge da azion - arquiteturas

- src/content/docs/pt-br/pages/guias/edge-application/ea-enforce-hls.mdx
- src/content/docs/pt-br/pages/guias/edge-functions/WebAssembly.mdx
- src/content/docs/pt-br/pages/guias/edge-functions/serverless-functions.mdx
- src/content/docs/pt-br/pages/guias/importar-do-github/azion-github-app.mdx
- src/content/docs/pt-br/pages/guias/importar-do-github/importar-do-github.mdx
- src/content/docs/pt-br/pages/guias/waf/configurar-allowed-rules.mdx
> [EDU-6518] fix: replaced plataforma de edge da azion - guias

- src/content/docs/pt-br/pages/menu-principal/referencia/build/edge-application/edge-functions-edge-app.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/contas/faturamento.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/glossario/glossario.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/marketplace/marketplace-seller-guide.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/marketplace/marketplace.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/secure/edge-dns/dnssec.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/secure/edge-firewall/edge-functions-for-edge-firewall/edge-functions-firewall.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/store/edge-storage/index.mdx
> [EDU-6520] fix: replaced plataforma de edge da azion - referencia

- src/content/docs/pt-br/pages/menu-principal/gerencie-contas/gerenciar-perfis/personal-token.mdx
- src/content/docs/pt-br/pages/menu-principal/ponto-de-partida/comecar-com-um-template.mdx
- src/content/docs/pt-br/pages/menu-principal/ponto-de-partida/visao-geral-da-azion.mdx
- src/content/docs/pt-br/pages/menu-principal/recursos-adicionais/templates-e-integracoes/integracoes-visao-geral.mdx
- src/content/docs/pt-br/pages/menu-principal/recursos-adicionais/templates-e-integracoes/overview.mdx
- src/content/docs/pt-br/pages/menu-principal/recursos-adicionais/templates-e-integracoes/templates-visao-geral.mdx
- src/content/docs/pt-br/pages/menu-principal/recursos-adicionais/templates-e-integracoes/usar-um-template-via-rtm.mdx
- src/content/docs/pt-br/pages/menu-principal/release-notes/release-notes.mdx
> [EDU-6528] fix: Replaced plataforma de edge da azion - paginas menu principal

- src/content/docs/pt-br/pages/devtools/azion-edge-runtime/api-reference/edge-sql/edge-sql.mdx
- src/content/docs/pt-br/pages/devtools/cli/azion-cli/azion-overview/azion-overview.mdx
- src/content/docs/pt-br/pages/devtools/cli/azion-cli/comandos/init-build-deploy/azion-create-deploy-application.mdx
- src/content/docs/pt-br/pages/secure-jornada/automatizar/edge-functions-apis.mdx
- src/content/docs/pt-br/pages/secure-jornada/proteja-dns.mdx
> [EDU-6533] fix: replace plataforma de edge da azion -extras

- src/content/docs/en/pages/devtools/azion-edge-runtime/compatibility/node-polyfills/cells-node.mdx
- src/content/docs/pt-br/pages/devtools/azion-edge-runtime/compatibilidade/node-polyfills/node.mdx
> [EDU-6526]fix: removed node compatibility matrix

- src/content/docs/pt-br/pages/arquiteturas/edge-native/edge-native-apps.mdx
- src/content/docs/pt-br/pages/devtools/azion-lib/usage/ai-client.mdx
- src/content/docs/pt-br/pages/devtools/cli/azion-cli/comandos/unlink/unlink.mdx
- src/content/docs/pt-br/pages/devtools/console-kit/console-kit.mdx
- src/content/docs/pt-br/pages/menu-principal/compliance/pci-dss.mdx
- src/content/docs/pt-br/pages/menu-principal/compliance/soc.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/build/edge-application/digital-certificates.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/contas/faturamento.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/secure/edge-firewall/digital-certificates.mdx
- src/content/docs/pt-br/pages/observe-jornada/visao-geral.mdx
- src/content/docs/pt-br/pages/secure-jornada/firewall-configuracoes-avancadas/gerenciar-bots.mdx
> [EDU-6534] fix: replaced plataforma de edge computing docs

- src/content/docs/en/pages/main-menu/release-notes/release-notes.mdx
- src/content/docs/pt-br/pages/menu-principal/release-notes/release-notes.mdx
> [EDU-6400] fix: release notes  fixes

- src/content/docs/en/pages/main-menu/reference/secure/edge-firewall/digital-certificates.mdx
- src/content/docs/en/pages/main-menu/release-notes/release-notes.mdx
- src/content/docs/en/pages/main-menu/work-with-domains/create-certificate.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/secure/edge-firewall/digital-certificates.mdx
- src/content/docs/pt-br/pages/menu-principal/release-notes/release-notes.mdx
- src/content/docs/pt-br/pages/menu-principal/trabalhe-com-dominios/criar-certificado.mdx
New content for a feature for Secure.
> launch:new-feature-in-digital-certificates

- cicd/massive-redirect/en.json
- cicd/massive-redirect/pt-br.json
- src/content/docs/en/pages/main-menu/reference/edge-ai/edge-ai-reference.mdx
- src/content/docs/en/pages/main-menu/reference/edge-ai/models.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/edge-ai/modelos.mdx
> fix: replace 4xx links and add redirects

- src/content/docs/en/pages/devtools/azion-lib/usage/ai-client.mdx
- src/content/docs/en/pages/devtools/cli/azion-cli/commands/unlink/unlink.mdx
- src/content/docs/en/pages/devtools/console-kit/console-kit.mdx
- src/content/docs/en/pages/guides/edge-dns/run-dig-command.mdx
- src/content/docs/en/pages/guides/getting-to-know-azion-console/getting-to-know-azion-console.mdx
- src/content/docs/en/pages/guides/paywall-edge-function-jwt/paywall-edge-function-jwt.mdx
- src/content/docs/en/pages/main-menu/compliance/pci-dss.mdx
- src/content/docs/en/pages/main-menu/compliance/soc-2.mdx
- src/content/docs/en/pages/main-menu/reference/build/edge-application/digital-certificates.mdx
- src/content/docs/en/pages/main-menu/reference/secure/edge-dns/dnssec/dnssec.mdx
- src/content/docs/en/pages/main-menu/reference/secure/edge-firewall/digital-certificates.mdx
- src/content/docs/en/pages/main-menu/reference/secure/edge-firewall/edge-functions-for-edge-firewall/edge-functions-firewall.mdx
- src/content/docs/en/pages/main-menu/reference/store/object-storage/index.mdx
- src/content/docs/en/pages/observe-journey/overview.mdx
- src/content/docs/en/pages/secure-journey/automate/edge-functions-apis.mdx
- src/content/docs/en/pages/secure-journey/firewall-advanced-configurations/manage-bots.mdx
- src/content/docs/pt-br/pages/guias/conhecendo-o-azion-console/conhecendo-o-azion-console.mdx
- src/content/docs/pt-br/pages/guias/hosting-edge-site/hosting-edge-site.mdx
- src/content/docs/pt-br/pages/guias/marketplace/templates/image-optimization.mdx
- src/content/docs/pt-br/pages/guias/marketplace/templates/static-cache.mdx
- src/includes/docs_help_center/en/marketplace/about-marketplace/index.md
- src/includes/docs_help_center/en/welcome/getting-started/index.md
> [EDU-6538] fix: replaced edge computing platform

- src/content/docs/en/pages/devtools/azion-edge-runtime/compatibility/frameworks.mdx
- src/content/docs/en/pages/guides/import-from-github/import-from-github.mdx
- src/content/docs/pt-br/pages/devtools/azion-edge-runtime/compatibilidade/frameworks.mdx
- src/content/docs/pt-br/pages/guias/importar-do-github/importar-do-github.mdx
- Removed mode setting from the import from github docs
- Removed mode mentions in the frameworks doc.
> [EDU-6549] fix: removed compute x deliver

- src/content/docs/en/pages/main-menu/manage-accounts/manage-profile/delete-account.mdx
- src/content/docs/pt-br/pages/menu-principal/gerencie-contas/gerenciar-perfis/deletar-conta.mdx
> [EDU-6487] fix: removed app disclaimer

- src/content/docs/en/pages/build-journey/develop-with-azion/lang-js/lang-javascript.mdx
- src/content/docs/en/pages/devtools/azion-edge-runtime/compatibility/frameworks.mdx
- src/content/docs/en/pages/devtools/azion-edge-runtime/runtime-apis/functions-objects/2023-04-07-index.mdx
- src/content/docs/en/pages/devtools/azion-lib/usage/unenv.mdx
> [EDU-6551] fix: replace edge runtime

- src/content/docs/en/pages/main-menu/reference/secure/edge-firewall/azion-bot-manager.mdx
O link levava para uma pág em PT dentro do doc em EN
> fix-wrong-link

- src/content/docs/en/pages/main-menu/release-notes/release-notes.mdx
- src/content/docs/pt-br/pages/menu-principal/release-notes/release-notes.mdx
> [EDU-6548] Added apllication mode release note

- src/content/docs/en/pages/devtools/azion-edge-runtime/compatibility/node-polyfills/fs.mdx
> [NO-ISSUE]fix: fs file desc

- src/content/docs/en/pages/main-menu/manage-accounts/manage-account/mfa.mdx
- src/content/docs/pt-br/pages/menu-principal/gerencie-contas/gerenciar-contas/mfa.mdx
> [EDU-6568] fix: mfa setup guides

- src/content/docs/en/pages/main-menu/before-begin/get-help.mdx
- src/content/docs/en/pages/main-menu/get-started/azion-platform-overview.mdx
- src/content/docs/pt-br/pages/menu-principal/antes-de-comecar/obter-ajuda.mdx
- src/content/docs/pt-br/pages/menu-principal/ponto-de-partida/visao-geral-da-azion.mdx
> [EDU-6573] fix: improvements to get-help and overview

- src/content/docs/en/homes/home-docs.mdx
- src/content/docs/pt-br/homes/doc-home.mdx
> [EDU-6575] fix: new docs homepage

- src/i18n/pt-br/nav.ts
> fix: amend pricing translation

- src/content/docs/en/pages/agreements/azion-plans/azion-plans.mdx
- src/content/docs/pt-br/pages/contratos/azion-plans/azion-plans.mdx
> azion-plans

- src/content/docs/en/homes/home-docs.mdx
- src/content/docs/pt-br/homes/doc-home.mdx
-  Moved astro
- Changed titles to template name
- Added url to  template landing page
> [EDU-6596] fix: minor docs homepage adjustments

- src/content/docs/pt-br/pages/devtools/azion-edge-runtime/compatibilidade/frameworks/template-showcase/astro/astro-clean-sanity.mdx
> [NO-ISSUE] fix: component buttons

- src/content/docs/en/homes/home-docs.mdx
- src/content/docs/pt-br/homes/doc-home.mdx
> [EDU-6595] fix: added gatsby  template landing in docs homes

- src/content/docs/en/pages/guides/marketplace/templates/clean-astro-sanity.mdx
- src/content/docs/en/pages/main-menu/reference/glossary/glossary.mdx
- src/content/docs/pt-br/homes/doc-home.mdx
- src/content/docs/pt-br/pages/devtools/azion-edge-runtime/compatibilidade/frameworks/astro.mdx
- src/content/docs/pt-br/pages/devtools/azion-edge-runtime/compatibilidade/frameworks/gatsby.mdx
- src/content/docs/pt-br/pages/guias/guides.mdx
- src/content/docs/pt-br/pages/menu-principal/trabalhe-com-dominios/migrar-ns.mdx
> [NO-ISSUE]fixed description astr- sanity guide

- src/content/docs/en/pages/main-menu/reference/secure/edge-firewall/ddos-protection/ddos-protection.mdx
> fix: typo on button name

- src/content/docs/pt-br/pages/menu-principal/referencia/build/edge-application/domains/domains.mdx
> [NO-ISSUE] fix: removed extra char

- src/content/docs/en/pages/main-menu/reference/secure/edge-firewall/web-application-firewall/custom-allowed-rule.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/secure/edge-firewall/web-application-firewall/waf-custom-allowed-rules.mdx
Remove rule 1206 as it is no longer supported.
> [EDU-6510] Remove waf rule 1206

- src/content/docs/en/pages/devtools/azion-edge-runtime/api-reference/metadata/metadata.mdx
- src/content/docs/pt-br/pages/devtools/azion-edge-runtime/api-reference/metadata/metadata.mdx
> [EDU-6605] fix: added fingerprint metadata

- src/content/docs/en/homes/home-docs.mdx
- src/content/docs/pt-br/homes/doc-home.mdx
- src/content/docs/pt-br/pages/devtools/azion-edge-runtime/compatibilidade/frameworks/angular.mdx
- src/content/docs/pt-br/pages/devtools/azion-edge-runtime/compatibilidade/frameworks/astro.mdx
> [EDU-6596] fix: added new urls

- src/content/docs/en/pages/main-menu/reference/build/edge-application/rules-engine.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/build/edge-application/rules-engine-edge-app.mdx
> [EDU-6641] fix: added response tag to capture match groups

- src/content/docs/en/pages/devtools/azion-edge-runtime/api-reference/cache_api.mdx
- src/content/docs/en/pages/main-menu/release-notes/release-notes.mdx
- src/content/docs/pt-br/pages/devtools/azion-edge-runtime/api-reference/cache_api.mdx
- src/content/docs/pt-br/pages/menu-principal/release-notes/release-notes.mdx
- src/i18n/en/runtimeMenu.ts
- src/i18n/pt-br/runtimeMenu.ts
> [EDU-6588] [PMK-9565] feat: add cache API docs

- src/content/docs/en/pages/guides/edge-application/ea-request-lets-encrypt-certificates.mdx
- src/content/docs/pt-br/pages/guias/edge-application/ea-requet-lets-encrypt-certificates.mdx
> [edu-6634] fix: updated phrasing

- src/content/docs/en/pages/main-menu/reference/build/edge-application/edge-caching.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/build/edge-application/edge-caching.mdx
> [EDU-66040] edge cache add stale cache info

- src/content/docs/en/pages/devtools/azion-edge-runtime/api-reference/cache_api.mdx
- src/content/docs/pt-br/pages/devtools/azion-edge-runtime/api-reference/cache_api.mdx
> [NO-ISSUE] removed url

- src/content/docs/en/pages/agreements/savings-plan/savings-plan-10-7-2025.mdx
- src/content/docs/en/pages/agreements/savings-plan/savings-plan.mdx
- src/content/docs/pt-br/pages/contratos/savings-plan/savings-plan-10-7-2025.mdx
- src/content/docs/pt-br/pages/contratos/savings-plan/savings-plan.mdx
> [EDU-6632] updated terms

- src/content/docs/en/pages/agreements/inventive-credits/incentive-credits.mdx
- src/content/docs/en/pages/agreements/savings-plan/savings-plan.mdx
- src/content/docs/pt-br/pages/contratos/creditos-incentivo/creditos-incentivo.mdx
- src/content/docs/pt-br/pages/contratos/savings-plan/savings-plan.mdx
> [NO-ISSUE] fix: indent and duplicated title

- src/content/docs/en/pages/main-menu/release-notes/release-notes.mdx
- src/content/docs/pt-br/pages/menu-principal/release-notes/release-notes.mdx
> launch-release-notes

- src/content/docs/en/pages/main-menu/reference/secure/edge-firewall/web-application-firewall/custom-allowed-rule.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/secure/edge-firewall/web-application-firewall/waf-custom-allowed-rules.mdx
> [EDU-6626] fixed itens in custom allowed rules page

- cicd/massive-redirect/en.json
- cicd/massive-redirect/pt-br.json
- src/content/docs/en/documentation/products/guides/build/browserless-edge-functions.mdx
- src/content/docs/en/documentation/products/guides/build/file-upload-edge-functions.mdx
- src/content/docs/en/documentation/products/guides/build/resend-email-edge-functions.mdx
- src/content/docs/en/documentation/products/guides/build/restful-tasks-api-edge-functions.mdx
- src/content/docs/en/documentation/products/guides/build/stripe-webhooks-edge-functions.mdx
- src/content/docs/en/pages/guides/index.mdx
- src/content/docs/pt-br/documentation/products/guides/build/browserless-edge-functions.mdx
- src/content/docs/pt-br/documentation/products/guides/build/file-upload-edge-functions.mdx
- src/content/docs/pt-br/documentation/products/guides/build/resend-email-edge-functions.mdx
- src/content/docs/pt-br/documentation/products/guides/build/restful-tasks-api-edge-functions.mdx
- src/content/docs/pt-br/documentation/products/guides/build/stripe-webhooks-edge-functions.mdx
- src/content/docs/pt-br/pages/devtools/azion-edge-runtime/compatibilidade/frameworks/nextjs.mdx
- src/content/docs/pt-br/pages/guias/guides.mdx
- src/content/docs/pt-br/pages/guias/marketplace/templates/next-pages-middleware.mdx
> [EDU-6698] fixed invalid urls

- src/content/docs/en/pages/main-menu/reference/secure/edge-firewall/azion-bot-manager.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/secure/edge-firewall/azion-bot-manager.mdx
Ajustes conforme solicitação do Furno
> fix:adjust-documentation

- src/content/docs/en/pages/main-menu/reference/build/edge-application/error-responses.mdx
- src/content/docs/en/pages/main-menu/reference/secure/custom-pages/custom-pages.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/build/edge-application/error-responses.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/secure/custom-pages/custom-pages.mdx
> [EDU-6697] API V4 | CUSTOM PAGES REFERENCE

- src/content/docs/en/pages/build-journey/edit-edge-app/edit-cache-settings/cache-settings.mdx
- src/content/docs/pt-br/pages/build-jornada/edite-edge-app/cache-settings.mdx
Update Cache Settings Documentation - Migration Console/API v4
> [EDU-6673] update cache settings docs

- src/content/docs/en/pages/main-menu/reference/secure/api-v4-migration.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/secure/api-v4-migration.mdx
> [EDU-6696] API V4 |  MIGRATION REFERENCE

- src/content/docs/en/pages/main-menu/reference/build/edge-application/edge-application.mdx
- src/content/docs/en/pages/main-menu/reference/build/edge-application/v3/edge-application-v3.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/build/edge-application/edge-application.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/build/edge-application/v3/edge-application-v3.mdx
> [EDU-6681] API V4 - update edge app reference

- src/content/docs/en/pages/main-menu/reference/glossary/glossary.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/glossario/glossario.mdx
> fix-glossary

- src/content/docs/en/pages/main-menu/reference/secure/api-v4-migration.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/secure/api-v4-migration.mdx
> fix: updated what happens to my origins secttion

- src/content/docs/en/pages/store-journey/storage/create-bucket.mdx
- src/content/docs/en/pages/store-journey/storage/download-object.mdx
- src/content/docs/en/pages/store-journey/storage/update-bucket.mdx
- src/content/docs/en/pages/store-journey/storage/upload-object.mdx
- src/content/docs/en/pages/store-journey/storage/use-bucket-as-origin.mdx
- src/content/docs/pt-br/pages/store-jornada/storage/atualizar-bucket.mdx
- src/content/docs/pt-br/pages/store-jornada/storage/criar-bucket.mdx
- src/content/docs/pt-br/pages/store-jornada/storage/upload-objeto.mdx
- src/content/docs/pt-br/pages/store-jornada/storage/usar-bucket-como-origem.mdx
> [EDU-6689] API V4 Store journey

- src/content/docs/en/pages/changelog/previous-years/previous-years-changelog.mdx
- src/content/docs/pt-br/pages/changelog/anos-passados/anos-passados-changelog.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/build/edge-application/domains/domains.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/build/edge-application/edge-application.mdx
> [NO-ISSUE] fix broken urls

- src/content/docs/en/pages/agreements/tos/12-august-2025/12-august-2025.mdx
- src/content/docs/pt-br/pages/contratos/tos/12-august-2025/terms-of-service.mdx
> amends-tos

- src/content/docs/pt-br/pages/menu-principal/referencia/build/edge-application/main-settings.mdx
> [NO-ISSUE]fix: broken main settings page

- src/content/docs/pt-br/pages/contratos/privacy-policy/controlador-operador.mdx
- src/content/docs/pt-br/pages/contratos/privacy-policy/index.mdx
- src/content/docs/pt-br/pages/contratos/privacy-policy/operador-operador.mdx
> launch-anpd-clauses

- src/content/docs/en/homes/build-home.mdx
- src/content/docs/en/pages/architectures/edge-application/application-modernization.mdx
- src/content/docs/en/pages/build-journey/advanced-configurations/multiple-origins.mdx
- src/content/docs/en/pages/build-journey/overview/overview.mdx
- src/content/docs/en/pages/changelog/previous-years/previous-years-changelog.mdx
- src/content/docs/en/pages/devtools/cli/azion-cli/commands/update/update.mdx
- src/content/docs/en/pages/main-menu/reference/build/edge-application/first-steps.mdx
- src/content/docs/en/pages/main-menu/reference/build/edge-application/origins.mdx
- src/content/docs/en/pages/main-menu/reference/build/edge-application/v3/edge-application-v3.mdx
- src/content/docs/pt-br/homes/build-home.mdx
- src/content/docs/pt-br/pages/build-jornada/configuracoes-avancadas/multiple-origins.mdx
- src/content/docs/pt-br/pages/build-jornada/edite-edge-app/error-responses.mdx
- src/content/docs/pt-br/pages/build-jornada/edite-edge-app/origins.mdx
- src/content/docs/pt-br/pages/build-jornada/visao-geral/visao-geral.mdx
- src/content/docs/pt-br/pages/changelog/anos-passados/anos-passados-changelog.mdx
- src/content/docs/pt-br/pages/devtools/cli/azion-cli/comandos/update/update.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/build/edge-application/edge-app-primeiros-passos.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/build/edge-application/origins.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/build/edge-application/v3/edge-application-v3.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/observe/data-streaming/data-streaming.mdx
- src/i18n/en/nav.ts
- src/i18n/pt-br/nav.ts
> [EDU-6738] fix: load balancer url cleanup and broken  link replacement

- src/content/docs/pt-br/pages/guias/edge-application/ea-configure-ports/custom-ports.mdx
> fixed duplicated step

- src/content/docs/en/pages/agreements/tos/29-august-2025/terms-of-service-29-august-2025.mdx
- src/content/docs/en/pages/agreements/tos/terms-of-service.mdx
- src/content/docs/pt-br/pages/contratos/tos/29-august-2025/terms-of-service-29-august-2025.mdx
- src/content/docs/pt-br/pages/contratos/tos/index.mdx
> amend-compute-time

- src/content/docs/en/pages/observe-journey/analyze-logs.mdx
- src/content/docs/en/pages/observe-journey/data-stream/advanced-configurations/select-variables.mdx
- src/content/docs/en/pages/observe-journey/data-stream/edit-stream/configure-main-settings.mdx
- src/content/docs/en/pages/observe-journey/data-stream/integrations/connector-azion-edge-storage.mdx
- src/content/docs/en/pages/observe-journey/monitor-applications.mdx
- src/content/docs/en/pages/observe-journey/overview.mdx
- src/content/docs/en/pages/observe-journey/real-time-events/analyze-logs/investigate-requests.mdx
- src/content/docs/en/pages/observe-journey/real-time-events/analyze-logs/understand-logs.mdx
- src/content/docs/en/pages/observe-journey/real-time-events/integrations/grafana-plugin-custom-table.mdx
- src/content/docs/en/pages/observe-journey/real-time-events/integrations/integrate-grafana.mdx
- src/content/docs/en/pages/observe-journey/real-time-metrics/integrations/grafana-plugin-prebuilt-dash.mdx
- src/content/docs/en/pages/observe-journey/real-time-metrics/monitor-metrics/analyze-metrics.mdx
- src/content/docs/en/pages/observe-journey/stream-data.mdx
- src/content/docs/pt-br/pages/observe-jornada/analisar-logs.mdx
- src/content/docs/pt-br/pages/observe-jornada/data-stream/configuracoes-avancadas/selecionar-variaveis.mdx
- src/content/docs/pt-br/pages/observe-jornada/data-stream/editar-stream/configure-main-settings.mdx
- src/content/docs/pt-br/pages/observe-jornada/data-stream/integracoes/connector-azion-edge-storage.mdx
- src/content/docs/pt-br/pages/observe-jornada/monitorar-aplicacoes.mdx
- src/content/docs/pt-br/pages/observe-jornada/real-time-events/analise-logs/entenda-logs.mdx
- src/content/docs/pt-br/pages/observe-jornada/real-time-events/analise-logs/investigue-requisicoes.mdx
- src/content/docs/pt-br/pages/observe-jornada/real-time-events/integracoes/integrar-grafana.mdx
- src/content/docs/pt-br/pages/observe-jornada/real-time-metrics/integracoes/grafana-plugin-dash-pre-config.mdx
- src/content/docs/pt-br/pages/observe-jornada/real-time-metrics/monitorar-metricas/adicionar-filtros.mdx
- src/content/docs/pt-br/pages/observe-jornada/real-time-metrics/monitorar-metricas/analisar-metricas.mdx
- src/content/docs/pt-br/pages/observe-jornada/transmitir-dados.mdx
- src/content/docs/pt-br/pages/observe-jornada/visao-geral.mdx
> [EDU-6795] updated product names in observe journey

- cicd/massive-redirect/en.json
- cicd/massive-redirect/pt-br.json
> [EDU-6805] added redirects

- src/content/docs/en/pages/main-menu/reference/ai-inference/edge-ai-reference.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/ai-inference/edge-ai-reference.mdx
> [EDU-6824] minor fixes ai inference

- src/content/docs/en/pages/devtools/mcp/mcp-configuration.mdx
- src/content/docs/en/pages/devtools/mcp/mcp-examples.mdx
- src/content/docs/en/pages/devtools/mcp/mcp-overview.mdx
- src/content/docs/en/pages/devtools/mcp/mcp-troubleshooting.mdx
- src/content/docs/pt-br/pages/devtools/mcp/mcp-configuracao.mdx
- src/content/docs/pt-br/pages/devtools/mcp/mcp-exemplos.mdx
- src/content/docs/pt-br/pages/devtools/mcp/mcp-overview.mdx
- src/content/docs/pt-br/pages/devtools/mcp/mcp-solucao-de-problemas.mdx
- Add MCP documentation in devtools section (EN and PT-BR)
- Include overview, configuration, examples, and troubleshooting guides
- Document support for Claude, Cursor, Windsurf, and other AI assistants
> [EDU-6837] [AI-153] feat(docs): add MCP documentation

- src/content/docs/en/pages/main-menu/release-notes/release-notes.mdx
- src/content/docs/pt-br/pages/menu-principal/release-notes/release-notes.mdx
> new-product-names

- src/content/docs/en/pages/build-journey/develop-with-azion/lang-js/lang-javascript.mdx
- src/content/docs/en/pages/build-journey/troubleshooting/understanding-metrics.mdx
- src/content/docs/en/pages/main-menu/reference/build/edge-application/domains/mtls.mdx
- src/content/docs/en/pages/main-menu/reference/observe/real-time-metrics/real-time-metrics.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/build/edge-application/domains/mtls.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/build/edge-application/edge-application.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/deploy/edge-orchestrator/edge-orchestrator.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/deploy/edge-orchestrator/edge-services.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/observe/data-streaming/data-streaming.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/observe/real-time-events/real-time-events.mdx
> fix: typos

- src/content/docs/en/pages/guides/index.mdx
Changing product's names on index page at guides (EN)
> update: nomes guides en index page

- src/content/docs/en/pages/guides/edge-functions/edge-functions-examples/browserless-edge-functions.mdx
> fix: browserless-edge-functions-file-en

- src/content/docs/pt-br/pages/menu-principal/referencia/build/edge-application/v3/main-settings-v3.mdx
> fix-change-snippet-to-ptbr

- cicd/massive-redirect/pt-br.json
- src/content/docs/pt-br/pages/guias/edge-firewall/atualizar-edge-firewall.mdx
- src/content/docs/pt-br/pages/guias/edge-firewall/edge-firewall.mdx
- src/content/docs/pt-br/pages/guias/edge-functions/edge-functions-examples/browserless-edge-functions.mdx
- src/content/docs/pt-br/pages/guias/edge-functions/edge-functions-examples/file-upload-edge-functions.mdx
- src/content/docs/pt-br/pages/guias/edge-functions/edge-functions-examples/resend-email-edge-functions.mdx
- src/content/docs/pt-br/pages/guias/edge-functions/edge-functions-examples/stripe-webhooks-edge-functions.mdx
- src/content/docs/pt-br/pages/guias/edge-storage/use-s3-protocol/index.mdx
- src/content/docs/pt-br/pages/guias/marketplace/integrations/paywall-edge-function-jwt.mdx
- src/content/docs/pt-br/pages/guias/marketplace/templates/edge-function-github-autodeploy.mdx
- src/content/docs/pt-br/pages/guias/marketplace/templates/edge-function-starter-kit.mdx
- src/content/docs/pt-br/pages/guias/marketplace/templates/qstash-scheduler.mdx
> update permalinks nomes produtos guias pt-br
