- README.md
In the link Contributing guide, the previous URL was broken and led to a 404 error. 
This commit replaces the broken URL with the correct one, ensuring that 
contributors can easily access the guide.
> fix: removed broken URL and added correct URL

- src/content/docs/en/pages/products/edge-application/rules-engine.mdx
- src/content/docs/pt-br/pages/produtos/edge-application/rules-engine/index.mdx
Added the following variables (unlisted in UI but accepted by the code):
- remote_port
- server_addr
- server_port
- tcpinfo_rtt
[EDU-2471]: https://aziontech.atlassian.net/browse/EDU-2471?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-2471] Add RE missing variables

- src/content/docs/en/pages/api-graphql/features/features.mdx
- src/content/docs/pt-br/pages/api-graphql/recursos/index.mdx
[EDU-2677]
* Added info on data storage + data beginning for the activityHistoryEvents dataset on Real-Time Events GQL.
[EDU-2677]: https://aziontech.atlassian.net/browse/EDU-2677?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-2677] add-activity-history-gql-ttl-date

- src/content/docs/en/pages/products/edge-firewall/web-application-firewall/custom-allowed-rule.mdx
Related issue: [EDU-2676](https://aziontech.atlassian.net/browse/EDU-2676)
Changes:
* Introducing the WAF Custom Allowed Rules video made by Learning Experience team.
[EDU-2676]: https://aziontech.atlassian.net/browse/EDU-2676?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> EDU-2676-EN-Add-learning-video-to-WAF-Custom-Allowed-Rules

- src/content/docs/pt-br/pages/produtos/edge-firewall/web-application-firewall/custom-allowed-rule/index.mdx
Tarefa relacionada: [EDU-2676](https://aziontech.atlassian.net/browse/EDU-2676)
Alterações:
* Introdução do vídeo sobre WAF Custom Allowed Rules feito pelo time de Learning.
[EDU-2676]: https://aziontech.atlassian.net/browse/EDU-2676?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> EDU-2676-PT-Add-learning-video-to-WAF-Custom-Allowed-Rules

- .github/CONTRIBUTING.md
* Added code owners @ on GitHub.
* Added info for code owners review and possible reasons leading to a PR rejection.
[EDU-2635]: https://aziontech.atlassian.net/browse/EDU-2635?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> contributions reject

- src/content/docs/pt-br/pages/devtools/api-graphql/primeiros-passos/primeiros-passo-gql.mdx
Related issue:
[EDU-3227] Fix broken youtube link PT doc GraphQL
Changes:
- Update link to youtube video on PT doc GraphQL
[EDU-3227]: https://aziontech.atlassian.net/browse/EDU-3227?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-3227] fix: update link youtube pt

- src/content/docs/en/pages/main-menu/reference/build/edge-application/edge-caching.mdx
- src/content/docs/en/pages/main-menu/reference/build/edge-application/real-time-purge.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/secure/edge-firewall/edge-firewall.mdx
- Removed cache key format information from RTP
- Added cache key section to edge caching page
[EDU-2448]: https://aziontech.atlassian.net/browse/EDU-2448?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-2448] refactor: cache keys into edge caching

- src/content/docs/en/pages/main-menu/reference/observe/real-time-metrics/real-time-metrics.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/observe/real-time-metrics/real-time-metrics.mdx
* Removed `Preview` tag from Real-Time Metrics reference as it's now in GA.
[EDU-3281]: https://aziontech.atlassian.net/browse/EDU-3281?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-3281] refactor: remove preview tag metrics

- src/content/docs/en/pages/devtools/azion-edge-runtime/compatibility/frameworks.mdx
- src/content/docs/pt-br/pages/devtools/azion-edge-runtime/compatibilidade/frameworks.mdx
Related issue:
[EDU-3549 ](https://aziontech.atlassian.net/browse/EDU-3549)
Changes
- Replace link to Vulcan.config.js file from GitHub to azion docs
> refactor: replace link from github to azion docs

- src/content/docs/en/pages/guides/edge-functions-firewall/index.mdx
- src/content/docs/pt-br/pages/guias/edge-functions-firewall/index.mdx
[EDU-3650](https://aziontech.atlassian.net/browse/EDU-3650)
Changes
- Remove mentions to initiator type (edge functions)
[EDU-3650]: https://aziontech.atlassian.net/browse/EDU-3650?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-3650]refactor: remove initiator type from guides

- src/content/docs/en/pages/main-menu/reference/build/edge-application/main-settings.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/build/edge-application/main-settings.mdx
Changes
- fix: Removed the "Experimental" badge from the HTTP/3 support section in the "main-settings.mdx" file. This change reflects the fact that HTTP/3 support is no longer experimental and is now a GA feature.
> fix-update-badge

- src/content/docs/en/pages/secure-journey/edit-zone/add-records.mdx
- src/content/docs/en/pages/secure-journey/intelligent-dns-advanced-configurations/add-lets-encrypt-txt-record.mdx
* Added guide explaining how to add a TXT record in Intelligent DNS if you have a Let's Encrypt certificate generated from outside Azion.
* Fixed a letter in another guide.
[EDU-3692]: https://aziontech.atlassian.net/browse/EDU-3692?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-3692] feat: add let's encrypt txt record

- src/content/docs/en/pages/devtools/cli/azion-cli-alpha/list/list.mdx
- src/content/docs/pt-br/pages/devtools/cli/azion-cli-alpha/list/list.mdx
Related issue:
[EDU-4097](https://aziontech.atlassian.net/browse/EDU-4097)
Changes:
Place all create commands inside a parent file for the list command. Each resource had its own page. Now, the page will be based on the CRUDL command.
The content was not altered, only moved.
I avoided using ### because it was uncomfortable to the eye... nor nice.
[EDU-4097]: https://aziontech.atlassian.net/browse/EDU-4097?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-4097] add cli list command

- src/content/docs/en/pages/architectures/live-streaming/live-streaming-delivery-hls.mdx
- src/content/docs/en/pages/guides/edge-application/ea-enforce-hls.mdx
- src/content/docs/en/pages/guides/index.mdx
- src/content/docs/en/pages/main-menu/reference/build/edge-application/rules-engine.mdx
- src/content/docs/pt-br/pages/arquiteturas/live-streaming-delivery/live-streming-delivery-com-hls.mdx
- src/content/docs/pt-br/pages/guias/edge-application/ea-enforce-hls.mdx
- src/content/docs/pt-br/pages/guias/guides.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/build/edge-application/rules-engine-edge-app.mdx
[EDU-4448]
- Add enforce HLS caching guide.
- Refactor Live Streaming arch and link to guide.
- Add the link to the guides page.
- Add button to Rules Engine reference.
n/a.
[EDU-4448]: https://aziontech.atlassian.net/browse/EDU-4448?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-4448] feat: enforce HLS caching guide

- src/content/docs/en/pages/main-menu/reference/secure/edge-firewall/web-application-firewall/web-application-firewall.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/secure/edge-firewall/web-application-firewall/web-application-firewall.mdx
[EDU-4463] 
- Add options to the Match Zone table in WAF reference, including examples and Match on* field.
n/a.
[EDU-4463]: https://aziontech.atlassian.net/browse/EDU-4463?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-4463] refactor: add options to Match Zone table

- src/content/docs/en/pages/guides/index.mdx
- src/content/docs/en/pages/guides/marketplace/templates/vitepress-javascript-boilerplate.mdx
- src/content/docs/en/pages/main-menu/additional-resources/templates-and-integrations/understand-azion-templates.mdx
- src/content/docs/pt-br/pages/guias/guides.mdx
- src/content/docs/pt-br/pages/guias/marketplace/templates/vitepress-javascript-boilerplate.mdx
- src/content/docs/pt-br/pages/menu-principal/recursos-adicionais/templates-e-integracoes/templates-visao-geral.mdx
[EDU-4903]
- Add Vitepress JavaScript Boilerplate guide. EN-PT.
- Add links to the Guides page and the Templates reference.
n/a.
[EDU-4903]: https://aziontech.atlassian.net/browse/EDU-4903?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-4903] feature: add Vitepress JavaScript Boilerplate guide

- src/content/docs/en/pages/main-menu/release-notes/release-notes.mdx
- src/content/docs/pt-br/pages/menu-principal/release-notes/release-notes.mdx
[EDU-4911] 
- Add item to Release Notes: VitePress templates launch.
n/a.
[EDU-4911]: https://aziontech.atlassian.net/browse/EDU-4911?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-4911] feature: add VitePress templates launch to Release Notes

- src/content/docs/en/pages/guides/marketplace/templates/docusaurus-typescript-boilerplate.mdx
- src/content/docs/pt-br/pages/guias/marketplace/templates/docusaurus-typescript-boilerplate.mdx
[EDU-4925]
- Add Docusaurus TypeScript Boilerplate guide (EN-PT).
https://github.com/aziontech/docs/pull/1106
[EDU-4925]: https://aziontech.atlassian.net/browse/EDU-4925?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-4925] feature: add Docusaurus TypeScript Boilerplate guide

- src/content/docs/en/pages/guides/index.mdx
- src/content/docs/en/pages/guides/marketplace/templates/docusaurus-javascript-boilerplate.mdx
- src/content/docs/en/pages/main-menu/additional-resources/templates-and-integrations/understand-azion-templates.mdx
- src/content/docs/pt-br/pages/guias/guides.mdx
- src/content/docs/pt-br/pages/guias/marketplace/templates/docusaurus-javascript-boilerplate.mdx
- src/content/docs/pt-br/pages/menu-principal/recursos-adicionais/templates-e-integracoes/templates-visao-geral.mdx
[EDU-4900]
- add Docusaurus JavaScript Boilerplate guide (EN-PT).
- Add links to the Guides page and Templates reference (EN-PT / JavaScript-TypeScript)
https://github.com/aziontech/docs/pull/1107
[EDU-4900]: https://aziontech.atlassian.net/browse/EDU-4900?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-4900] feature: add Docusaurus JavaScript Boilerplate guide

- src/content/docs/pt-br/pages/menu-principal/referencia/build/edge-application/rules-engine-edge-app.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/secure/edge-firewall/rules-engine-edge-firewall.mdx
[EDU-2917]
- Review and refine the Rules Engine for Edge Firewall reference in PT, including adjusting tables, adding examples, and reorganizing h2/h3.
- Minor improvements on the Rules Engine for Edge Application reference to align both files.
https://github.com/aziontech/docs/pull/1097
[EDU-2917]: https://aziontech.atlassian.net/browse/EDU-2917?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-2917] refactor: PT - review and refine Rules Engine for Edge Firewall reference

- src/content/docs/en/pages/main-menu/additional-resources/templates-and-integrations/understand-azion-templates.mdx
- src/content/docs/pt-br/pages/menu-principal/release-notes/release-notes.mdx
[No-issue]
- Fix broken URLs to the Docusaurus Material template guide: Templates reference (EN) and Release Notes (PT)
n/a.
> [No-issue] fix: broken urls to Docusaurus Material template guide

- src/content/docs/en/pages/guides/account-lockout-policy/logs-account-lockout-policy.mdx
- src/content/docs/en/pages/guides/account-lockout-policy/unlock-user-account-lockout-policy.mdx
- src/content/docs/pt-br/pages/guias/account-lockout-policy/logs-account-lockout-policy.mdx
- src/content/docs/pt-br/pages/guias/account-lockout-policy/unlock-user-account-lockout-policy.mdx
[EDU-5185]
- Update endpoint URL in the Lockout Policy guides: Unlock and Logs.
n/a.
[EDU-5185]: https://aziontech.atlassian.net/browse/EDU-5185?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-5185] fix: update endpoint URL in Lockout Policy guides

- src/content/docs/en/pages/devtools/azion-edge-runtime/overview/overview.mdx
- src/content/docs/pt-br/pages/devtools/azion-edge-runtime/visao-geral/visao-geral-runtime.mdx
Remove Jamstack and Frameworks paragraphs on Azion Runtime Overview
> [EDU-5220] fix: remove frameworks section from runtime overview

- src/content/docs/en/pages/build-journey/develop-with-azion/frameworks/framework-overview.mdx
- src/content/docs/pt-br/pages/build-jornada/desenvolva-com-azion/guias-frameworks/framework-overview.mdx
Remove Vulcan/Bundler dedicated paragraphs from framework specific overview.
> [EDU-5216] fix: remove bundler paragraph from framework specific overview

- src/content/docs/en/pages/guides/graphql/connected-users-dataset.mdx
- src/content/docs/en/pages/main-menu/release-notes/release-notes.mdx
- src/content/docs/pt-br/pages/guias/graphql/connected-users-dataset.mdx
- src/content/docs/pt-br/pages/menu-principal/release-notes/release-notes.mdx
[EDU-5288]
- Add an item to the Release Notes page, related to the `Connected Users dataset` launching. 
n/a.
[EDU-5288]: https://aziontech.atlassian.net/browse/EDU-5288?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-5288] feature: add item to Release Notes - Connected Users dataset

- src/content/docs/pt-br/pages/guias/marketplace/integrations/ab-testing-marketplace.mdx
[No-issue] 
- Fix a typo in the A/B Testing guide, PT.
n/a.
> [No-issue] fix: typo in A/B Testing guide

- src/content/docs/en/pages/guides/index.mdx
- src/content/docs/en/pages/guides/marketplace/templates/astro-ecommerce-collection.mdx
- src/content/docs/en/pages/main-menu/additional-resources/templates-and-integrations/understand-azion-templates.mdx
- src/content/docs/pt-br/pages/guias/guides.mdx
- src/content/docs/pt-br/pages/guias/marketplace/templates/astro-ecommerce-collection.mdx
- src/content/docs/pt-br/pages/menu-principal/recursos-adicionais/templates-e-integracoes/templates-visao-geral.mdx
Adds the Astro E-commerce Templates guide, with general guidance and buttons to deploy the three available templates:
- Astro Audiophile
- Astro Ecommerce
- Astro Quickstore
> [EDU-5388] Add E-commerce Astro Templates guide

- src/content/docs/en/pages/devtools/api-graphql/features/events-fields.mdx
- src/content/docs/en/pages/devtools/api-graphql/features/metrics-fields.mdx
- src/content/docs/en/pages/main-menu/reference/observe/data-stream/data-stream.mdx
- src/content/docs/en/pages/main-menu/reference/observe/real-time-events/real-time-events.mdx
- src/content/docs/pt-br/pages/devtools/api-graphql/recursos/events-campos.mdx
- src/content/docs/pt-br/pages/devtools/api-graphql/recursos/metrics-campos.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/observe/data-streaming/data-streaming.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/observe/real-time-events/real-time-events.mdx
[EDU-5020] 
Adjust time-related metrics in Observe Docs:
- Real-Time Events GraphQL API Fields
- Real-Time Events Reference.
- Real-Time Metrics GraphQL API Fields
- Data Stream Reference
n/a.
[EDU-5020]: https://aziontech.atlassian.net/browse/EDU-5020?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-5020] fix: adjust time-related metrics in Observe Docs

- src/content/docs/en/pages/devtools/cli/azion-cli/commands/link-project/link.mdx
- src/content/docs/pt-br/pages/devtools/cli/azion-cli/comandos/link-project/link.mdx
Updates `link` command reference to better explain the purpose of the command, match the actual interactions with the CLI and improve user understanding and experience.
> [EDU-5527] improve link command guide

- src/content/docs/en/pages/devtools/api-graphql/features/events-fields.mdx
- src/content/docs/en/pages/main-menu/reference/observe/data-stream/data-stream.mdx
- src/content/docs/en/pages/main-menu/reference/observe/real-time-events/real-time-events.mdx
- src/content/docs/pt-br/pages/devtools/api-graphql/recursos/events-campos.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/observe/data-streaming/data-streaming.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/observe/real-time-events/real-time-events.mdx
[no-issue]
adjust tcpInfoRtt metric description in Observe docs
n/a.
> [no-issue] fix: adjust tcpInfoRtt metric description in Observe docs

- src/content/docs/en/pages/devtools/azion-edge-runtime/compatibility/frameworks.mdx
- src/content/docs/pt-br/pages/devtools/azion-edge-runtime/compatibilidade/frameworks.mdx
Removes the Vite entry from the Frameworks Compatibility page, as we cover Vite in VitePress and Vue/Vite templates and not on its own.
> [no-issue] - Remove Vite entry from frameworks compatibility

- src/content/docs/en/pages/devtools/azion-edge-runtime/compatibility/cells-node.mdx
- src/content/docs/pt-br/pages/devtools/azion-edge-runtime/compatibilidade/node.mdx
Updates the page on Node.js APIs compatibility in accordance with the actual support through Cells and Bundler.
Adds code samples for the polyfills.
> [EDU-5621] Update Node Compatibility reference

- src/content/docs/en/pages/guides/marketplace/integrations/add-request-id.mdx
- src/content/docs/en/pages/guides/marketplace/integrations/bot-manager-lite.mdx
- src/content/docs/en/pages/guides/marketplace/integrations/hcaptcha.mdx
- src/content/docs/en/pages/guides/marketplace/integrations/ipqs.mdx
- src/content/docs/en/pages/guides/marketplace/integrations/jwt.mdx
- src/content/docs/en/pages/guides/marketplace/integrations/limit-payload.mdx
- src/content/docs/en/pages/guides/marketplace/integrations/radware-bot-manager.mdx
- src/content/docs/en/pages/guides/marketplace/integrations/rate-limiting-with-penalty.mdx
- src/content/docs/en/pages/guides/marketplace/integrations/recaptcha.mdx
- src/content/docs/en/pages/guides/marketplace/integrations/request-data-into-header.mdx
- src/content/docs/en/pages/guides/marketplace/integrations/scheduled-blocking.mdx
- src/content/docs/en/pages/guides/marketplace/integrations/secure-token.mdx
- src/content/docs/en/pages/guides/marketplace/integrations/send-event-endpoint.mdx
- src/content/docs/en/pages/guides/marketplace/integrations/waiting-room.mdx
- src/content/docs/pt-br/pages/guias/marketplace/integrations/add-request-id.mdx
- src/content/docs/pt-br/pages/guias/marketplace/integrations/bot-manager-lite.mdx
- src/content/docs/pt-br/pages/guias/marketplace/integrations/hcaptcha.mdx
- src/content/docs/pt-br/pages/guias/marketplace/integrations/ipqs.mdx
- src/content/docs/pt-br/pages/guias/marketplace/integrations/jwt.mdx
- src/content/docs/pt-br/pages/guias/marketplace/integrations/limit-payload.mdx
- src/content/docs/pt-br/pages/guias/marketplace/integrations/radware-bot-manager.mdx
- src/content/docs/pt-br/pages/guias/marketplace/integrations/rate-limit-with-penalty.mdx
- src/content/docs/pt-br/pages/guias/marketplace/integrations/recaptcha.mdx
- src/content/docs/pt-br/pages/guias/marketplace/integrations/request-data-headers.mdx
- src/content/docs/pt-br/pages/guias/marketplace/integrations/scheduled-blocking.mdx
- src/content/docs/pt-br/pages/guias/marketplace/integrations/secure-token.mdx
- src/content/docs/pt-br/pages/guias/marketplace/integrations/send-event-endpoint.mdx
- src/content/docs/pt-br/pages/guias/marketplace/integrations/waiting-room.mdx
Changes steps to protect a domain with an Edge Firewall integration on guides
> [EDU-5876] Refactor: update Edge Firewall integrations guides

- src/content/docs/en/pages/main-menu/reference/build/edge-application/digital-certificates.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/build/edge-application/digital-certificates.mdx
[EDU-5982] [EDU-5984] 
update Digital Certificates reference adding info about the key.
n/a.
[EDU-5982]: https://aziontech.atlassian.net/browse/EDU-5982?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[EDU-5984]: https://aziontech.atlassian.net/browse/EDU-5984?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-5982] [EDU-5984] refactor: update Digital Certificates reference

- src/content/docs/en/pages/main-menu/reference/build/edge-application/load-balancer.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/build/edge-application/load-balancer.mdx
[EDU-5978] 
update Load Balancer reference, adding info about Balancing method
n/a.
[EDU-5978]: https://aziontech.atlassian.net/browse/EDU-5978?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-5978] refactor: update Load Balancer reference

- src/content/docs/en/pages/guides/graphql/query-bot-manager-data.mdx
- src/content/docs/en/pages/guides/marketplace/templates/videoteca-static-cache.mdx
- src/content/docs/pt-br/pages/guias/marketplace/templates/videoteca-static-cache.mdx
[EDU-6085]
Fix broken links in Docs:
- Query Bot Manager data guide.
- Videoteca Static Cache template guide.
n/a.
[EDU-6085]: https://aziontech.atlassian.net/browse/EDU-6085?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-6085] fix: broken links in Docs

- src/content/docs/en/pages/build-journey/edit-edge-app/edit-cache-settings/cache-settings.mdx
AI Comment: The documentation was enhanced to include details on the 'UPDATING' status and its role in serving stale content. It also clarifies that 'Stale Cache' is enabled by default and suggests using the Azion API to create rules for handling stale cache scenarios. These additions address user questions about serving the most recent cache when the origin server is down or while the cache is being renewed.
Código: 19080
> [EDU-6114] AI documentation update - 2025-01-24 - tune cache settings

- src/content/docs/en/pages/guides/marketplace/integrations/javascript-tag-js-tag.mdx
- src/content/docs/pt-br/pages/guias/marketplace/integrations/javascript-tag-js-tag.mdx
[EDU-6287]
- Update link to resource included in the JS Tag how-to guide.
- The link wasn't identified in any file other than the guide.
n/a.
[EDU-6287]: https://aziontech.atlassian.net/browse/EDU-6287?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-6287] refactor: update link to resource - JS Tag guide

- src/content/docs/en/pages/guides/edge-application/ea-fs-image-processor.mdx
- src/content/docs/en/pages/main-menu/reference/build/edge-application/image-processor.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/build/edge-application/image-processor-primeiros-passos.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/build/edge-application/image-processor.mdx
Adds note about placement of the ims= query string parameter for Image Processor.
> [EDU-6261] Add note about ims parameter placement

- src/content/docs/en/homes/dev-tools.mdx
- src/content/docs/pt-br/homes/dev-tools.mdx
devtools pages are now in alphabetical order.
> [EDU-6318] fix: devtools homepage order

- src/content/docs/en/homes/home-docs.mdx
- src/content/docs/pt-br/homes/doc-home.mdx
Added missing devtools and reordered by name
> [EDU-6318] fix:Order devtools by name in docs home

- src/content/docs/en/pages/main-menu/reference/build/edge-application/rules-engine.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/build/edge-application/rules-engine-edge-app.mdx
Added valid chars to the add header section in rules engine doc
> [EDU-6328] fix: Added valid chars to the add header section in rules engine doc

- src/content/docs/en/pages/main-menu/release-notes/release-notes.mdx
- src/content/docs/pt-br/pages/menu-principal/release-notes/release-notes.mdx
[PMK-9313] 
add new item to the Release Notes page to communicate the Consumption dataset launch.
n/a.
[PMK-9313]: https://aziontech.atlassian.net/browse/PMK-9313?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [PMK-9313] feature: add Consumption dataset to the Release Notes page

- src/content/docs/en/pages/devtools/api-graphql/first-steps/first-steps.mdx
- src/content/docs/en/pages/guides/graphql/bot-manager-breakdown-data.mdx
- src/content/docs/en/pages/guides/graphql/connected-users-dataset.mdx
- src/content/docs/en/pages/guides/graphql/query-bot-manager-data.mdx
- src/content/docs/en/pages/guides/graphql/query-edge-functions-usage-data.mdx
- src/content/docs/en/pages/guides/graphql/query-image-processor-usage-data.mdx
- src/content/docs/en/pages/guides/graphql/query-top-attacks.mdx
- src/content/docs/en/pages/guides/graphql/query-top-ips.mdx
- src/content/docs/en/pages/observe-journey/real-time-events/analyze-logs/investigate-requests.mdx
- src/content/docs/pt-br/pages/deploy-jornada/configurar-node/vincular-service/vincular-service.mdx
- src/content/docs/pt-br/pages/deploy-jornada/deploy-service/deploy-service.mdx
- src/content/docs/pt-br/pages/devtools/api-graphql/primeiros-passos/primeiros-passo-gql.mdx
- src/content/docs/pt-br/pages/guias/graphql/bot-manager-breakdown-data.mdx
- src/content/docs/pt-br/pages/guias/graphql/connected-users-dataset.mdx
- src/content/docs/pt-br/pages/guias/graphql/query-bot-manager-data.mdx
- src/content/docs/pt-br/pages/guias/graphql/query-edge-functions-usage-data.mdx
- src/content/docs/pt-br/pages/guias/graphql/query-image-processor-usage-data.mdx
- src/content/docs/pt-br/pages/guias/graphql/query-top-attacks.mdx
- src/content/docs/pt-br/pages/guias/graphql/query-top-ips.mdx
- src/content/docs/pt-br/pages/observe-jornada/real-time-events/analise-logs/investigue-requisicoes.mdx
[EDU-6336]
- Update URLs for the GraphiQL Playground.
- Delete a couple of RTM mentions.
n/a.
[EDU-6336]: https://aziontech.atlassian.net/browse/EDU-6336?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-6336] fix: update URLs for the GraphiQL Playground

- src/content/docs/pt-br/pages/devtools/azion-lib/usage/application.mdx
The azion lib application module in pt-br had an incorrct permalink.
> [NO-ISSUE] fix: removed -client from permalink

- src/content/docs/en/pages/guides/marketplace/integrations/javascript-tag-js-tag.mdx
- src/content/docs/pt-br/pages/guias/marketplace/integrations/javascript-tag-js-tag.mdx
Guys, as per Artur`s request, I updated the link where needed:
_O link para o client fingerprint do Bot Manager mudou para [https://assets.azion.com/global/bot-manager/client-fingerprint/azfp-1.0.0.min.js](https://www.google.com/url?q=https%3A%2F%2Fassets.azion.com%2Fglobal%2Fbot-manager%2Fclient-fingerprint%2Fazfp-1.0.0.min.js&sa=D) 
Preciso que sejam atualizadas as docs que referenciam o arquivo azfp-1.0.0.min.js para que apontem para este novo link._
> [EDU-6470]-fix-amend-new-link-in-bot-manager-docs

- src/content/docs/en/pages/guides/create-button/create-button.mdx
- src/content/docs/en/pages/guides/edge-application/ea-enforce-hls.mdx
- src/content/docs/en/pages/guides/edge-functions/serverless-functions.mdx
- src/content/docs/en/pages/guides/edge-functions/webassembly.mdx
- src/content/docs/en/pages/guides/import-from-github/azion-github-app.mdx
- src/content/docs/en/pages/guides/import-from-github/import-from-github.mdx
- src/content/docs/en/pages/guides/waf/configure-allowed-rules.mdx
Replaced Azion Edge Platform in englosh guides.
> [EDU-6476] fix: replaced Azion Edge Platform in guides - en

- src/content/docs/en/pages/guides/index.mdx
- src/content/docs/en/pages/guides/marketplace/templates/edge-ai-starter-kit.mdx
- src/content/docs/en/pages/main-menu/additional-resources/templates-and-integrations/understand-azion-templates.mdx
- src/content/docs/pt-br/pages/guias/guides.mdx
- src/content/docs/pt-br/pages/guias/marketplace/templates/edge-ai-starter-kit.mdx
- src/content/docs/pt-br/pages/menu-principal/recursos-adicionais/templates-e-integracoes/templates-visao-geral.mdx
> [EDU-6497] Edge AI Starter Kit guide

- cicd/massive-redirect/en.json
- cicd/massive-redirect/pt-br.json
- src/content/docs/en/pages/main-menu/reference/deploy/edge-orchestrator/edge-node.mdx
- src/content/docs/en/pages/main-menu/reference/deploy/edge-orchestrator/edge-orchestrator.mdx
- src/content/docs/en/pages/main-menu/reference/deploy/edge-orchestrator/edge-services.mdx
- src/content/docs/en/pages/main-menu/reference/observe/data-stream/data-stream.mdx
- src/content/docs/en/pages/main-menu/reference/observe/real-time-events/real-time-events.mdx
- src/content/docs/en/pages/main-menu/reference/observe/real-time-metrics/first-steps.mdx
- src/content/docs/en/pages/main-menu/reference/observe/real-time-metrics/historical-real-time-metrics/historical-real-time-metrics.mdx
- src/content/docs/en/pages/main-menu/reference/observe/real-time-metrics/real-time-metrics.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/deploy/edge-orchestrator/edge-node.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/deploy/edge-orchestrator/edge-orchestrator.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/deploy/edge-orchestrator/edge-services.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/observe/data-streaming/data-streaming.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/observe/real-time-events/real-time-events.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/observe/real-time-metrics/historico-real-time-metrics.mdx
- src/content/docs/pt-br/pages/menu-principal/referencia/observe/real-time-metrics/real-time-metrics.mdx
> [EDU-6790] Update-products-observe-reference
